Treatment summary
coronasafe/care_fe pull request #1284
Opened 2021-05-31 01:20 UTC by divyagar

Closes #1212

Add treatment summary to live consultation. User can also download pdf of this summary.

https://user-images.githubusercontent.com/42246254/120127194-5d775680-c1dc-11eb-96cf-3f454df181ee.mp4

2021-05-31 19:43 UTC, arpancodes requested changes
Everything works fine! Just one thing, after we save or even cancel pdf download the button goes white, it is a focus issue, because it becomes green again after we click somewhere else.
![treatment_summary](https://user-images.githubusercontent.com/42417893/120234665-13db4a00-c276-11eb-9b69-57cc3dee3be7.gif)

2021-05-31 23:35 UTC, aparnacoronasafe commented
@bodhish Preview has failed. Please merge to staging and leave a "test in staging" label

2021-06-01 00:57 UTC, divyagar commented
@arpancodes Thanks for the feedback.
@aparnacoronasafe @bodhish I have fixed the issue.

2021-06-01 03:14 UTC, bodhish commented
@aparnacoronasafe what difference will it make if I merge it to staging 🤔

2021-06-01 06:23 UTC, arpancodes approved these changes
Looks good to me

2021-06-01 06:49 UTC, smartclash requested changes

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/ConsultationDetails.tsx
> +                          <tr className="bg-white">
Add `id` to the table row.

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
Please add `id` to this table row

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                    </tbody>
Please fix this spacing issue

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
Add `id` here too

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                            )}
Fix spacing issue

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
`id` here too

2021-06-01 06:49 UTC, smartclash commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                </tbody>
Spacing issue, please fix :)

2021-06-03 02:41 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                </tbody>
done

2021-06-03 02:41 UTC, divyagar commented on src/Components/Facility/ConsultationDetails.tsx
> +                          <tr className="bg-white">
done

2021-06-03 02:41 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
done

2021-06-03 02:41 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                    </tbody>
done

2021-06-03 02:41 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                            )}
done

2021-06-03 02:42 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
done

2021-06-03 02:42 UTC, divyagar commented on src/Components/Facility/TreatmentSummary.tsx
> +                                                        <tr>
done

2021-06-03 02:44 UTC, divyagar commented
@smartclash @bodhish Done with all changes.

2021-06-05 18:31 UTC, aparnacoronasafe commented
saved Relevant investigations does not appear on the treatment summary

2021-06-05 18:35 UTC, amruthavijay88 commented
Tested. 'Examination details and Clinical conditions' were missing in the print out version - though it was updated.

2021-06-07 02:05 UTC, divyagar commented
@amruthavijay88 @aparnacoronasafe I have made changes.

2021-06-07 04:38 UTC, merged