Refining advanced filter in patients page
coronasafe/care_fe pull request #1324
Opened 2021-06-03 14:33 UTC by sam9111

- Added date range filter based on "Onset of Symptoms Date"

2021-06-05 08:48 UTC, smartclash requested changes

2021-06-05 08:48 UTC, smartclash commented on src/Components/Patient/PatientFilterV2.tsx
> +      // }
Remove the code if not required

2021-06-05 14:01 UTC, samholics commented
tested, failed

when you applied district filter on patients list ;
 . logged in as state  admin, and  selected a  district .but the patient count remains the same. not showing the results
  also the selected district cleared when we came back to filters

. date of onset symptoms filter is working fine

2021-06-06 09:54 UTC, sam9111 commented
The district filter is now working.

![chrome-capture (1)](https://user-images.githubusercontent.com/60708693/120920102-cc701600-c6da-11eb-822f-eb071713428e.gif)

2021-06-06 16:55 UTC, amruthavijay88 commented
Tested, when filtered by a district - it works, but when we re-open advanced filters again - it doesn't show which filter is applied.

2021-06-06 16:56 UTC, amruthavijay88 commented
@sam9111

2021-06-07 17:43 UTC, amruthavijay88 commented
Tested - date range filters and district filters are working fine. Previous mentioned issue is resolved too.

2021-06-09 06:15 UTC, merged