Fix/login page changes
coronasafe/care_fe pull request #1327
Opened 2021-06-03 17:00 UTC by aayushah711

- [x] Innovation Society Logo
- [x] CARE Logo. Push Coronasafe to the bottom of the page with the brief
- [x] Login page title should be 'MahaKavach'
- [x] The 'Central Resource Management Platform' should be a subtitle

2021-06-03 17:07 UTC, bodhish commented
@aayushi-shah-sharechat wrong repo 😅

2021-06-03 17:08 UTC, bodhish commented
@aayushah711 wrong repo 😅

2021-06-05 09:02 UTC, smartclash requested changes

2021-06-05 09:02 UTC, smartclash commented on .prettierrc.json
> +}
Don't add your prettier config. Do delete this.

2021-06-05 09:02 UTC, smartclash commented on src/Components/Shifting/BoardView.tsx
> +            }
Can we use `classnames` package instead?

2021-06-05 09:02 UTC, smartclash commented on src/Components/Shifting/BoardView.tsx
> +            }
Can we use `classnames` package instead?

2021-06-05 18:01 UTC, aparnacoronasafe commented
@bodhish What do we do about this? wrong repo. please close or deal appropriatly

2021-06-05 18:14 UTC, closed without merging