Updating the test status to POSITIVE/NEGATIVE
coronasafe/care_fe pull request #1333
Opened 2021-06-04 14:00 UTC by Sandra3657

Resolves #1167

If the current status and result is COMPLETED and AWAITING respectively, it is now possible to edit the result to POSITIVE or NEGATIVE.

2021-06-04 15:57 UTC, amruthavijay88 commented
Tested - When we select 'test completed' and click 'awaiting' - there is no option to update it as positive/negative later.

2021-06-05 08:59 UTC, smartclash requested changes

2021-06-05 08:59 UTC, smartclash commented on src/Components/Patient/UpdateStatusDialog.tsx
> +  // .filter(i => roleStatusMap[userType] && roleStatusMap[userType].includes(i.text))
can we remove this?

2021-06-05 12:51 UTC, Sandra3657 commented
Where has the test failed? Its working in the deploy preview. @amruthavijay88

2021-06-06 16:48 UTC, amruthavijay88 commented
@Sandra3657 - we had discussed on steps over yesterday's EOD call? Do you need clarity?

2021-06-07 04:03 UTC, Sandra3657 commented
Yes please. I have tried recreating the steps, and their was no issue. So I may have done it wrong. So, can you please repeat the steps? @amruthavijay88.

2021-06-07 17:25 UTC, amruthavijay88 commented
1. Open a patient card
2.  Click Request Sample test
3.  Fill in details and assign test facility name 'hi tech test' and submit
4.  Logout and login as user of Hi tech test facility
5. Click sample test
6. Go until test completed and click awaiting
7.  Card freezes - you can't made further edits if you put awaiting.

2021-06-07 17:26 UTC, amruthavijay88 commented
@Sandra3657

2021-06-09 07:31 UTC, aparnacoronasafe commented
tested in preview

2021-06-09 17:18 UTC, amruthavijay88 commented
Tested - failed. Screenshots below - 

1. While adding 'awaiting status'
![image](https://user-images.githubusercontent.com/67979586/121399891-88983d80-c974-11eb-85ab-ebc6d91df224.png)

2. While trying to update status as positive/negative - is taken off.

![image](https://user-images.githubusercontent.com/67979586/121400002-a9f92980-c974-11eb-963d-3dfe0b3ae25a.png)

2021-06-11 10:57 UTC, Sandra3657 commented
It is working in preview. @amruthavijay88 

![test](https://user-images.githubusercontent.com/62461536/121676028-c494e500-cad1-11eb-83c7-9c71b1f0848e.gif)

2021-06-11 15:40 UTC, nihal467 commented
![error 1](https://user-images.githubusercontent.com/57055998/121711103-dd17f600-caf7-11eb-8129-79f6a92d8de1.PNG)

step 1: Update the sample test test to 'approved'
step 2: Select 'new status', choose 'test completed' and in Result choose 'invalid'

Even the test in completed, the 'update sample test status' button appear in the screen

2021-06-12 08:45 UTC, nihal467 commented
test approved

2021-06-12 09:48 UTC, bodhish commented
@Sandra3657 can you fix the merge conflicts

2021-06-12 12:01 UTC, merged