Deleting users by the District Admin
coronasafe/care_fe pull request #1339
Opened 2021-06-05 06:33 UTC by Sandra3657

Resolves #1309 

The district admins can now delete users of the user types which the district admins can create. The district admins cannot delete users, that are above them (State Admin, State Lab Admin etc).

![delete](https://user-images.githubusercontent.com/62461536/120882497-f0a5f700-c5f5-11eb-9928-262098b13574.gif)

2021-06-05 08:56 UTC, smartclash requested changes

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +  // console.log(isSuperuser, userType);
Let's remove this

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +    // setReload(!reload);
and this too

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +    console.log(user);
and this

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +        }`}
Can we use `classnames` package here?

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +          <div className="flex items-center mb-2">
Please add a `key` here.

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +      console.log(user);
Let's remove this

2021-06-05 08:56 UTC, smartclash commented on src/Components/Users/ManageUsers.tsx
> +    console.log(userData);
and this

2021-06-05 13:11 UTC, Sandra3657 commented on src/Components/Users/ManageUsers.tsx
> +        }`}
Yes. Have added it.

2021-06-05 14:11 UTC, smartclash approved these changes

2021-06-05 17:15 UTC, amruthavijay88 commented
Tested, unable to delete someone of staff user type. Warning comes - which says 'Not found' and then the user seems to exist after deletion.

2021-06-06 09:25 UTC, shaileshaanand commented
I can delete Staff users from my local backend but not from staging

2021-06-06 11:10 UTC, Sandra3657 commented
Can you say which user is that? I have tested it out with a usertype of Staff and I am able to delete the user. @amruthavijay88

2021-06-06 16:45 UTC, amruthavijay88 commented
Tested again, unable to delete users with 'staff' user access in staging again.

2021-06-06 16:45 UTC, amruthavijay88 commented
@Sandra3657 @shaileshaanand

2021-06-06 17:52 UTC, nihal467 commented
@Sandra3657 

step 1: Create a user id for example "test-arun"
step 2: delete the staff user-id "test-arun"
step 3: create again the same user-id "test-arun"

You will have a notification that 'user-id already exists' but in the front end, you will not be able to see the user id.

2021-06-06 17:59 UTC, bodhish commented
@nihal467 we do a soft delete. You can't re-use a user id that's already used.

2021-06-06 18:02 UTC, bodhish commented
![image](https://user-images.githubusercontent.com/14979190/120935228-5f32a400-c71f-11eb-8afe-389f83ec8fe8.png)


When I tried to delete a district admin the API crashed. Do handle these edge cases.

2021-06-06 18:04 UTC, bodhish commented
@vigneshhari Any idea why I am getting a 404 for the delete endpoint 🤔

2021-06-06 18:09 UTC, bodhish commented
Also Update 

```
  deleteUser: {
    path: "/api/v1/users",
    method: "DELETE",
  },
```
with

```
  deleteUser: {
    path: "/api/v1/users/",
    method: "DELETE",
  },

```

api.txs

2021-06-07 00:03 UTC, vigneshhari commented
@bodhish 404 is thrown the user does not have access to delete that user , dist admin trying to delete other districts dist admin/staff or a state admin or cases like that.

2021-06-07 04:31 UTC, bodhish commented
That's nice. Please hide the delete button for those users

2021-06-07 10:44 UTC, Sandra3657 commented
For a district admin, the dropdown for adding new users contains `DistrictAdmin` and `DistrictReadOnlyAdmin` as an option too. So if a district admin cannot delete another district admin, he shouldn't be able to able to create one too, right? @bodhish 

<img src="https://user-images.githubusercontent.com/62461536/121003207-e547fc80-c7aa-11eb-878e-bf92483f188d.png" width=50%/>

2021-06-07 12:19 UTC, bodhish commented
Delete should be down by a user with one level more access.

2021-06-09 07:16 UTC, aparnacoronasafe commented
<img width="1048" alt="Screenshot 2021-06-09 at 12 45 12 PM" src="https://user-images.githubusercontent.com/67050716/121310087-98863200-c920-11eb-9a9c-e496eebe75f4.png">

When trying to delete staff, "Something went wrong" notification comes up

2021-06-09 13:27 UTC, Sandra3657 commented
It was working in the deploy preview, soon after the last commit. It is still working in my local server, although not in the deploy preview now. @aparnacoronasafe @bodhish

2021-06-11 16:29 UTC, nihal467 commented
![error1](https://user-images.githubusercontent.com/57055998/121718734-3edc5e00-cb00-11eb-8918-de6071daed6d.PNG)

Test failed, not able to delete a user with 'staff' role

2021-06-11 17:35 UTC, aparnacoronasafe commented
> It was working in the deploy preview, soon after the last commit. It is still working in my local server, although not in the deploy preview now. @aparnacoronasafe @bodhish

@bodhish Please look at this

2021-06-12 08:21 UTC, bodhish commented
@Sandra3657 get help from cef in slack

2021-06-12 13:39 UTC, arpancodes commented
Implemented the following:
- [x] District admin can delete the users below it in the same district
- [x] State Admin can delete users from the same state
- [x] User below the District Admin won't be able to see the delete button
- [x] In rare case, if the user tries to delete a user that they don't have the permission for, `permission denied` alert will be shown.

Please test @amruthavijay88 @aparnacoronasafe

2021-06-13 14:24 UTC, nihal467 commented
![errorror](https://user-images.githubusercontent.com/57055998/121811084-d49ef700-cc80-11eb-9af7-0b3528c3fc51.PNG)


test failed, with a district admin access, when I am trying to delete a staff user, a pop-up alert 'permission denied'

2021-06-13 15:07 UTC, arpancodes commented
This is only happening in deploy preview! I tried deleting same staff in both local server and deploy preview. Check this out:
In local server:
![delete_staff_localhost](https://user-images.githubusercontent.com/42417893/121812804-f1d6c400-cc86-11eb-8fe1-208a00eed981.gif)

in deploy preview:
![delete_staff_deploy_preview](https://user-images.githubusercontent.com/42417893/121812810-f4d1b480-cc86-11eb-8e56-0698f10b6188.gif)

2021-06-14 07:31 UTC, nihal467 commented
test failed, using a state admin access, I can delete another state admin privilege account

2021-06-14 08:47 UTC, arpancodes commented
@nihal467 if you were able to delete that means it's possible from the server else you'd see a permission denied, should I disable the delete button just on the frontend?

2021-06-14 08:54 UTC, nihal467 commented
@vigneshhari  @bodhish check this issue

2021-06-14 09:04 UTC, vigneshhari commented
You can delete other stateadmins provided they are in the same state.

2021-06-14 21:07 UTC, aparnacoronasafe commented
cannot find the option in preview

2021-06-15 00:18 UTC, arpancodes commented
@aparnacoronasafe You can only see delete button for the one you have access to delete for example, a district admins can delete the ones with lower access but in the same district.
![image](https://user-images.githubusercontent.com/42417893/121974524-348ac000-cd9d-11eb-914a-694773d46478.png)

2021-06-15 08:00 UTC, aparnacoronasafe commented
@arpancodes my bad!! yes tested in preview

2021-06-15 08:01 UTC, bodhish commented
@arpancodes can you resolve the merge conflicts 
Good to merge after that

2021-06-15 08:30 UTC, amruthavijay88 commented
Tested in Netlify. Logged in as a district admin, can't seem to find delete button? 

![image](https://user-images.githubusercontent.com/67979586/122019971-f8c61980-cde1-11eb-87c7-79c0f20ce613.png)

2021-06-15 08:34 UTC, aparnacoronasafe commented
@amruthavijay88 

Check Arpans comment above...:-/

2021-06-15 08:46 UTC, amruthavijay88 commented
@aparnacoronasafe - My bad, didn't notice it was another state's staff.

2021-06-15 09:01 UTC, arpancodes commented
@bodhish yaa will do that

2021-06-16 08:26 UTC, merged