Facility cypress
coronasafe/care_fe pull request #1361
Opened 2021-06-08 02:51 UTC by divyagar

2021-06-08 11:24 UTC, smartclash commented
Instead of making this whole test a single unit? Can you branch it up? 

Like one unit for  `Create facility` another one for `Add bed types` and so on?

It's simple. Just refactor the code to be inside multiple `it` blocks

2021-06-08 11:25 UTC, smartclash requested changes
~Instead of making this whole test a single unit? Can you branch it up?~

~Like one unit for Create facility another one for Add bed types and so on?~

~It's simple. Just refactor the code to be inside multiple it blocks~

Never mind, just understood the flow for creation of a facility.

2021-06-08 11:59 UTC, smartclash requested changes

2021-06-08 11:59 UTC, smartclash commented on cypress/integration/authentication/facility.spec.ts
> +function verifyNotification(text){
```suggestion
const verifyNotification = text => {
```

2021-06-08 11:59 UTC, smartclash commented on cypress/integration/authentication/facility.spec.ts
> +){
```suggestion
const facilityForm = (
    type, name,
    state, district,
    localbody, ward,
    address, pincode, tel,
    oxygen_capacity, oxygen_requirement,
    type_b_cylinders, expected_type_b_cylinders,
    type_c_cylinders, expected_type_c_cylinders,
    type_d_cylinders, expected_type_d_cylinders,
    kasp_empanelled
) => {
```

2021-06-08 11:59 UTC, smartclash commented on cypress/integration/authentication/facility.spec.ts
> +
```suggestion

```

2021-06-08 11:59 UTC, smartclash commented on cypress/integration/authentication/facility.spec.ts
> +
```suggestion
    
```

2021-06-09 02:04 UTC, divyagar commented
@smartclash Can you please review the commits that are added now?

2021-06-11 14:29 UTC, abhinandanarya06 requested changes
Fetch changes from `develop` branch and fix the following suggestions

2021-06-11 14:29 UTC, ghost commented on cypress/integration/authentication/facility.spec.ts
> +
Currently every tests seems to be inside `authentication` folder and these line of code is repeating on every tests. 

Shift this authentication part to support directory

2021-06-11 14:29 UTC, ghost commented on cypress/support/commands.js
> -// Cypress.Commands.add('login', (email, password) => { ... })
here we could add authentication part

2021-06-11 14:30 UTC, abhinandanarya06 commented on cypress/support/commands.js
> -// Cypress.Commands.add('login', (email, password) => { ... })
with extra option of `roles` like `staff` or `admin` 😅

2021-06-11 14:32 UTC, smartclash commented on cypress/support/commands.js
> -// Cypress.Commands.add('login', (email, password) => { ... })
That should be a separate PR @abhinandanarya06

2021-06-11 16:17 UTC, abhinandanarya06 commented on cypress/support/commands.js
> -// Cypress.Commands.add('login', (email, password) => { ... })
oh there are other cypress PR with same issue hmm.

2021-06-11 16:17 UTC, abhinandanarya06 approved these changes

2021-06-12 07:36 UTC, bodhish commented on src/Components/Facility/FacilityCreate.tsx
> +                  data-test="facility-name"
```suggestion
                  id="facility-name"
```

Why can't we add this as Id for the input? 
The label should have an `htmlFor`

2021-06-12 07:37 UTC, bodhish approved these changes

2021-06-12 07:37 UTC, bodhish requested changes
Use `id` instead of `data-test` where ever possible

2021-06-12 14:27 UTC, divyagar commented
@bodhish Done

2021-06-14 08:33 UTC, smartclash approved these changes

2021-06-15 07:59 UTC, merged