Add webpush notifications
coronasafe/care_fe pull request #1373
Opened 2021-06-09 11:26 UTC by ProCode2

Adding web push notifications for various actions on the site.

# ***`[work in progress]`***

2021-06-16 18:25 UTC, Apurva-Nagar commented
@bodhish 

- [ ] Configure Workbox to use custom ServiceWorker code
- [ ] Show notifications when triggered (with hardcoded information for now)
- [ ] handle multi-device subscription logic
- [ ] handle notification click (with hardcoded information for now)
- [ ] Resolve to correct page on notification click.

2021-06-18 18:50 UTC, bodhish requested changes

2021-06-18 18:50 UTC, bodhish commented on src/Components/Notifications/ShowPushNotification.tsx
> +  };
Can we use the `fire_request` Helper

2021-06-18 18:50 UTC, bodhish commented on src/Components/Notifications/NotificationsList.tsx
> +    );
Can we use the `fire_request` Helper

2021-06-18 18:50 UTC, bodhish commented on src/Components/Notifications/NotificationsList.tsx
> +            );
Can we use the `fire_request` Helper

2021-06-18 18:50 UTC, bodhish commented on src/Components/Notifications/NotificationsList.tsx
> +    });
Can we use the `fire_request` Helper

2021-06-18 18:50 UTC, bodhish commented on webpack.config.js
> +  // }
Can we disable push notification in development for better performance while compiling?

2021-06-18 21:13 UTC, bodhish approved these changes
Nice 🔥

2021-06-18 21:14 UTC, bodhish approved these changes

2021-06-18 21:15 UTC, merged