Revamp Sample Management : Result: File Upload
coronasafe/care_fe pull request #1390
Opened 2021-06-12 13:14 UTC by shaileshaanand

This PR adds a FIle Upload option in Sample Test Completion Dialog for Staff to upload a Report.

Fixes https://github.com/coronasafe/care_fe/issues/1382

![FileUpload](https://user-images.githubusercontent.com/26682202/121777107-fc715a80-cbad-11eb-90d8-f0002741a298.gif)

2021-06-20 16:53 UTC, samholics commented
tested, failed

file upload feature is available on sample test, but preview is not available.
where can i find the preview of that uploaded result?????? @shaileshaanand

2021-06-25 17:21 UTC, nihal467 commented
test approved

2021-06-25 17:23 UTC, nihal467 commented
@shaileshaanand @bodhish there is a branch conflict

2021-06-25 19:18 UTC, abhinandanarya06 requested changes
Fix the problem below

2021-06-25 19:18 UTC, ghost commented on src/Components/Patient/SampleDetails.tsx
> +      />
![image](https://user-images.githubusercontent.com/52771399/123466958-935a0000-d60d-11eb-80c6-1379566bbb0e.png)

Can you fix the alignment of `Download` and `Close` button. May be it was not noticed early 😅 

Also can you made it so that it open pdf in full screen mode by default or its fine to have pages overview. Not much need

2021-06-25 19:18 UTC, ghost commented on src/Components/Patient/SampleDetails.tsx
> +        </Button>
## Bug 
![image](https://user-images.githubusercontent.com/52771399/123468016-d49edf80-d60e-11eb-903c-9110dd69b639.png)

When i click this button to go to icmr specimen form, it prompt `not found`
Don't know what not found 😅 

This above image, i tried clicking button from [this route](http://localhost:4000/sample/f8b1d215-3e68-44dc-8470-53af186f909d)

2021-06-25 19:18 UTC, ghost commented on src/Components/Patient/UpdateStatusDialog.tsx
> +};
I think this is already defined in `FileUpload.tsx`. No need to redefine

2021-06-25 19:18 UTC, ghost commented on src/Components/Patient/SampleTestCard.tsx
> +                `/patient/${patientId}/test_sample/${itemData.id}/details`
I didn't understand, in sample list page there are sample test cards as follows
![image](https://user-images.githubusercontent.com/52771399/123473954-ebe1cb00-d616-11eb-8653-b9409dd6d5b3.png)
where `View Sample Report` button redirects to `icmr_sample` route instead of `details` route

whereas card in patient view page, it is redirecting to `details` route
Is it right ? Noticing ambiguity between these two

2021-06-25 19:18 UTC, abhinandanarya06 commented on src/Components/Patient/UpdateStatusDialog.tsx
> +  const [reload, setReload] = useState<boolean>(false);
i am not getting any special purpose of `reload` state, can you clarify what is its need?

2021-06-26 08:34 UTC, smartclash requested changes

2021-06-26 08:34 UTC, smartclash commented on src/Components/Patient/FileUpload.tsx
> +  sampleId?: any;
can we not use `any`?

2021-06-26 08:34 UTC, smartclash commented on src/Components/Patient/UpdateStatusDialog.tsx
> +const LinearProgressWithLabel = (props: any) => {
define types for the props, if possible.

2021-06-26 08:34 UTC, smartclash commented on src/Components/Patient/UpdateStatusDialog.tsx
> +  const handleUpload = async (e: any) => {
types

2021-06-26 08:34 UTC, smartclash commented on src/Components/Patient/UpdateStatusDialog.tsx
> +  const uploadfile = (response: any) => {
types

2021-06-28 20:19 UTC, aparnacoronasafe commented
Tested in preview

@shaileshaanand in preview, the file is opening very zoomed in. Could you make it fit the frame ?

2021-06-30 11:59 UTC, shaileshaanand commented on src/Components/Patient/SampleDetails.tsx
> +      />
The File Preview component is used here and is not a part of this commit, It should be a separate PR

2021-06-30 13:02 UTC, shaileshaanand commented on src/Components/Patient/SampleTestCard.tsx
> +                `/patient/${patientId}/test_sample/${itemData.id}/details`
We need patient id to generate the icmr form which is not present in the details route from sample management page, hence I created a separate route from the patient page with the patient ID

2021-06-30 13:11 UTC, abhinandanarya06 commented on src/Components/Patient/SampleTestCard.tsx
> +                `/patient/${patientId}/test_sample/${itemData.id}/details`
ohk then fine

2021-06-30 13:13 UTC, abhinandanarya06 commented on src/Components/Patient/UpdateStatusDialog.tsx
> +  const [reload, setReload] = useState<boolean>(false);
i think there is no use of `reload` state as its value is changing but never used anywhere except in `setReload`

2021-06-30 13:48 UTC, shaileshaanand commented
> Tested in preview
> 
> @shaileshaanand in preview, the file is opening very zoomed in and i dont see an option to zoom out. Could you make it fit the frame ?

The zoom buttons are there already
![Screenshot from 2021-06-30 19-15-48](https://user-images.githubusercontent.com/26682202/123971709-e9e18880-d9d7-11eb-83bf-162616d16318.png)

2021-06-30 16:44 UTC, abhinandanarya06 approved these changes
LGTM, Good Job !!!

2021-07-07 04:46 UTC, nihal467 commented
![error 2](https://user-images.githubusercontent.com/57055998/124701553-6e6a6480-df0c-11eb-82af-988045d6b70d.PNG)


test failed, the preview is not having a zoom in or out function when a .png file is uploaded

2021-07-08 02:29 UTC, shaileshaanand commented
> ![error 2](https://user-images.githubusercontent.com/57055998/124701553-6e6a6480-df0c-11eb-82af-988045d6b70d.PNG)
> 
> test failed, the preview is not having a zoom in or out function when a .png file is uploaded

@nihal467 If files had extension in Upper case the zoom buttons were not appearing, Fixed the issue.

2021-07-08 13:35 UTC, bodhish commented
@nihal467 can you test

2021-07-08 16:24 UTC, nihal467 commented
test approved

2021-07-08 19:01 UTC, merged