Send facility specific messages via notification
coronasafe/care_fe pull request #1454
Opened 2021-06-21 21:57 UTC by Apurva-Nagar

Allows sending of messages to subscribed users of a facility via notifications.
![Button](https://user-images.githubusercontent.com/8392802/122832827-8eddd080-d309-11eb-8f84-5820512f2158.png)
![Modal](https://user-images.githubusercontent.com/8392802/122832884-ac129f00-d309-11eb-9560-d093b7185985.png)

2021-06-21 22:01 UTC, Apurva-Nagar commented
@bodhish should the notify button be shown for all users or some specific user roles?

2021-06-25 16:58 UTC, bodhish requested changes

2021-06-25 16:58 UTC, bodhish commented on webpack.config.js
> +  // }
@Apurva-Nagar can you revert it 
```suggestion
  if (isDev) {
    return [];
  }
```

2021-06-25 17:11 UTC, nihal467 commented
https://user-images.githubusercontent.com/57055998/123461198-6c4c0000-d606-11eb-9268-f264378de6e9.mp4

test failed, the notification can be sent but once I use the function, I can't close the screen for going back to my dashboard

2021-06-25 21:06 UTC, bodhish commented on src/Components/Facility/HospitalList.tsx
> +                                Type your message...
This should be placeholder

2021-07-01 14:19 UTC, closed without merging