Add Time to Date Range Picker in Patient Filter Page
coronasafe/care_fe pull request #1470
Opened 2021-06-24 12:56 UTC by abhinandanarya06

## Issue: #1076 

## Proposed Changes
1. Added `src/Components/Common/DateTimeRangePicker.tsx` which is custom material ui based date time range picker. 
    - **Reason**: Couldn't use another because other don't have corresponding `@types` available and gives many errors with jsx.
2. Updated Patient Filter page to use above component 

## Merge Checklist
- [ ] Filter correctly working
- [ ] UI/UX Improved

![bdfd9f95-3074-4929-b752-6b4f404f2042](https://user-images.githubusercontent.com/52771399/123266427-89d87700-d4eb-11eb-9293-2f865eddc722.gif)

closes #1076

2021-06-24 13:16 UTC, developedBySJ commented on src/Components/Common/DateTimeRangePicker.tsx
> +  const [focusInput, setFocusInput] = React.useState<any>(null);
Remove this line as it is not needed

2021-06-24 13:17 UTC, abhinandanarya06 commented on src/Components/Common/DateTimeRangePicker.tsx
> +  const [focusInput, setFocusInput] = React.useState<any>(null);
oh forgot that thanks

2021-06-24 13:27 UTC, developedBySJ reviewed
Looks good

2021-06-25 01:46 UTC, khavinshankar commented on src/Components/Common/DateTimeRangePicker.tsx
> +        </button>
```suggestion
        {(startDate || endDate) && <button
          className="text-xs font-semibold px-2 bg-red-200 hover:bg-red-300 rounded uppercase float-right mr-1 ml-auto"
          onClick={() => {
            onChange({ startDate: null, endDate: null });
          }}
        >
          X Clear
        </button>}
```

2021-06-25 01:50 UTC, khavinshankar approved these changes
```js
{(startDate || endDate) && <button
          className="text-xs font-semibold px-2 bg-red-200 hover:bg-red-300 rounded uppercase float-right mr-1 ml-auto"
          onClick={() => {
            onChange({ startDate: null, endDate: null });
          }}
        >
          X Clear
        </button>}
```


add a simple check so that the `X Clear` shows only when there is some value.

rest LGTM

2021-06-26 08:36 UTC, smartclash requested changes

2021-06-26 08:36 UTC, smartclash commented on src/Components/Common/DateTimeRangePicker.tsx
> +export const getDate = (value: any) =>
let's not use `any`

2021-06-26 14:27 UTC, bodhish commented
Let's not merge this now. The other picker was way better for data selection. 

@aparnacoronasafe can you re-evaluate the actual use of date-time again?

2022-06-08 08:17 UTC, nihal467 commented
@gigincg its been blocked for a long time now, shall we close it

2022-07-02 14:28 UTC, gigincg commented
Stale/Archived

2022-07-02 14:28 UTC, closed without merging