Improved the responsive UI for ResourceBoardView and Shifting boardView
coronasafe/care_fe pull request #2029
Opened 2022-01-13 11:58 UTC by kunatastic

Fixes #2028 

![image](https://user-images.githubusercontent.com/61267953/149325977-0ed7776d-32e0-48be-9a6a-5854c51dd5d1.png)

![image](https://user-images.githubusercontent.com/61267953/149326081-3824c8fc-78c5-4c33-8be1-75038043dc38.png)

2022-01-17 05:39 UTC, gigincg commented
@kunatastic Can you increase the Gap and keep the filters and the List View button in the same row. And I believe you've kept the after ss twice in the PR. Would be nice if you write some description in the PR text for easy review.

Nice find and Nice work

2022-01-17 10:35 UTC, kunatastic commented
Sure!! I will make sure to add the description from next time.

2022-01-20 14:28 UTC, nihal467 commented
tested

2022-01-20 14:37 UTC, gigincg commented
@nihal467 Removing test cleared, I've requested to keep The 2 buttons in the same row. @kunatastic mentioned he'll be incorporating those too.

2022-01-21 12:12 UTC, kunatastic commented
The search bar is a component whose property was sticky to top-0 so I didn't change it. 
The updated new mobile view: 
<img src="https://user-images.githubusercontent.com/61267953/150522776-cf86d861-8636-4f65-92fd-459b3b23a85d.png" width="300px"/>

2022-01-23 04:15 UTC, khavinshankar reviewed
some padding-top to the search bar and some space between all components would make it better.

the UI might look something like this,
![image](https://user-images.githubusercontent.com/29787772/150664559-979bee94-b5ec-44ab-8ed0-afa5de66ae67.png)

2022-01-23 04:15 UTC, khavinshankar commented on src/Components/Shifting/BoardView.tsx
> +        <div className="flex items-end  md:items-center justify-between md:w-2/3 flex-col md:flex-row">
```suggestion
        <div className="flex items-end pt-2 space-y-2 md:items-center justify-between md:w-2/3 flex-col md:flex-row">
```

2022-01-23 04:15 UTC, khavinshankar commented on src/Components/Resource/ResourceBoardView.tsx
> +        <div className="flex items-end  md:items-center justify-between md:w-2/3 flex-col md:flex-row">
```suggestion
        <div className="flex items-end pt-2 space-y-2 md:items-center justify-between md:w-2/3 flex-col md:flex-row">
```

2022-01-25 13:50 UTC, gigincg commented
![image](https://user-images.githubusercontent.com/13028584/150988531-5c8be98e-15e7-4f61-9cc7-352ccb6c1562.png)

@kunatastic In some screen sizes (Tablet Portrait Mode) The Nav area looks broken. The filter button is half off screen and the search bar is too small. Can you fix ?

Suggestion: Keep Search bar in a separate row and the rest in a new row for these screens.

Also, the Resource screen is practically a clone of the Shifting Screen in terms of design, so you could possibly pass on the fixes to that screen as well. This could be a separate Issue/Pull Request

2022-01-25 13:51 UTC, gigincg requested changes
UI Breaking in iPad/Tablet Portrait View

2022-01-25 17:20 UTC, kunatastic commented
Sure I will fix that.

2022-02-18 13:31 UTC, kunatastic commented
Updated Tablet view 

![image](https://user-images.githubusercontent.com/61267953/154691853-4aa5819c-b0db-4719-8962-611908e6253d.png)

2022-02-23 17:41 UTC, nihal467 commented
![pwkefewop](https://user-images.githubusercontent.com/57055998/155376212-afd07693-ad2b-4260-b303-84b6a9c1eea7.jpg)

@kunatastic @gigincg all the buttons like list view, patient name, etc.. seem really close and each of them feels like having different size

2022-05-16 04:59 UTC, closed without merging