added patient details in investigation report
coronasafe/care_fe pull request #2291
Opened 2022-04-30 17:58 UTC by Marmik2003

Fixes #2280 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44599895/166116971-a37f0760-b642-4926-9e7e-70a37bab4dfa.png">

2022-05-04 13:28 UTC, khavinshankar approved these changes
LGTM

2022-05-05 16:09 UTC, nihal467 commented
test approved

2022-05-12 06:37 UTC, gigincg requested changes
I don't think there is a need for a "Patient Details" Title. Simply having the Patient Name, Age etc below the "Report" Title should be enough

2022-05-12 06:37 UTC, gigincg commented on src/Components/Facility/Investigations/Reports/ReportTable.tsx
> +            key={index}
Don't use the Array Index as the Key, unless there is no other unique id available.

2022-05-12 06:37 UTC, gigincg commented on src/Components/Facility/Investigations/Reports/ReportTable.tsx
> +                      onChange={() => {}}
Can't this onChange prop be removed?

2022-05-12 11:02 UTC, Marmik2003 commented on src/Components/Facility/Investigations/Reports/ReportTable.tsx
> +                      onChange={() => {}}
done

2022-05-17 17:59 UTC, gigincg commented
@Marmik2003 The package-lock seems unrelated to the PR. Can you revert the package-lock or merge develop to clear the conflicts.

Also add a screenshot to the updated UI

2022-05-18 05:53 UTC, Marmik2003 commented
![image](https://user-images.githubusercontent.com/44599895/168966739-c61aa973-9710-46f8-af98-e1895ff36e61.png)

2022-05-21 14:25 UTC, merged