Added spinner feedback after pressing login button
coronasafe/care_fe pull request #2341
Opened 2022-05-13 16:40 UTC by ishanExtreme

### Issue Fixed
#2338 

### Updates

- Button changed to submit type
- onClick removed from button since it was already present in form's onSubmit
- Spinner feedback is displayed by clicking log in button until a response is sent back by the server

### Demo

https://user-images.githubusercontent.com/39593226/168328642-1c9d45b6-b0f8-4dd9-8675-fe35eb475376.mp4

2022-05-16 12:36 UTC, developedBySJ commented on src/Components/Auth/Login.tsx
> +    setLoading(true);
Set loading to `true` only if the data is valid.

2022-05-16 12:38 UTC, developedBySJ requested changes

2022-05-16 12:38 UTC, developedBySJ commented on src/Components/Auth/Login.tsx
> +    setLoading(true);
- Remove this line
- Remove else part of `valid ` condition

2022-05-17 02:33 UTC, nihal467 commented
@ishanExtreme @gigincg there is a merging conflict !

2022-05-17 03:07 UTC, ishanExtreme commented
> @ishanExtreme @gigincg there is a merging conflict !

Conflict fixed

2022-05-17 15:09 UTC, merged