Add Other symptoms to Symptoms card
coronasafe/care_fe pull request #2367
Opened 2022-05-15 15:55 UTC by rabilrbl

![image](https://user-images.githubusercontent.com/63334479/168481788-a323952c-026e-4fd7-81be-c6f0af65a148.png)

2022-05-15 16:53 UTC, rabilrbl commented
Closes #2356

2022-05-17 13:28 UTC, nihal467 commented
test approved

2022-05-17 18:29 UTC, gigincg requested changes
@rabilrbl You also need to remove otherSymptoms from the top. Now it's showing up twice

2022-05-17 18:53 UTC, gigincg approved these changes

2022-05-17 18:53 UTC, merged