Added 404 Error Page
coronasafe/care_fe pull request #2386
Opened 2022-05-17 08:40 UTC by skks1212

Closes [https://github.com/coronasafe/care_fe/issues/2352](https://github.com/coronasafe/care_fe/issues/2352)
![image](https://user-images.githubusercontent.com/23238460/168768875-f8de30df-82a1-428e-a5a5-c351a5b3a47a.png)

2022-05-17 13:41 UTC, nihal467 commented
@skks1212 @gigincg  is it good for testing?

2022-05-17 15:45 UTC, tomahawk-pilot commented
@skks1212 can you make this into a single page html with css and we can put this globaly on our domain. 
this looks good

2022-05-17 16:54 UTC, shivankacker commented
> @skks1212 can you make this into a single page html with css and we can put this globaly on our domain. this looks good

Suree! There you go @tomahawk-pilot [https://github.com/skks1212/care_misc/tree/master/error_pages]( https://github.com/skks1212/care_misc/tree/master/error_pages)

2022-05-17 20:28 UTC, tomahawk-pilot commented
Instead of the asset folder let's pull it from a cdn

2022-05-18 07:53 UTC, skks1212 commented
> Instead of the asset folder let's pull it from a cdn

Cool! Can you put it up on the coronasafe cdn? (If we have one?)
Otherwise I will put up on another.

2022-05-31 05:54 UTC, nihal467 commented
test approved

2022-06-01 04:11 UTC, skks1212 commented
@gigincg deploy is failing, can we clear cache?

2022-06-02 07:59 UTC, khavinshankar commented on src/Router/AppRouter.tsx
>      ({ patientId, consultationId }: any) => (
```suggestion
    ({ facilityId, patientId, consultationId }: any) => (
```

_do destructure facilityId from the param before using_

2022-06-02 08:00 UTC, khavinshankar requested changes
please do work on the requested changes

2022-06-02 08:21 UTC, skks1212 commented
> please do work on the requested changes

I don't have access to the cdn, and i think we don't require a cdn for this PR @gigincg what should I do?

2022-06-02 11:30 UTC, skks1212 commented
> please do work on the requested changes

@khavinshankar Done please check

2022-06-03 05:45 UTC, khavinshankar approved these changes

2022-06-03 05:46 UTC, merged