Renamed button from 'Add COVID Suspect/Patient' to 'Add Patient'
coronasafe/care_fe pull request #2398
Opened 2022-05-17 15:36 UTC by GokulramGHV

Fixes #2393 

Renamed the "Add Covid Suspect/Patient" button in the patient registration form to "Add Patient".

Before:
![image](https://user-images.githubusercontent.com/40627011/168851004-1b2946c4-43de-4362-bb40-61849c409586.png)

After:
![image](https://user-images.githubusercontent.com/40627011/168850884-5afbdacf-09e1-4924-9b9c-33be8961fd98.png)

2022-05-17 15:36 UTC, tomahawk-pilot approved these changes

2022-05-17 16:19 UTC, nihal467 commented
![sokfd](https://user-images.githubusercontent.com/57055998/168859985-16437ed6-a909-4309-b60f-904d6f1cd596.jpg)

@gigincg @GokulramGHV this also needs to be changed right?

2022-05-18 13:01 UTC, nihal467 commented
test approved

2022-05-25 06:19 UTC, gigincg requested changes
@GokulramGHV You cannot use the `eslint-disable-next-line`. You need to fix them!

2022-05-25 13:32 UTC, GokulramGHV commented
@gigincg I've made the requested changes.

2022-06-03 05:42 UTC, khavinshankar requested changes
please do work on the requested changes,

**Note:**

- _the unused variables, functions, interfaces and imports can be removed instead of commenting them out_
- _do prioritize on fixing an eslint issue instead of using eslint disable_

2022-06-03 05:42 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +  // DESIGNATION_HEALTH_CARE_WORKER,
do remove the comment

2022-06-03 05:42 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +// import statesList from "../../Common/static/states.json";
do remove the comment

2022-06-03 05:42 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +// );
do remove the unused import and do remove the comment

2022-06-03 05:42 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +// const designationOfHealthWorkers = [...DESIGNATION_HEALTH_CARE_WORKER];
do remove the comment

2022-06-03 05:42 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +  // };
do remove the comment

2022-06-07 05:54 UTC, khavinshankar approved these changes

2022-06-08 10:28 UTC, merged