fix: extra padding on external results page
coronasafe/care_fe pull request #2409
Opened 2022-05-18 05:40 UTC by kunatastic

fixes #2369 

Updated UI 
![image](https://user-images.githubusercontent.com/61267953/168965117-ac298a65-fbf1-44b8-9d5d-31e6dac99b4d.png)

2022-05-18 12:46 UTC, nihal467 commented
![wefiewf](https://user-images.githubusercontent.com/57055998/169041836-6cdb9a1d-4409-4276-bfd7-2cdc16b79537.jpg)

@kunatastic @gigincg test failed, the filter and the buttons are still close

2022-05-19 06:24 UTC, kunatastic commented
Fixed the button's padding 

![image](https://user-images.githubusercontent.com/61267953/169224469-6c11c3d4-5e62-4663-90a7-21ea0c96b626.png)

2022-05-19 07:56 UTC, nihal467 commented
test approved

2022-06-03 04:39 UTC, khavinshankar commented
@kunatastic please do work on the merge conflict

2022-06-07 06:24 UTC, kunatastic commented
@khavinshankar @nihal467 fixed the merge conflict. Apologies for long delay

2022-06-11 11:03 UTC, nihal467 commented
test appproved

2022-06-11 11:17 UTC, khavinshankar requested changes
please do make the recommended changes

2022-06-11 11:17 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
>                }`}
```suggestion
              className={clsx("btn btn-primary", downloadLoading && "pointer-events-none")}
```

_can you please use clsx here, it improves the readability and don't forget to import clsx if not already done so_

2022-06-14 11:21 UTC, kunatastic commented
@khavinshankar worked on suggested changes

2022-06-23 11:32 UTC, cp-Coder approved these changes

2022-06-23 18:00 UTC, nihal467 commented
@kunatastic test failed, the button is not responsive

![8](https://user-images.githubusercontent.com/57055998/175364405-e6cd8bb0-4ff4-4698-8be6-97dea97ca2ca.jpg)

2022-06-28 06:27 UTC, kunatastic commented
made required changes

2022-07-02 08:17 UTC, nihal467 commented
@kunatastic check the conflict file !

2022-07-04 05:40 UTC, kunatastic commented
@nihal467 this pr is good for testing

2022-07-04 17:52 UTC, nihal467 commented
test approved

2022-07-06 09:13 UTC, khavinshankar requested changes

2022-07-06 09:13 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +    resultList = data.map((result: any, _idx: number) => {
```suggestion
    resultList = data.map((result: any) => {
```

`_idx` is an optional parameter, so I think we can just avoid it when we don't use it, this keeps the code clean

2022-07-06 09:13 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +            onClick={(_) =>
```suggestion
            onClick={() =>
```

If event (`_`) is an optional one, so its better to be avoided when we don't use them

2022-07-06 09:13 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +            onClick={(_) => removeFilter(paramKey)}
```suggestion
            onClick={() => removeFilter(paramKey)}
```
If event (_) is an optional one, so its better to be avoided when we don't use them

2022-07-06 09:13 UTC, khavinshankar commented
@kunatastic there are some minor changes, can you please address them

2022-07-06 12:29 UTC, khavinshankar commented
@kunatastic please do work on the merge conflict

2022-07-13 09:49 UTC, khavinshankar approved these changes

2022-07-13 09:49 UTC, merged