Updated the colour of profile badge and fixed errors in the same file
coronasafe/care_fe pull request #2417
Opened 2022-05-18 10:19 UTC by Parthan-Sachin

The user profile has got errors which has been fixed.
![image](https://user-images.githubusercontent.com/50884766/169016869-539d2a3c-f765-461f-9073-df07be22d733.png)

Please refer the image attached.

2022-05-28 07:37 UTC, nihal467 commented
@Parthan-Sachin @gigincg is it good for testing

2022-07-02 20:10 UTC, gigincg requested changes
Given the merge conflict and the issues in the PR, please make a separate PR

2022-07-02 20:10 UTC, gigincg commented on src/Components/Users/UserProfile.tsx
> +  const state: any = useSelector((state1) => state1);
This is unnecessary

2022-07-02 20:10 UTC, gigincg commented on src/Components/Users/UserProfile.tsx
> +    const errors = { ...initError };
errors should be declared as `let` since it's mutated later in this function

2022-07-02 20:10 UTC, closed without merging