fix: add loader to external results section
coronasafe/care_fe pull request #2457
Opened 2022-05-20 15:06 UTC by Pragati1610

loader already exists

- [x] add a state to correct the condition for including the loader

2022-05-20 19:07 UTC, nihal467 commented
test approved

2022-05-24 18:01 UTC, developedBySJ requested changes

2022-05-24 18:01 UTC, developedBySJ commented on src/Components/ExternalResult/ResultList.tsx
> +// function Badge(props: { color: string; icon: string; text: string }) {
Cleanup this code

2022-05-25 06:26 UTC, gigincg commented on src/Components/ExternalResult/ResultList.tsx
> +// function Badge(props: { color: string; icon: string; text: string }) {
@Pragati1610

2022-06-03 14:15 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +    resultList = data.map((result: any, _idx: number) => {
```suggestion
    resultList = data.map((result: any) => {
```

if we are anyways not going to use index (idx), it would be better of not declaring it

2022-06-03 14:16 UTC, khavinshankar requested changes
please do work on the suggested changes

2022-06-03 18:05 UTC, Pragati1610 commented on src/Components/ExternalResult/ResultList.tsx
> +    resultList = data.map((result: any, _idx: number) => {
Removed the unused variable

2022-06-06 13:02 UTC, khavinshankar reviewed
is this state really necessary? can't just do with isLoading?

please do share your thoughts?

2022-07-31 00:14 UTC, nihal467 commented
@khavinshankar what is the status of the PR

2022-08-02 15:13 UTC, closed without merging