Added option for 3rd dose
coronasafe/care_fe pull request #2468
Opened 2022-05-21 07:57 UTC by siddnikh

Had to comment out a few lines in PatientRegister.tsx to allow commit. 
Solves #2037

2022-05-22 08:27 UTC, nihal467 commented
![wpokdqowd](https://user-images.githubusercontent.com/57055998/169685769-1575d18c-ef9c-408b-b47a-d9c542813068.jpg)

@gigincg @siddnikh it is not accepting 3rd dose

2022-05-22 08:30 UTC, gigincg commented
@siddnikh Have you created a backend issue for this?

2022-05-22 08:31 UTC, siddnikh commented
@nihal467 I had to update the backend too. Here's the PR for that: https://github.com/coronasafe/care/pull/775
Please try using that.

2022-05-22 08:32 UTC, siddnikh commented
@gigincg yeah. You can check it out here: https://github.com/coronasafe/care/pull/775

2022-05-28 08:00 UTC, nihal467 commented
test approved

2022-06-03 05:29 UTC, khavinshankar requested changes
please do work on the requested changes,

**Note:**
- _the unused variables, functions, interfaces and imports can be removed instead of commenting them out_
- _do prioritize on fixing an eslint issue instead of using eslint disable_

2022-06-03 05:29 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +  //DESIGNATION_HEALTH_CARE_WORKER,
do remove the comment

2022-06-03 05:29 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +//import statesList from "../../Common/static/states.json";
do remove the comment

2022-06-03 05:29 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +// );
do remove unused variables and do remove the comment

2022-06-03 05:29 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +//const designationOfHealthWorkers = [...DESIGNATION_HEALTH_CARE_WORKER];
do remove the comment

2022-06-03 05:29 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +  // };
do remove the comment

2022-06-10 06:13 UTC, khavinshankar approved these changes

2022-06-10 09:09 UTC, merged