Modal for switching bed fixed
coronasafe/care_fe pull request #2473
Opened 2022-05-21 13:47 UTC by ishanExtreme

### Issue Fixed
fixes #2458 

### Updates

- Added small loader as original loader was making modal unresponsive
- Shifted modal position
- Made modal responsive

### Demo

https://user-images.githubusercontent.com/39593226/169654547-dccda974-af7b-4e7f-a6a0-43f3b4b22566.mp4

2022-05-22 08:35 UTC, nihal467 commented
![eoifjw](https://user-images.githubusercontent.com/57055998/169685991-23be60b4-73e6-4ea2-8750-f9757e653762.jpg)

@ishanExtreme @gigincg test failed, 
- the UI is very small
- the date is not auto fetching
- the date is not fully visible

2022-05-22 08:47 UTC, ishanExtreme commented
@nihal467 
Can you give more details about date auto fetching issue.

2022-05-22 09:01 UTC, nihal467 commented
@ishanExtreme @gigincg when we click the switch bed, button, the date of shifting column should be auto-filled with the current time and date

2022-05-24 17:17 UTC, ishanExtreme commented
@nihal467 
Fixed above issues

2022-05-28 08:10 UTC, nihal467 commented
![epjof](https://user-images.githubusercontent.com/57055998/170816772-2afc5b74-ab1a-4bdf-b099-6ec4db0e4442.jpg)

@ishanExtreme @gigincg test failed, when we click the switch bed button, the current date and time are not been auto fetched

2022-05-28 11:24 UTC, ishanExtreme commented
@nihal467 
After the new changes, I pushed 4 days a go, date of shift is now fetching current date
![Screenshot from 2022-05-28 16-51-39](https://user-images.githubusercontent.com/39593226/170823356-81839717-7c06-4967-9f51-2b872e698deb.png)

2022-05-28 11:39 UTC, ishanExtreme commented
@nihal467 
Nelify preview build is not showing the latest changes

2022-05-28 13:22 UTC, rithviknishad commented
Netlify preview does show up with current date time for me.

![image](https://user-images.githubusercontent.com/25143503/170827410-dc225c9e-b9c1-4893-8337-322ed5e314d5.png)

2022-05-31 05:43 UTC, nihal467 commented
test approved

2022-06-03 05:16 UTC, khavinshankar requested changes
please do remove the comments and console logs

2022-06-03 05:16 UTC, khavinshankar commented on src/Components/Facility/Consultations/Beds.tsx
> +  console.log(current);
do remove console logs

2022-06-03 05:16 UTC, khavinshankar commented on src/Components/Facility/Consultations/Beds.tsx
> +    // small loader for modal
do remove the comment

2022-06-03 05:16 UTC, khavinshankar commented on src/Components/TeleIcu/Patient/InfoCard.tsx
> +  // console.log(patient);
do remove this comment

2022-06-10 06:10 UTC, khavinshankar approved these changes

2022-06-10 06:11 UTC, khavinshankar commented on src/Components/Facility/Consultations/Beds.tsx
> +  console.log(current);
```suggestion
```

2022-06-10 06:12 UTC, khavinshankar approved these changes

2022-06-10 08:21 UTC, merged