Removed overlapping Fixes Issue#2492
coronasafe/care_fe pull request #2499
Opened 2022-05-24 03:35 UTC by Pranshu1902

Removed overlap and made the buttons better

![image](https://user-images.githubusercontent.com/70687348/169943593-157265cb-2f0f-4ce8-867e-ce227545a314.png)

2022-05-24 03:39 UTC, Pranshu1902 commented
Fixes #2492

2022-05-27 19:26 UTC, nihal467 commented
![oekwpfew](https://user-images.githubusercontent.com/57055998/170777316-8d38817c-b349-49c2-bf37-19a46df2c3af.jpg)
@gigincg @Pranshu1902 
test failed, unable to see the button

2022-05-28 08:53 UTC, Pranshu1902 commented
@nihal467 I meant the pagination buttons, they were overlapping before
![Screenshot (333)](https://user-images.githubusercontent.com/70687348/170818378-aeb9a93e-bc61-493f-92ad-7c0127fba140.png)

2022-05-31 08:21 UTC, rithviknishad commented
@Pranshu1902 deploy preview is failing. merge the latest develop branch.

2022-06-01 14:48 UTC, nihal467 commented
@Pranshu1902 @gigincg the pagination is missing, can you share me the patient URL, which you used

2022-06-02 05:03 UTC, Pranshu1902 commented
http://localhost:4000/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8/consultation/d794ba54-da42-4238-8ba9-0b628ca60069

2022-06-04 06:15 UTC, nihal467 commented
test approved

2022-06-06 12:56 UTC, khavinshankar requested changes
please make the requested changes

2022-06-06 12:56 UTC, khavinshankar commented on src/Components/Facility/Consultations/DailyRoundsList.tsx
> +        <div key={`daily_round_${idx}`} className="w-ful">
is `w-ful` a valid tailwind class 😕? please do check this one

2022-06-06 12:56 UTC, khavinshankar commented on src/Components/Common/Pagination.tsx
> +          onClick={(e) => handleChangePage("next")}
```suggestion
          onClick={() => handleChangePage("next")}
```

2022-06-06 12:56 UTC, khavinshankar commented on src/Components/Common/Pagination.tsx
> +          onClick={(e) => handleChangePage("prev")}
```suggestion
          onClick={() => handleChangePage("prev")}
```

2022-06-06 12:56 UTC, khavinshankar commented on src/Components/Common/Pagination.tsx
> +        onClick={(e) => handleChangePage(label.toLowerCase())}
```suggestion
        onClick={() => handleChangePage(label.toLowerCase())}
```

2022-06-06 15:28 UTC, Pranshu1902 commented
@khavinshankar done

2022-06-07 05:59 UTC, khavinshankar approved these changes

2022-06-08 10:44 UTC, gigincg approved these changes

2022-06-08 10:50 UTC, merged