Darken labels and fix col gap under profile
coronasafe/care_fe pull request #2567
Opened 2022-05-28 17:41 UTC by rabilrbl

Fixes #2566

Before:
![image](https://user-images.githubusercontent.com/63334479/170836700-423e2b43-bfc9-4d2c-acd3-0b8c89baf93c.png)

After:
![image](https://user-images.githubusercontent.com/63334479/170836627-8fb34b40-1624-4f3d-aafe-8dcc4fc4c028.png)

- less code repetitions

2022-05-30 09:31 UTC, nihal467 commented
@rabilrbl @gigincg the deploy preview failed

2022-05-31 05:42 UTC, developedBySJ requested changes

2022-05-31 05:42 UTC, developedBySJ commented on src/Components/Users/UserProfile.tsx
> +  const LabelValueCard = (props: { children: React.ReactNode }) => (
Avoid Declaring React Component Inside Parent Component.
 
 Move component outside

2022-05-31 08:12 UTC, rithviknishad commented
@rabilrbl deploy preview is failing. merge the latest develop branch.

2022-06-02 08:22 UTC, nihal467 commented
test approved

2022-06-02 09:18 UTC, khavinshankar approved these changes

2022-06-02 09:19 UTC, khavinshankar commented
@rabilrbl please do work on the merge conflicts

2022-06-04 12:15 UTC, developedBySJ approved these changes
You can keep components within a file if they are closely related or only used once.

2022-06-10 06:02 UTC, khavinshankar approved these changes

2022-06-10 06:02 UTC, merged