Fix empty whatsapp no. field
coronasafe/care_fe pull request #2594
Opened 2022-05-31 12:36 UTC by rabilrbl

Close #2593

2022-05-31 12:43 UTC, gigincg commented on src/Components/Users/UserAdd.tsx
> +    } else if (state.form.phone_number === state.form.alt_phone_number) {
Is this `else` condition needed?

Isn't it better to handle it on the onChange of the checkbox?

2022-05-31 12:45 UTC, rabilrbl commented on src/Components/Users/UserAdd.tsx
> +    } else if (state.form.phone_number === state.form.alt_phone_number) {
Agree 👍

2022-05-31 12:56 UTC, gigincg commented
@rabilrbl I think the onChange should clear the field only when going from true-false

Otherwise there is a chance that the effect gets triggered before this and thereby clearing the field when marking it true

2022-05-31 12:58 UTC, gigincg commented
@rabilrbl also the effect need not be triggered when alt phone changes

2022-05-31 13:30 UTC, nihal467 commented
@gigincg @rabilrbl is it good for testing, the preview is failed?

2022-05-31 13:39 UTC, rabilrbl commented
@nihal467 waiting for @gigincg  approval

2022-06-01 01:50 UTC, gigincg requested changes

2022-06-01 01:50 UTC, gigincg commented on src/Components/Users/UserAdd.tsx
> +                    setPhoneIsWhatsApp(!phoneIsWhatsApp);
Shouldn't it be setState(checked)

2022-06-01 02:35 UTC, nihal467 commented
@rabilrbl @gigincg the deployment preview is failed

2022-06-01 03:16 UTC, nihal467 commented
test approved

2022-06-01 06:41 UTC, merged