Assign Bed or Switch Bed button is visible only for Live Patients
coronasafe/care_fe pull request #2675
Opened 2022-06-11 07:26 UTC by patelaryan7751

Fixes #2673 

# Bugs Fixed

## Assign Bed or Switch Bed button is visible only for Live Patients
![image](https://user-images.githubusercontent.com/59426397/173178067-e62d1c97-f919-4312-b7eb-be8fe816cb9c.png)

2022-06-11 07:44 UTC, patelaryan7751 commented
Deploy Preview Ready https://deploy-preview-2675--care-net.netlify.app/

2022-06-11 13:52 UTC, skks1212 commented
Hey @patelaryan7751 can you add this as a commit to #2563 and close this pr ?
Because the UI will be completely changing with that PR so...

2022-06-11 13:54 UTC, nihal467 commented
test approved

2022-06-20 02:10 UTC, patelaryan7751 commented
Done Changes as per new UI #2563

2022-06-20 02:11 UTC, patelaryan7751 commented
Deploy Preview Ready https://deploy-preview-2675--care-net.netlify.app/

2022-06-20 08:26 UTC, skks1212 requested changes
Rather than removing the button alltogether, can you change it to "Bed History" and make the modal only show the assigned beds table and not let them add any?

2022-06-20 08:43 UTC, patelaryan7751 commented
@skks1212 yeah right. Nice idea i am working on it.

2022-06-22 15:58 UTC, nihal467 commented
@patelaryan7751 is it good for testing, saw a comment mentioning you are working

2022-06-22 16:17 UTC, patelaryan7751 commented
@nihal467 i am working on it

2022-07-02 02:22 UTC, closed without merging