Resolved buttons placing in desktop and mobile view Issue#2739
coronasafe/care_fe pull request #2740
Opened 2022-06-17 11:06 UTC by Pranshu1902

Fixes #2739 

1. Resolved fixed buttons issue
https://www.loom.com/share/8e4e32c7774c4c8194c72f30a0adb45e

2. Resolved styling between buttons in mobile view
![Screenshot (391)](https://user-images.githubusercontent.com/70687348/174286560-2e5ac523-e204-4658-b121-0ebeb5dbc6d6.png)

2022-06-17 11:27 UTC, developedBySJ requested changes
@Pranshu1902 Can you make full-width buttons and add spacing above buttons?

2022-06-17 13:21 UTC, Pranshu1902 commented
Updated mobile view:
![Screenshot (392)](https://user-images.githubusercontent.com/70687348/174306503-9c035554-768a-46ef-90dd-869b12d133f6.png)

2022-06-17 13:29 UTC, developedBySJ approved these changes
LGTM

2022-06-17 13:29 UTC, developedBySJ commented on src/Components/Facility/ConsultationDetails.tsx
> +          <div className="right-0 top-0 flex sm:flex-row sm:items-center flex-col space-y-1 sm:space-y-0 sm:divide-x-2">
You can use [`gap`](https://tailwindcss.com/docs/gap) classes for spacing

2022-06-21 06:10 UTC, cp-Coder approved these changes

2022-06-22 22:08 UTC, nihal467 commented
test approved

2022-06-23 07:53 UTC, khavinshankar approved these changes

2022-06-23 07:54 UTC, khavinshankar commented
@Pranshu1902 please do work on the merge conflicts

2022-06-25 06:27 UTC, Pranshu1902 commented
@khavinshankar done!

2022-06-25 06:30 UTC, cp-Coder approved these changes

2022-07-03 10:58 UTC, nihal467 commented
@Pranshu1902 

![12](https://user-images.githubusercontent.com/57055998/177036478-b23261bd-0787-41ab-88b5-69db67c704e4.jpg)

the buttons are conjuested

2022-07-03 11:29 UTC, Pranshu1902 commented
@nihal467 bug resolved!
Desktop view:
![image](https://user-images.githubusercontent.com/70687348/177037465-a22933eb-b131-4dcf-9b84-cbeea441a2d8.png)

Mobile View:
![image](https://user-images.githubusercontent.com/70687348/177037479-eba6f6c8-54e4-4859-ae9a-e2dace5ee100.png)

2022-07-03 13:54 UTC, nihal467 commented
![14](https://user-images.githubusercontent.com/57055998/177042922-31ede28c-c5ec-458a-9cf4-7bfae31f0668.jpg)

@Pranshu1902 test failed

- [ ] the button is not in uniform size compared to others
- [ ] verified by is misaligned, it should be coming on the left side

2022-07-03 15:51 UTC, Pranshu1902 commented
@nihal467 
Updated view:
![image](https://user-images.githubusercontent.com/70687348/177047297-6b08deca-f7e0-4a90-bac4-36c6cd35114b.png)

2022-07-04 18:00 UTC, nihal467 commented
test approved

2022-07-06 09:24 UTC, khavinshankar approved these changes

2022-07-06 09:28 UTC, merged