Removed 'State Test ID' and 'Operation' fields from consultation form
coronasafe/care_fe pull request #2900
Opened 2022-06-25 14:17 UTC by GokulramGHV

Fixes #2760 
Removed the following fields from the consultation form
- [x]  state ID
- [x]  Operation

2022-06-25 14:31 UTC, cp-Coder approved these changes

2022-06-27 17:15 UTC, nihal467 commented
tset approved

2022-06-28 13:48 UTC, khavinshankar requested changes
please do remove the in instances in line `257` and  `264` and also double check if there is anymore instances that are left out

2022-06-30 04:41 UTC, GokulramGHV commented
@khavinshankar I've made the changes

2022-07-06 09:39 UTC, khavinshankar approved these changes

2022-07-06 12:22 UTC, merged