Removed service worker logs and replaced them with console errors
coronasafe/care_fe pull request #2949
Opened 2022-06-30 22:38 UTC by anuran-roy

Removed service worker logs and replaced them with console errors and replaced them with console errors and sentry reporting

2022-07-01 05:09 UTC, developedBySJ requested changes

2022-07-01 05:09 UTC, developedBySJ commented on src/Components/Notifications/NotificationsList.tsx
> +      // Error({
Clean up code

2022-07-01 05:09 UTC, developedBySJ commented on src/Components/Notifications/NotificationsList.tsx
> +        // Error({ msg: "Service Worker Error" });
Clean up code

2022-07-01 05:09 UTC, developedBySJ commented on src/Components/Notifications/NotificationsList.tsx
> +      console.log(`Service worker error...Details: ${error}`);
use `console.error`

2022-07-01 13:14 UTC, anuran-roy commented
@developedBySJ can you please review it?

2022-07-04 15:34 UTC, anuran-roy commented
@kunatastic can we remove the `need testing` label?

2022-07-05 17:18 UTC, kunatastic commented
@anuran-roy ig @nihal467 would be the right person

2022-07-06 08:11 UTC, nihal467 commented
looks good

2022-07-06 10:03 UTC, khavinshankar approved these changes

2022-07-06 12:18 UTC, merged