add: delete specialization doctor type
coronasafe/care_fe pull request #2953
Opened 2022-07-01 11:06 UTC by kunatastic

closes #2832 

https://user-images.githubusercontent.com/61267953/176882626-3ab938d1-bb79-4d41-bda2-f02dcbef2cc2.mp4

Added the delete button directly on facilty page because
1. The edit form was being re-used at several places
2. Now, both the edit and delete option are at same location

2022-07-02 03:05 UTC, rithviknishad requested changes
@kunatastic 

When I delete all items, it does not show "No Doctors Found".
![image](https://user-images.githubusercontent.com/25143503/176984431-cc76c48d-250d-4c83-94f2-d32933fae926.png)

However, when I refresh the page only it shows up.
![image](https://user-images.githubusercontent.com/25143503/176984451-3b529363-63bd-4937-af0e-eed2ed04a939.png)

2022-07-02 05:53 UTC, kunatastic commented
Cool @rithviknishad, on it

2022-07-02 07:52 UTC, cp-Coder approved these changes

2022-07-02 08:15 UTC, nihal467 commented
![8](https://user-images.githubusercontent.com/57055998/176992648-372a872d-7dae-4acd-8540-7a596bd179be.jpg)

@kunatastic now the UI look so lengthy, is there any alternative way to implement the delete button

2022-07-02 16:17 UTC, rithviknishad approved these changes

2022-07-04 05:03 UTC, kunatastic commented
Updated UI
![image](https://user-images.githubusercontent.com/61267953/177084459-18c11378-3daf-418d-b7e7-b9173b0ee371.png)

![image](https://user-images.githubusercontent.com/61267953/177084708-9acdcc3b-a7ea-417f-85d4-c6288e7fcba7.png)

@nihal467 is this better?

2022-07-06 17:22 UTC, nihal467 commented
test approved

2022-07-07 06:28 UTC, khavinshankar approved these changes

2022-07-13 09:45 UTC, khavinshankar requested changes

2022-07-13 09:45 UTC, khavinshankar commented on src/Components/Facility/models.tsx
> +  created_date?: string;
@kunatastic should this be outside the bracket

2022-07-13 09:45 UTC, khavinshankar commented on src/Components/Facility/models.tsx
>  export interface CapacityModal {
check this too (repetitions)

2022-07-13 09:46 UTC, khavinshankar approved these changes

2022-07-13 09:47 UTC, merged