Improved Ui of Choose File input and added validation in upload new file form in Consultation Files Page
coronasafe/care_fe pull request #3007
Opened 2022-07-05 02:35 UTC by patelaryan7751

Fixes #3005 

# Bugs Fixed

## Added validation in upload new file form
https://user-images.githubusercontent.com/59426397/177238111-84f6004e-db05-4cf6-98ac-4adf20915e9a.mp4

## Improved Ui of Choose File input
![image](https://user-images.githubusercontent.com/59426397/177238162-52b0e93e-a00b-4546-a184-0c5c81588ba3.png)

2022-07-05 17:12 UTC, kunatastic approved these changes

2022-07-05 19:23 UTC, cp-Coder approved these changes

2022-07-06 08:39 UTC, nihal467 commented
@patelaryan7751 make the choose file button rectangle itself rather than curve in the end, since everywhere we use rectangle buttons,

2022-07-08 11:12 UTC, patelaryan7751 commented
Hey, @nihal467 is this okay
![image](https://user-images.githubusercontent.com/59426397/177981566-e683e3e5-0790-46ee-be94-7ed16a9afe75.png)

2022-07-11 09:15 UTC, nihal467 commented
test approved

2022-07-21 05:01 UTC, khavinshankar commented
@patelaryan7751 making the filename mandatory can reduce the user experience, so can you make it similar to audio file, giving some template name? 

@nihal467 what do you think?

2022-07-21 05:47 UTC, patelaryan7751 commented
@khavinshankar @nihal467 i also think the same shall i implement it ?

2022-08-11 04:01 UTC, patelaryan7751 commented
@nihal467 @khavinshankar is there anything else to be done?

2022-08-16 05:29 UTC, khavinshankar requested changes

2022-08-16 05:29 UTC, khavinshankar commented on src/Components/Patient/FileUpload.tsx
> +      return false;
```suggestion
      setUploadFileNameError("Please choose a file to upload");
      return false;
```

2022-08-16 05:29 UTC, khavinshankar commented on src/Components/Patient/FileUpload.tsx
> +                      hover:file:bg-primary-300"
```suggestion
                      className="block w-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:border-0 file:text-sm file:font-semibold file:bg-primary-100 file:text-primary-700 hover:file:bg-primary-300"
```

2022-08-16 14:14 UTC, patelaryan7751 commented
@khavinshankar i have done the changes

2022-08-19 01:31 UTC, khavinshankar approved these changes

2022-08-19 01:31 UTC, merged