Added pointer cursor to inventory list item and changed name to inventory manager
coronasafe/care_fe pull request #3026
Opened 2022-07-07 06:19 UTC by skks1212

closes #3025

2022-07-07 06:36 UTC, cp-Coder approved these changes

2022-07-11 14:29 UTC, nihal467 commented
test approved

2022-07-12 05:46 UTC, khavinshankar requested changes

2022-07-12 05:46 UTC, khavinshankar commented on src/Components/Facility/InventoryList.tsx
> +        className={`cursor-pointer ${
refactor this code using clsx

2022-07-21 05:08 UTC, khavinshankar approved these changes

2022-07-21 05:08 UTC, khavinshankar commented on src/Components/Facility/InventoryList.tsx
> +        })}
```suggestion
        className={clsx("cursor-pointer hover:bg-gray-200", inventoryItem.is_low ? "bg-red-100" : "bg-white")}
```

2022-07-21 05:17 UTC, merged