remove profile button, shifted link to user at bottom
coronasafe/care_fe pull request #3031
Opened 2022-07-07 07:35 UTC by skks1212

closes #3030

2022-07-07 11:02 UTC, rithviknishad approved these changes

2022-07-07 12:20 UTC, cp-Coder approved these changes

2022-07-11 15:32 UTC, nihal467 commented
test approved

2022-07-12 06:18 UTC, khavinshankar requested changes

2022-07-12 06:18 UTC, khavinshankar commented on src/Components/Common/SideBar.tsx
> +  },*/
please do remove this

2022-07-21 05:13 UTC, khavinshankar approved these changes

2022-07-21 05:13 UTC, merged