Fixed notification issue in Facility Form
coronasafe/care_fe pull request #3098
Opened 2022-07-10 07:31 UTC by cp-Coder

# Updates

- [x] Fixes #3044
- [x] Fixed `notification` logic for `Facility Form`

2022-07-10 17:00 UTC, skks1212 approved these changes

2022-07-11 07:56 UTC, Ashesh3 requested changes
Minor change, otherwise LGTM

2022-07-11 07:56 UTC, Ashesh3 commented on src/Components/Facility/FacilityCreate.tsx
>        if (res && res.data) {
We can merge these two `if` statements.

```
if (res && res.data) {
    if (res.status === 200) {
```

```suggestion
      if (res && res.status === 200 && res.data) {
```

2022-07-11 20:53 UTC, nihal467 commented
![13](https://user-images.githubusercontent.com/57055998/178356271-731c44ba-c266-46ed-a78a-09e14ef474bf.jpg)


@cp-Coder make the notification more user friendly

2022-07-20 08:05 UTC, cp-Coder commented
@nihal467 This error is not present anymore.
If a user tries to assign `0: Choose Ward` as a ward, it will show `Field is required`. The form will not be saved.

2022-07-20 09:35 UTC, nihal467 commented
test approved

2022-07-21 05:16 UTC, khavinshankar approved these changes

2022-07-21 05:18 UTC, merged