Removed overlap on Facility Page in mobile view
coronasafe/care_fe pull request #3126
Opened 2022-07-14 09:04 UTC by Pranshu1902

Fixes #3124 
http://localhost:4000/facility/f8f05c04-5c97-415c-814d-419ecf692d0e

![image](https://user-images.githubusercontent.com/70687348/178945763-3ba84ea0-61d6-4adc-bfa6-ab6a5ef92327.png)

2022-07-14 10:03 UTC, developedBySJ requested changes

2022-07-14 10:03 UTC, developedBySJ commented on src/Components/Facility/FacilityHome.tsx
> +                    <div className="flex flex-col md:flex-row lg:flex-row gap-4">
`lg:flex-row` not needed

2022-07-14 11:22 UTC, Pranshu1902 commented on src/Components/Facility/FacilityHome.tsx
> +                    <div className="flex flex-col md:flex-row lg:flex-row gap-4">
Done

2022-07-14 13:30 UTC, kunatastic approved these changes

2022-07-14 18:36 UTC, cp-Coder approved these changes

2022-07-15 08:27 UTC, developedBySJ approved these changes
LGTM

2022-07-19 13:15 UTC, nihal467 commented
@Pranshu1902 
![image](https://user-images.githubusercontent.com/57055998/179759239-fff704b9-fc01-45e2-9984-756bd60abaa6.png)

make it responsive

2022-07-19 13:31 UTC, Pranshu1902 commented
@nihal467 
Updated view:
![image](https://user-images.githubusercontent.com/70687348/179762570-76d5ba22-9842-4f0a-8fbc-c8274f5d40f3.png)

2022-07-20 09:31 UTC, nihal467 commented
@Pranshu1902 
![image](https://user-images.githubusercontent.com/57055998/179949093-17af5bc0-bc09-4a6a-b7f1-df16886d37ad.png)

still issue

2022-07-20 10:46 UTC, Pranshu1902 commented
@nihal467 
Updated view:
![image](https://user-images.githubusercontent.com/70687348/179963879-68c2c15a-effb-484b-9963-5528b16da77c.png)

2022-07-25 18:23 UTC, nihal467 commented
test approved

2022-07-27 15:04 UTC, khavinshankar approved these changes

2022-07-27 15:04 UTC, merged