Prevent reload to same page in Pagination
coronasafe/care_fe pull request #3162
Opened 2022-07-18 09:51 UTC by Pranshu1902

Fixes #3161 
http://localhost:4000/facility

2022-07-19 09:49 UTC, developedBySJ requested changes
@Pranshu1902 
- Use the `button` tag instead of `div`
- Add `disable` prop to button (eg: disable "prev" button if a user is on the first page)

https://github.com/coronasafe/care_fe/blob/ff03007dbd5c6565afe829789a04d8221cde5dfc/src/Components/Common/Pagination.tsx#L131-L136

2022-07-19 09:49 UTC, developedBySJ commented on src/Components/Common/Pagination.tsx
> +    }
LGTM

2022-07-19 10:49 UTC, Pranshu1902 commented
> 

done

2022-07-19 20:11 UTC, nihal467 commented
test approved

2022-07-21 04:14 UTC, developedBySJ requested changes

2022-07-21 04:14 UTC, developedBySJ commented on src/Components/Common/Pagination.tsx
> +          {...(currentPage === 1 ? { disabled: true } : {})}
```suggestion
        disabled={currentPage === 1}
```

2022-07-21 04:14 UTC, developedBySJ commented on src/Components/Common/Pagination.tsx
> +          {...(currentPage === totalPage ? { disabled: true } : {})}
```suggestion
          disabled={currentPage === totalPage}
```

2022-07-28 08:03 UTC, Pranshu1902 commented
Fixed in #3204

2022-07-28 08:03 UTC, closed without merging