Made the consultation form responsive for Samsung Fold Device
coronasafe/care_fe pull request #3175
Opened 2022-07-21 07:27 UTC by patelaryan7751

Fixes #3148 

# Made the consultation form responsive for Samsung Fold Device
![consultation form](https://user-images.githubusercontent.com/59426397/180155002-b77a0d37-8fce-4f1e-bc54-58dfcf5b13a6.png)

2022-07-22 06:45 UTC, developedBySJ requested changes
Migrate to tailwind CSS buttons.

2022-07-22 12:48 UTC, patelaryan7751 commented
Hey, @developedBySJ I have migrated the buttons to tailwind.

2022-07-26 07:14 UTC, nihal467 commented
@developedBySJ after review,  provide the comment

2022-07-26 08:34 UTC, developedBySJ requested changes

2022-07-26 08:34 UTC, developedBySJ commented on src/Components/Facility/ConsultationForm.tsx
> +                  className="btn text-gray-900 bg-gray-200 border border-gray-300 focus:outline-none hover:bg-gray-400  font-medium  text-sm px-5 py-2.5 mt-2"
Use `btn-default` class for the secondary button
```suggestion
                  className="btn btn-default mt-2"
```

2022-07-29 10:41 UTC, patelaryan7751 commented
@developedBySJ I have done the changes.

2022-07-31 06:27 UTC, Ashesh3 approved these changes

2022-08-02 09:56 UTC, nihal467 commented
@patelaryan7751 can you merge the latest version of care

2022-08-02 12:44 UTC, patelaryan7751 commented
@nihal467 done.

2022-08-03 12:15 UTC, nihal467 commented
@patelaryan7751 
![image](https://user-images.githubusercontent.com/57055998/182605312-8394669d-74be-4820-b0d2-54af93482b1c.png)

make it responsive

2022-09-03 21:59 UTC, closed without merging

2022-11-09 08:00 UTC, Ritesh-Aggarwal commented
Hey @patelaryan7751, why was this PR closed , Is issue #3148 completed by some other PR?

2022-11-09 08:03 UTC, Ritesh-Aggarwal commented
Hey @patelaryan7751 , why was this PR closed, Is there any other PR fixing #3148 ?

2022-11-09 14:15 UTC, patelaryan7751 commented
Hey actually i tried to fix it the ui changed so i unassigned it
@Ritesh-Aggarwal

2022-11-09 14:15 UTC, patelaryan7751 commented
You can work on it it is not fixed yet