Fix check for required fields on Update Patient Details page
coronasafe/care_fe pull request #3200
Opened 2022-07-23 04:28 UTC by Ashesh3

Fixes #3181 

When a parent selection changes, the dependent option is reset to the "Unselected" choice. This PR also fixes the check for blank selection, by casting it to a number first as they are stored as string.

![image](https://user-images.githubusercontent.com/3626859/180590346-8302efaf-61fd-4a99-8f45-1d63a0081fca.png)

2022-07-25 07:23 UTC, developedBySJ requested changes
@Ashesh3 
If you change
```
state  => reset district, local_body, ward
district => reset local_body, ward
local_body => reset ward
```

Currently, only one field is updated

2022-07-25 07:27 UTC, Ashesh3 commented
> @Ashesh3 If you change
> 
> ```
> state  => reset district, local_body, ward
> district => reset local_body, ward
> local_body => reset ward
> ```
> 
> Currently, only one field is updated

Hey, the field updating is chained in the current logic.
state  => reset district (Which forces u to select a district, => resets local_body, which forces you to select a local body => resets ward)
district => reset local_body, (forces you to select a local_body => resets ward)
local_body => reset ward

I agree that updating all children fields at once would be neater, making the change now.

2022-07-25 22:20 UTC, nihal467 commented
@Ashesh3 @developedBySJ once completed, change the status to need testing

2022-07-26 06:26 UTC, Ashesh3 commented
The requested changes are made from my side and it works as expected. Need testing now.

2022-07-29 06:43 UTC, Ashesh3 commented
The requested changes are done, need a test now!

2022-08-02 09:58 UTC, nihal467 commented
@developedBySJ do the review and upon completed, update the label to need testing, currently making it to work-in-progress

2022-08-02 10:11 UTC, developedBySJ approved these changes
LGTM

2022-08-04 14:01 UTC, nihal467 commented
test approved

2022-08-10 13:41 UTC, khavinshankar approved these changes

2022-08-11 05:05 UTC, merged