fix: last-seen overflow
coronasafe/care_fe pull request #3205
Opened 2022-07-23 12:14 UTC by kunatastic

closes #3038

![image](https://user-images.githubusercontent.com/61267953/180604418-d94e3e7c-74e9-4baa-82af-af651418ad63.png)

2022-07-25 06:46 UTC, developedBySJ requested changes

2022-07-25 06:46 UTC, developedBySJ commented on src/Components/Users/ManageUsers.tsx
> +                    }
Use `clsx`
```suggestion
                    className={clsx(
                      "shrink-0 inline-block h-2 w-2 rounded-full" ,
                      moment().subtract(5, "minutes").isBefore(user.last_login)
                        ? "bg-primary-400"
                        : "bg-gray-300"
                        )
                    }
```

2022-07-25 18:08 UTC, nihal467 commented
@kunatastic @developedBySJ once its completed change the status to need testing

2022-07-26 07:03 UTC, kunatastic commented on src/Components/Users/ManageUsers.tsx
> +                    }
done

2022-07-26 07:15 UTC, nihal467 commented
test approved

2022-07-28 02:54 UTC, khavinshankar approved these changes

2022-08-08 19:20 UTC, cp-Coder approved these changes

2022-08-10 13:45 UTC, khavinshankar commented
@developedBySJ can you please rereview this?

2022-08-11 05:52 UTC, Ashesh3 approved these changes

2022-08-11 14:50 UTC, gigincg commented
@nihal467 This looks super weird in Desktop View. Why is this approved.

![image](https://user-images.githubusercontent.com/13028584/184162130-2b2f2cd3-5a54-49a6-bf56-4745fb58c728.png)

@kunatastic Use flex-wrap so that it goes over only when there isn't enough space

2022-10-15 16:49 UTC, closed without merging