Made all focus of input to green color in Critical Care Recorders
coronasafe/care_fe pull request #3206
Opened 2022-07-23 12:59 UTC by patelaryan7751

Fixes #3084 

## Made all focus of input to green color in Critical Care Recorders
https://user-images.githubusercontent.com/59426397/180605948-3df75f2b-4125-44b1-8b90-e7855f764fe1.mp4

2022-07-23 18:49 UTC, Ashesh3 approved these changes

2022-07-25 06:43 UTC, developedBySJ requested changes

2022-07-25 06:43 UTC, developedBySJ commented on src/Components/CriticalCareRecording/components/styles.css
> +  border:1px solid #0e9f6e;
Use `@apply ring-primary-500`

2022-07-25 18:21 UTC, nihal467 commented
@patelaryan7751 @developedBySJ once the work is completed, can the status to need to test

2022-10-03 08:41 UTC, nihal467 commented
test approved

2022-10-06 06:11 UTC, merged