Fix: Clear assigned doctor
coronasafe/care_fe pull request #3228
Opened 2022-07-26 04:58 UTC by GokulramGHV

Fixes #3227 

- [x]  Fixed: unable to clear the existing assigned doctor and keep it blank

2022-07-26 07:01 UTC, developedBySJ requested changes

2022-07-26 07:01 UTC, developedBySJ commented on src/Components/Facility/ConsultationForm.tsx
> +    if (doctor && doctor.id) {
Use optional chaining
```suggestion
    if (doctor?.id) {
```

2022-07-26 09:13 UTC, nihal467 commented
@GokulramGHV once work is completed, change the label

2022-07-26 10:12 UTC, GokulramGHV commented
@nihal467 The work is completed

2022-07-27 08:34 UTC, nihal467 commented
@GokulramGHV when we click clear, the droplist appears, can we avoid that!

2022-07-28 11:22 UTC, GokulramGHV commented
@nihal467 I've made the changes..

2022-08-02 07:07 UTC, nihal467 commented
![image](https://user-images.githubusercontent.com/57055998/182313355-4699ab98-c9a8-4833-a4fc-1468b65e4eb3.png)

@GokulramGHV make it responsive

2022-08-07 13:22 UTC, nihal467 commented
@GokulramGHV 
![image](https://user-images.githubusercontent.com/57055998/183292568-6b9fd7fa-87de-4835-9549-7aecbe886525.png)

the clear button is covered in responsive, any better place

2022-08-12 07:07 UTC, GokulramGHV commented
@nihal467 is this okay?
![Screenshot from 2022-08-12 12-24-19](https://user-images.githubusercontent.com/40627011/184302594-af07dfd9-3e51-4038-b818-0a961735a02b.png)

2022-08-12 07:27 UTC, nihal467 commented
@GokulramGHV can you put a cross button and try it out, rather than keeping a button saying clear?

2022-08-15 03:46 UTC, GokulramGHV commented
@nihal467 Is this ok?
![image](https://user-images.githubusercontent.com/40627011/184573761-8251e697-401e-4ea9-8d4a-19117e81cf29.png)

2022-08-17 13:00 UTC, nihal467 commented
test approved

2022-08-19 02:03 UTC, khavinshankar approved these changes

2022-08-19 02:03 UTC, khavinshankar commented
@developedBySJ can you please rereview this one?

2022-09-05 20:48 UTC, nihal467 commented
@GokulramGHV merge the latest development branch and check it passes the cypress test or not

2022-09-08 14:52 UTC, merged