Added prn prescription
coronasafe/care_fe pull request #3288
Opened 2022-08-01 10:29 UTC by skks1212

closes #3194 
![image](https://user-images.githubusercontent.com/23238460/182129313-a65bbda2-0194-47cc-9227-752aba95f39f.png)

2022-08-02 09:40 UTC, developedBySJ requested changes

2022-08-02 09:40 UTC, developedBySJ commented on src/Components/Common/prescription-builder/PRNPrescriptionBuilder.tsx
> +export default function PRNPrescriptionBuilder(props : {prescriptions :PRNPrescriptionType[], setPrescriptions : React.Dispatch<React.SetStateAction<PRNPrescriptionType[]>>}){
Extract `props` interface

2022-08-02 09:40 UTC, developedBySJ commented on src/Components/Common/prescription-builder/PRNPrescriptionBuilder.tsx
> +const dosageHrs = [1,2,3,6,12,24];
```suggestion
const DOSAGE_HRS= [1,2,3,6,12,24];
```

2022-08-09 14:55 UTC, nihal467 commented
@skks1212 

![image](https://user-images.githubusercontent.com/57055998/183678081-a901241d-a85f-4529-9784-dedb8f4acb2f.png)

- [ ] dosage more than 2 decimals are been accepted, but in issue, it says up to 2 decimals only

![image](https://user-images.githubusercontent.com/57055998/183680795-4d45a612-a11c-4ba7-a284-57c85d36ea99.png)

- [ ] when we are clicking on the increase and decrease button, the decimal inputted are been disappearing

2022-08-10 02:56 UTC, skks1212 commented
@nihal467 I have not added any restriction just in case anyone would like to use any more decimals. Regarding number 2, that is a browser specific functionality, so it will always round it up to nearest 1s.

2022-08-16 09:44 UTC, nihal467 commented
test approved

2022-08-19 01:55 UTC, khavinshankar approved these changes

2022-08-19 01:55 UTC, khavinshankar commented on src/Components/Facility/ConsultationForm.tsx
> +      console.log("recieved", res.data.prn_prescription);
```suggestion
```

2022-08-19 01:56 UTC, khavinshankar commented
@developedBySJ can you please rereview this one?

2022-08-27 16:11 UTC, nihal467 commented
test approved

2022-08-27 16:23 UTC, gigincg approved these changes

2022-08-27 16:23 UTC, merged