Fixed unresponsive bed delete dialog box
coronasafe/care_fe pull request #3294
Opened 2022-08-01 21:27 UTC by naman114

Fixes #3293 

- Fixed the unresponsive bed delete dialog box
- Improved the styling of the cancel button

![image](https://user-images.githubusercontent.com/57593654/182249431-8f532d7f-8b91-492a-ab5d-94812863b89e.png)

2022-08-02 08:59 UTC, developedBySJ requested changes

2022-08-02 08:59 UTC, developedBySJ commented on src/Components/Facility/BedDeleteDialog.tsx
> +        <button onClick={handleCancel} className="btn btn-primary">
Make `cancel` button as default button
```suggestion
        <button onClick={handleCancel} className="btn btn-default">
```

2022-08-02 21:31 UTC, patelaryan7751 approved these changes

2022-08-02 21:52 UTC, cp-Coder approved these changes

2022-08-07 06:30 UTC, developedBySJ approved these changes
LGTM

2022-08-07 18:20 UTC, nihal467 commented
test approved

2022-08-08 12:27 UTC, khavinshankar approved these changes

2022-08-11 04:59 UTC, merged