Fix patient category selection
coronasafe/care_fe pull request #3741
Opened 2022-10-10 11:22 UTC by Ashesh3

Fixes #3729 

- Fixes the category value to match with the backend, this resolves the error where the category value is an invalid choice.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2022-10-11 08:49 UTC, rithviknishad commented
@Ashesh3 two things:

- [ ] Consultation updates for "Slightly Abnormal" and "Comfort Care" not working.
- [ ] Daily rounds are broken. Page not even opening.

2022-10-11 08:53 UTC, rithviknishad requested changes
Changes made in `PATIENT_CATEGORIES` constants need to be updated on log updates page, and also fix the consultation update not working for "Comfort Care" and "Slightly Abnormal"

2022-10-11 14:02 UTC, Ashesh3 commented
> @Ashesh3 three things:
> 
> * [x]  Consultation updates for "Slightly Abnormal" and "Comfort Care" not working.
> * [x]  New log updates page not working.
> * [x]  Edit log updates not working.
> 
>  2022-10-11.14-16-28.mp4

Should be fixed now.

2022-10-11 16:07 UTC, rithviknishad approved these changes

2022-10-12 19:43 UTC, nihal467 commented
test approved

2022-10-13 06:02 UTC, khavinshankar approved these changes

2022-10-13 06:02 UTC, khavinshankar commented on src/Components/Facility/ConsultationForm.tsx
> +              ? PATIENT_CATEGORIES.find((i) => i.text === res.data.category)?.id
```suggestion
              ? PATIENT_CATEGORIES.find((i) => i.text === res.data.category)?.id || "Comfort"
```

2022-10-13 06:02 UTC, khavinshankar commented on src/Components/Patient/DailyRounds.tsx
> +                )?.id
```suggestion
                )?.id || "Comfort"
```

2022-10-13 06:02 UTC, khavinshankar commented on src/Components/Patient/DailyRounds.tsx
> +                )?.id
```suggestion
                )?.id || "Comfort"
```

2022-10-13 06:21 UTC, merged