feat: added health details and medical history fields to consultation form
coronasafe/care_fe pull request #3799
Opened 2022-10-22 05:03 UTC by cp-Coder

# Updates

- [x] Fixes #2738
- [x] Fixes #3332
- [x] Fixes #3333
- [x] Fixes #3335
- [x] Fixes #3336
- [x] Fixes #3338
- [x] Fixes #3361

2023-02-06 11:27 UTC, nihal467 commented
@cp-Coder marking it for team discussion required, for reevaluating the PR since the backend changes are not getting merged, and the issue seems to be changed a lot,

2023-02-07 18:29 UTC, nihal467 commented
@rithviknishad can you review it @cp-Coder can you work on the backend

2023-02-13 03:53 UTC, rithviknishad commented
@cp-Coder could you clear the merge conflicts too?

2023-03-08 08:23 UTC, rithviknishad commented
@cp-Coder could you clear the merge conflicts?

2023-03-08 10:08 UTC, rithviknishad requested changes
@cp-Coder @nihal467 few issues that are to be solved and few minor issues which could be taken up later.

### Issues
- [x] Nothing happens when clicking add patient in Patient Registration form. Unable to create a patient even with all fields in Personal Details section filled, COVID details were never opened. However, even after filling all COVID details fields, no errors seems to appear, nor it creates the patient. No console errors, no network activity.
![image](https://user-images.githubusercontent.com/25143503/223683546-f651850e-7421-4cdd-9626-7a36fe55f020.png)


### Other minor issues (optional, but could be taken up as seperate issues even)
- [ ] Part of the Patient Registration form is back to using old components. Hence errors are in black instead of red.
- [ ] **MISSING**: Create a label for allergies to appear in the patient list - _part of #3332_

2023-03-13 11:04 UTC, rithviknishad requested changes
(ignore, I forgot to pull latest backend, my bad)

~@cp-Coder unable to create a consultation now. Getting 500 internal server error in your backend branch.~

~cc: @nihal467~

![image](https://user-images.githubusercontent.com/25143503/224683768-f02bfa14-ade1-48a0-9dcf-5a4ac3684125.png)

2023-03-13 11:08 UTC, rithviknishad commented
We could take this up as a separate issue

![image](https://user-images.githubusercontent.com/25143503/224684708-b45958f6-0204-456e-a23f-eb744bf55e89.png)

2023-03-13 11:18 UTC, rithviknishad approved these changes
Looks okay :) @nihal467

2023-03-14 06:17 UTC, nihal467 commented
@cp-Coder the deploy is failed and there is a merge conflict, can you clear it ASAP

2023-03-14 06:17 UTC, rithviknishad commented on src/Components/Facility/ConsultationForm.tsx
>          case "verified_by": {
```suggestion
        case "verified_by":
```

2023-03-14 10:14 UTC, nihal467 commented
LGTM, @khavinshankar merge it ASAP, we are having a lot of minor bugs in the PR, which are not causing functionality issues but need to be fixed this week itself, so once this PR is merged, the following issues will be filed

2023-03-22 08:24 UTC, nihal467 commented
@cp-Coder 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/57055998/226842586-975cf219-8d25-435c-b24a-e7e005eb0030.png">

2023-04-07 18:13 UTC, cp-Coder commented
> - [ ] it should be appearing in chronological order, once we submit the data

@nihal467 Can you elaborate it more? What should be in the chronological order?

2023-04-13 06:02 UTC, khavinshankar commented
@nihal467 Is this pr relevant now?

@cp-Coder what's the status of this pr?

2023-04-14 05:55 UTC, cp-Coder commented
@khavinshankar The PR is good for testing. I will fix the the conflicts

2023-10-16 06:00 UTC, nihal467 commented
@cp-Coder due to large merge conflict and inactivity in the PR, closing this PR

2023-10-16 06:00 UTC, closed without merging