Fixed the vital waveform initial breaking
coronasafe/care_fe pull request #3834
Opened 2022-10-26 13:53 UTC by khavinshankar

## Proposed Changes

- Increased the length of default data so that the original data can be loaded in the mean time without breaking

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-10-26 16:21 UTC, nihal467 commented
test approve

2022-10-27 10:34 UTC, gigincg requested changes

2022-10-27 10:34 UTC, gigincg commented on src/Components/TeleIcu/Patient/Waveform.tsx
> +  const viewable = 400;
This should be a const VIEWABLE outside of the component. There's no reason for it to be inside the component

2022-10-27 14:21 UTC, gigincg approved these changes

2022-10-27 14:21 UTC, merged