Login page revamp
coronasafe/care_fe pull request #3853
Opened 2022-10-28 20:40 UTC by skks1212

after:
![image](https://user-images.githubusercontent.com/23238460/198728285-a93797f1-e2a4-4123-bc28-247c179968e8.png)

before:
![image](https://user-images.githubusercontent.com/23238460/198728315-7e240069-0985-431f-8611-39bc2652962e.png)

2022-11-01 08:58 UTC, nihal467 commented
@skks1212 @khavinshankar

- [ ]  i can seen a comment by github code scan  bot, can you guys look into it
- [ ] in tamil and malayalam, the text are overlapping in the login page 
![image](https://user-images.githubusercontent.com/57055998/199196243-0d92697b-9a81-43b1-9f37-f707e913c8b9.png)

2022-11-01 08:59 UTC, nihal467 commented
@skks1212 @khavinshankar marking it for team discussion required

- [ ] to discuss on the final approval of the design in the EOD call

2022-11-03 08:31 UTC, nihal467 commented
@skks1212 
![image](https://user-images.githubusercontent.com/57055998/199675380-e87b0bbc-7795-493e-a57c-389c411f9b64.png)


- [ ] in the forget password page, when i click on top of the "username" text in the box, the input field is not coming up.
- [ ] the send reset link button is not functioning

2022-11-03 15:01 UTC, rithviknishad commented on src/Components/Auth/Login.tsx
> +    return form;
```suggestion
    let hasError = false;
    const err = Object.assign({}, errors);
    const usernameInput = form["username"];
    if (typeof usernameInput === "string") {
      if (!usernameInput.match(/\w/)) {
        hasError = true;
        err["username"] = t("field_request");
      }
    }
    if (!usernameInput) {
      hasError = true;
      err["username"] = t("field_request");
    }
    if (hasError) {
      setErrors(err);
      return false;
    }
    return form;
```

2022-11-03 15:02 UTC, rithviknishad requested changes
@skks1212 could you fix the forget password validation logic?

2022-11-03 15:09 UTC, skks1212 commented
> @skks1212 could you fix the forget password validation logic?

Already fixed 😬

2022-11-03 15:38 UTC, nihal467 commented
test approved

2022-11-03 15:54 UTC, khavinshankar approved these changes

2022-11-03 15:54 UTC, merged