fix(asset): droplist is stretching the asset page
coronasafe/care_fe pull request #3882
Opened 2022-10-30 08:55 UTC by cp-Coder

# Updates

- [x] Fixes #3805
- [x] Fixed stretching of page during option select
- [x] Replaced `SelectMenu` with `SelectMenuV2`

2022-11-01 10:15 UTC, nihal467 commented
@cp-Coder 
![image](https://user-images.githubusercontent.com/57055998/199210699-d504ab60-d429-4bd2-8678-17091b9dcad7.png)

- [ ] once an option is selected in location, asset type & class, we can't unselect the droplist.

2022-11-05 01:58 UTC, rithviknishad commented on src/Components/Facility/AssetCreate.tsx
>                              },
Remove the default option and use the placeholder property to achieve the same instead.

2022-11-05 02:00 UTC, rithviknishad commented on src/Components/Facility/AssetCreate.tsx
> +                          required
Asset class is not a required field
```suggestion
```

2022-11-05 02:02 UTC, rithviknishad commented on src/Components/Facility/AssetCreate.tsx
> +                            { title: "Select", value: "NONE" },
SelectMenuV2 has a placeholder prop, use that to achieve this. Adding a default option in the list of options makes it an actual valid value in the perspective of the SelectMenuV2 component.

2022-11-05 02:04 UTC, rithviknishad requested changes
Use the SelectMenuV2 component's features instead of hacks to achieve it.

2022-11-08 07:23 UTC, rithviknishad approved these changes

2022-11-08 09:52 UTC, nihal467 commented
test approved

2022-11-09 10:29 UTC, khavinshankar approved these changes

2022-11-09 10:30 UTC, merged