Added Home Facility name beside doctors name while assigning doctor in Consutation Page
coronasafe/care_fe pull request #3897
Opened 2022-10-31 10:34 UTC by patelaryan7751

## Proposed Changes
Fixes #3862 

Added Home Facility name beside doctors name while assigning doctor in Consutation Page
![image](https://user-images.githubusercontent.com/59426397/198988485-0b00de94-58e6-4ee8-b9b2-3ab76930bd7e.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-11-01 09:31 UTC, nihal467 commented
test approved

2022-11-01 16:19 UTC, khavinshankar requested changes
just couple refactors

2022-11-01 16:19 UTC, khavinshankar commented on src/Components/Users/models.tsx
> +interface home_facilty_object {
```suggestion
interface HomeFacilityObjectModel {
```

2022-11-01 16:19 UTC, khavinshankar commented on src/Components/Users/models.tsx
> +  home_facility_object?: home_facilty_object;
```suggestion
  home_facility_object?: HomeFacilityObjectModel;
```

2022-11-06 09:12 UTC, rithviknishad approved these changes
@khavinshankar @nihal467 @patelaryan7751 how about showing the associated facility without "@" prefix but in `text-gray-700` instead of having "@ facility name"?

2022-11-09 10:46 UTC, khavinshankar commented
> @khavinshankar @nihal467 @patelaryan7751 how about showing the associated facility without "@" prefix but in `text-gray-700` instead of having "@ facility name"?

that's a nice idea

2022-11-09 10:47 UTC, khavinshankar commented on src/Components/Common/OnlineUsersSelect.tsx
> +                            }`}
```suggestion
                            {user.home_facility_object?.name && 
                                 <span className="text-gray-700 ml-2">{user.home_facility_object?.name}</span>
                            }
```

2022-11-09 10:47 UTC, khavinshankar approved these changes

2022-11-09 10:54 UTC, khavinshankar commented
@nihal467 can you retest this pr

2022-11-09 11:38 UTC, nihal467 commented
test approved

2022-11-09 15:43 UTC, merged