Now facility icons are visible in mobile devices
coronasafe/care_fe pull request #3901
Opened 2022-11-01 05:19 UTC by patelaryan7751

## Proposed Changes

Now facility icons are visible in mobile devices
![image](https://user-images.githubusercontent.com/59426397/199164331-5800ed77-ed80-408d-a666-2df2262f5b38.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-11-01 06:40 UTC, rithviknishad reviewed
How about using tailwind modifiers like `md:hidden md:visible` instead of useWindowDimensions hook?

2022-11-01 07:08 UTC, patelaryan7751 commented
@rithviknishad i tried it it didn't work so i just hidden the div when using the hook

2022-11-01 10:31 UTC, nihal467 commented
@rithviknishad @patelaryan7751 @rithviknishad i can see comments going on, once it is done and finalize for testing, change the label back to need testing

2022-11-01 10:32 UTC, rithviknishad commented
@nihal467 you can test.

2022-11-01 15:39 UTC, Ashesh3 requested changes

2022-11-01 15:39 UTC, Ashesh3 commented on src/Components/Facility/HospitalList.tsx
> +import useWindowDimensions from "../../Common/hooks/useWindowDimensions";
```suggestion
```
We do not need to use this, instead simple CSS should work.

2022-11-01 15:39 UTC, Ashesh3 commented on src/Components/Facility/HospitalList.tsx
> +  const isSmallScreen = width <= smallScreenBreakpoint ? true : false;
```suggestion
```

2022-11-01 15:39 UTC, Ashesh3 commented on src/Components/Facility/HospitalList.tsx
> +                {isSmallScreen ? (
```suggestion
                <div className="md:hidden">
```

We can use `md:hidden` here, to instruct CSS to hide this div for screen sizes >= 768px. Achieving the same result.

2022-11-01 15:39 UTC, Ashesh3 commented on src/Components/Facility/HospitalList.tsx
> +                )}
```suggestion
                </div>
```

2022-11-01 15:39 UTC, Ashesh3 commented on src/Components/Facility/HospitalList.tsx
> +                )}
The final result:

![image](https://user-images.githubusercontent.com/3626859/199274403-87c75a0c-128c-4b67-96b8-58975e655ee1.png)

2022-11-01 15:43 UTC, Ashesh3 commented
> How about using tailwind modifiers like `md:hidden md:visible` instead of useWindowDimensions hook?

I think this should be the proper approach, I tried to use the above modifiers and was able to achieve the same results.

2022-11-02 06:55 UTC, nihal467 commented
@patelaryan7751 @Ashesh3 i can see the comments going on, once its finalise, mark it for need testing

2022-11-03 09:11 UTC, patelaryan7751 commented
Hey @Ashesh3 i have done the above said changes.

2022-11-03 09:13 UTC, Ashesh3 approved these changes

2022-11-03 09:28 UTC, rithviknishad approved these changes

2022-11-03 11:22 UTC, nihal467 commented
LGTM

2022-11-03 14:44 UTC, khavinshankar approved these changes

2022-11-03 14:44 UTC, merged