Added create more button in the asset creation form
coronasafe/care_fe pull request #3918
Opened 2022-11-01 17:34 UTC by Pranshu1902

Fixes #3881 

Added a create and add more assets button
https://www.loom.com/share/048a45f065d64b75886794ffbb0120de

2022-11-02 06:09 UTC, nihal467 commented
@Pranshu1902 
![image](https://user-images.githubusercontent.com/57055998/199411075-0eaab499-417d-46ae-af42-3f7f7f09b166.png)

- [ ] when i use the add more asset button for adding second asset, the both date field in the warranty and service are showing invalid date format

2022-11-02 07:13 UTC, Pranshu1902 commented
@nihal467 
Bug resolved
![image](https://user-images.githubusercontent.com/70687348/199423737-d7053907-b19b-4611-bbd2-8f696dce2dca.png)

2022-11-02 09:10 UTC, nihal467 commented
@Pranshu1902 @khavinshankar LGTM, A small enhancement issue for this PR has been filed on 3929,

2022-11-02 14:38 UTC, khavinshankar requested changes
minor refactor

2022-11-02 14:38 UTC, khavinshankar commented on src/Components/Facility/AssetCreate.tsx
> +            setLastServicedOn(null);
can this be moved into a function, something like `resetFilters`

2022-11-02 15:41 UTC, Pranshu1902 commented on src/Components/Facility/AssetCreate.tsx
> +            setLastServicedOn(null);
@khavinshankar Done

2022-11-03 05:13 UTC, khavinshankar approved these changes

2022-11-03 05:13 UTC, merged