Added a modal to notify user if a existing triage exist
coronasafe/care_fe pull request #4008
Opened 2022-11-09 06:32 UTC by patelaryan7751

## Proposed Changes
Fixes #3950
Added a modal to notify user if a existing triage exist
![image](https://user-images.githubusercontent.com/59426397/200754787-a7551423-92b8-4451-ae2b-b49802fbdd53.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-11-09 08:18 UTC, nihal467 commented
@patelaryan7751 the functionality looks good ! but, the text contact seem bulky, shall we discuss it on EOD, to see other opinions too !

2022-11-09 14:32 UTC, nihal467 commented
- "a triage already exist in the date" can be on first row and move the remaining content to the next line and use smaller font size for that
- use the tailwind button
- use the danger or warning exist for the proceed button
- use secondary for the cancel button

2022-12-05 09:44 UTC, patelaryan7751 commented
Hey @nihal467 all the modal Ui changes are done.
![image](https://user-images.githubusercontent.com/59426397/205605202-64fdba94-853a-4477-8951-46135bb41624.png)

2022-12-06 09:43 UTC, nihal467 commented
LGTM

2022-12-06 11:12 UTC, khavinshankar requested changes
@patelaryan7751 some minor changes

2022-12-06 11:12 UTC, khavinshankar commented on src/Components/Common/components/ButtonV2.tsx
> +      id={`${id || ""}`}
why aren't you just doing
```suggestion
      id={id}
```

2022-12-06 11:12 UTC, khavinshankar commented on src/Components/Facility/TriageForm.tsx
> +
```suggestion
```

extra lines seems unnecessary

2022-12-06 11:12 UTC, khavinshankar commented on src/Components/Facility/TriageForm.tsx
> +
```suggestion
```
extra lines seems unnecessary

2022-12-06 11:12 UTC, khavinshankar commented on src/Components/Facility/TriageForm.tsx
> +
```suggestion
import ButtonV2 from "../Common/components/ButtonV2";
```

2022-12-24 06:16 UTC, nihal467 commented
@patelaryan7751 can you work on it and push it after fixing all the problems before new year

2022-12-27 04:20 UTC, nihal467 commented
LGTM

2022-12-28 05:00 UTC, khavinshankar approved these changes

2022-12-28 05:00 UTC, merged