Generalize handling of filters and pagination with `usePaginatedQueryParam` hook
coronasafe/care_fe pull request #4041
Opened 2022-11-12 07:00 UTC by rithviknishad

#### This PR is stacked on top of #3965 

## Proposed Changes

- [x] Implements `usePaginatedQueryParam` hook.
- [ ] Generalizes handling of filters and pagination hook for:
  - [x] Facilties
  - [ ] Patients
  - [ ] Assets
  - [ ] Sample test
  - [ ] Shifting
  - [ ] Resource
  - [ ] External results
  - [ ] Users
- [x] Fixes #4015
- [x] Inherently closes #3955 via base PR #3965

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-11-16 09:02 UTC, nihal467 commented
@rithviknishad 
![image](https://user-images.githubusercontent.com/57055998/202133078-b839e3bb-a168-45ad-933e-45a4aba55af9.png)

- [x] KASP embelled filters are not working

![image](https://user-images.githubusercontent.com/57055998/202134222-f8c9c4ca-8aaf-47a1-abda-d5d7a91cbb64.png)

- [x] responsive view of the patient tab, after applying filters breaking a lot, when compared to current staging.

![image](https://user-images.githubusercontent.com/57055998/202135702-8b825393-488f-4072-9b9b-7269aaa7cd1d.png)

- [x] in normal view also, the UI in the patient tab is breaking

![image](https://user-images.githubusercontent.com/57055998/202138679-0c764086-df9f-4a47-b56e-e92e6ca8d5a3.png)

- [x] unable to close the district filter using badge

2022-11-18 06:13 UTC, rithviknishad commented
![image](https://user-images.githubusercontent.com/25143503/202633639-031ff76e-0dd3-4fae-b9aa-465b38790fe7.png)

2022-11-23 12:57 UTC, nihal467 commented
LGTM, @khavinshankar review it carefully while merging

2022-11-24 05:23 UTC, khavinshankar requested changes
@rithviknishad 
There are a few minor changes, and

It would be better if the filters remain when we change views like LIstView to BoardView and vice versa in Resources and Shifting

2022-11-24 05:23 UTC, khavinshankar commented on src/Components/Resource/BadgesList.tsx
> +        value("Origin facility", "origin_facility", orginFacilityName),
```suggestion
        value("Origin facility", "orgin_facility", orginFacilityName),
```

2022-11-24 05:23 UTC, khavinshankar commented on src/Components/Shifting/BadgesList.tsx
> +  const [originFacilityName, setOirginFacilityName] = useState("");
```suggestion
  const [originFacilityName, setOriginFacilityName] = useState("");
```

2022-11-24 05:23 UTC, khavinshankar commented on src/Components/Shifting/BadgesList.tsx
> +      setOirginFacilityName(res?.data?.name);
```suggestion
      setOriginFacilityName(res?.data?.name);
```

2022-11-24 05:23 UTC, khavinshankar commented on src/Components/Shifting/BadgesList.tsx
> +        value("Origin facility", "origin_facility", originFacilityName),
```suggestion
        value("Origin facility", "orgin_facility", originFacilityName),
```

2022-11-24 05:23 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +          <ListFilter {...advancedFilter} dataList={lsgWardData} />
```suggestion
          <ListFilter {...advancedFilter} dataList={lsgWardData} />
```

remove local in ListFilter also

2022-11-24 05:30 UTC, khavinshankar commented on src/Components/ExternalResult/ResultList.tsx
> +          <ListFilter {...advancedFilter} dataList={lsgWardData} />
removed local filters in ListFilter

2022-11-24 05:41 UTC, khavinshankar approved these changes

2022-11-24 05:42 UTC, merged