fix(FacilitySelect): Minor UI fix in patient popup
coronasafe/care_fe pull request #4064
Opened 2022-11-16 13:36 UTC by cp-Coder

# Bug Fix

## Proposed Changes

- Added Tailwind Dialog Modal
- Fixed `Add patient` popup size
- Fixed alignment of buttons in `Add patient` popup

## Associated Issue

- Fixes #3886

## Screenshot

- FacilitySelect Popup

![image](https://user-images.githubusercontent.com/77210185/202194488-e4779bdd-fbfa-4e6e-b399-a31f7d0bfbf6.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product[documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [x] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-11-17 03:53 UTC, rithviknishad commented on src/Components/Common/ConfirmDialogV2.tsx
> +        </ButtonV2>
Why would cancel operation be danger variant?
```suggestion
        <ButtonV2 onClick={onClose} variant="secondary">
          {cancelText || "Cancel"}
        </ButtonV2>
```

2022-11-17 03:55 UTC, rithviknishad commented on src/Components/ExternalResult/FacilitiesSelectDialogue.tsx
>      >
In the issue, the confirm dialog was meant for operations that needs explicit approval. Like delete, archive, etc. And not meant to be used for simple operations like selecting a facility.

2022-11-17 03:57 UTC, rithviknishad requested changes
- [x] Change such that, ConfirmDialog is for operations like delete, archive, etc...
- [ ] Use normal DialogV2 for things like Facility Selects.

2022-11-28 10:13 UTC, rithviknishad approved these changes

2022-11-30 10:44 UTC, nihal467 commented
LGTM

2022-11-30 11:25 UTC, khavinshankar approved these changes

2022-11-30 11:26 UTC, merged