Refactor doctor capacity page to use Tailwind
coronasafe/care_fe pull request #4314
Opened 2022-12-15 14:00 UTC by Ashesh3

Fixes #4023

![image](https://user-images.githubusercontent.com/3626859/207876617-f7ee3788-d06a-46cf-b8d0-8285d831d9d1.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2022-12-16 08:43 UTC, nihal467 commented
@Ashesh3 
![image](https://user-images.githubusercontent.com/57055998/208058967-9dd825cb-6a48-4ea3-bf1f-27c4699daee6.png)

make the three button in three rows when it is in responsive view

2022-12-16 16:16 UTC, Ashesh3 commented
> @Ashesh3 ![image](https://user-images.githubusercontent.com/57055998/208058967-9dd825cb-6a48-4ea3-bf1f-27c4699daee6.png)
> 
> make the three button in three rows when it is in responsive view

Done!
![image](https://user-images.githubusercontent.com/3626859/208141983-63bb30d6-ffb5-46ac-bbe2-9fe70387ff55.png)

2022-12-19 11:43 UTC, nihal467 commented
LGTM

2022-12-20 04:26 UTC, khavinshankar requested changes

2022-12-20 04:26 UTC, khavinshankar commented on src/Components/Facility/DoctorCapacityForm.tsx
>                      onClick={() => goBack(!id && `/facility/${facilityId}`)}
As these buttons are inside a form tag, clicking on them would submit the form by default, so use event.preventDefault() or type="button"

```suggestion
                    onClick={(e) => {
                        e.preventDefault()
                        goBack(!id && `/facility/${facilityId}`);
                    }}
```

2022-12-20 06:22 UTC, Ashesh3 commented
@khavinshankar Fixed now!

2022-12-20 07:24 UTC, nihal467 commented
test approved

2022-12-21 05:04 UTC, khavinshankar approved these changes

2022-12-21 05:07 UTC, merged