fix: upgrade the facility creation component to tailwind components
coronasafe/care_fe pull request #4315
Opened 2022-12-15 15:00 UTC by cp-Coder

# Feature Request

## Proposed Changes

- Replaced MUI components with Tailwind components for the `Facility Create/Update` page

## Associated Issue

- Fixes https://github.com/coronasafe/care_fe/issues/4200

## Screenshot

![image](https://user-images.githubusercontent.com/77210185/207893169-e907fa54-45a0-4152-96b1-63e52166d8fe.png)
![image](https://user-images.githubusercontent.com/77210185/207893258-5c31803b-697b-4c31-b590-7596fdd8d5ba.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product[documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-12-15 17:36 UTC, rithviknishad commented on src/Components/Facility/FacilityCreate.tsx
> +import TextInputFieldV2 from "../Common/components/TextInputFieldV2";
@cp-Coder use `TextFormField` instead and mark `TextInputFieldV2` as deprecated. From here on `TextFormField` will be maintained.

2022-12-15 17:37 UTC, rithviknishad commented on src/Components/Facility/FacilityCreate.tsx
> +import TextInputFieldV2 from "../Common/components/TextInputFieldV2";
Ref: https://github.com/coronasafe/care_fe/pull/4309

2022-12-15 17:46 UTC, rithviknishad requested changes
@cp-Coder I see that you've overridden the font size of all the `FieldLabel`s used. The FieldLabel uses the font size per the Figma design, avoid overriding it so that we have a consistent design across the platform.

2022-12-15 18:41 UTC, rithviknishad approved these changes
LGTM

2022-12-16 10:43 UTC, nihal467 commented
LGTM

2022-12-16 12:57 UTC, khavinshankar approved these changes

2022-12-16 13:03 UTC, khavinshankar commented
@nihal467 @cp-Coder there is a minor problem, once the state is selected we can't select 'choose state' again, and the same with the district, local body, and ward too. I am anyways merging this pr because those are mandatory fields.

2022-12-16 13:03 UTC, merged