Fix (Sidebar): made the sidebar collapse on clicking active links
coronasafe/care_fe pull request #4377
Opened 2022-12-20 18:04 UTC by naman114

## Proposed Changes

- Fixes #4372
- Made the mobile sidebar collapse on clicking the active/current tab

https://user-images.githubusercontent.com/57593654/208735156-5f1aa605-68b3-41c1-b049-525348f7685b.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-12-22 10:37 UTC, nihal467 commented
LGTM

2022-12-22 12:28 UTC, khavinshankar requested changes

2022-12-22 12:28 UTC, khavinshankar commented on src/Components/Common/Sidebar/Sidebar.tsx
> +  }, [activeLink, lastIndicatorPosition]);
updating `lastIndicatorPosition` and having it in deps array might cause infinite loop

2022-12-24 21:57 UTC, naman114 commented
@khavinshankar I have removed the dependency from the useEffect hook

2022-12-26 13:40 UTC, khavinshankar commented
@nihal467 can you retest this pr again, changes have been made

2022-12-27 04:27 UTC, nihal467 commented
LGTM

2022-12-28 06:08 UTC, khavinshankar approved these changes

2022-12-28 06:08 UTC, merged