Hide active tab indicator when `activeLink` is `undefined`
coronasafe/care_fe pull request #4549
Opened 2023-01-10 06:05 UTC by rithviknishad

## Proposed Changes

- Fixes #4548

The issue was caused because styles set via `indicatorRef` were being overridden by tailwind classes.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

2023-01-11 05:50 UTC, skks1212 requested changes
Hey, can you comment the current implementation and write the new one below it? Just so the old implementation is preserved.

2023-01-11 09:33 UTC, nihal467 commented
LGTM

2023-01-11 12:01 UTC, khavinshankar approved these changes

2023-01-11 12:01 UTC, khavinshankar commented
@skks1212 can you rereview this one

2023-01-11 13:06 UTC, skks1212 approved these changes
LGTM!

2023-01-12 06:23 UTC, khavinshankar approved these changes

2023-01-12 06:23 UTC, merged