fix: Tailwind delete user confirm dialog to use ConfirmDialog component
coronasafe/care_fe pull request #4583
Opened 2023-01-14 08:50 UTC by cp-Coder

# Bug Fix

## Proposed Changes

- Tailwind the user unlink facility dialog

## Associated Issue

- Fixes #4446

## Screenshot

![image](https://user-images.githubusercontent.com/77210185/212464163-a8dd3eb2-ef1c-4685-a9b5-878f1dd3ba00.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-01-14 09:17 UTC, rithviknishad requested changes

2023-01-14 09:17 UTC, rithviknishad commented on src/Components/Users/UnlinkFacilityDialog.tsx
> +      action="Delete"
```suggestion
      action="Unlink"
```

2023-01-17 06:04 UTC, nihal467 commented
@cp-Coder 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/57055998/212821929-c7e1f72f-95b7-4c5b-bc8e-8650859e3a48.png">

it is not working properly in 14 inch laptop

2023-01-17 06:06 UTC, nihal467 commented
LGTM

2023-01-17 09:26 UTC, khavinshankar approved these changes

2023-01-17 09:27 UTC, khavinshankar commented
@rithviknishad can you rereview this one

2023-01-17 09:33 UTC, rithviknishad approved these changes

2023-01-17 09:35 UTC, merged