Fixed facility cover photo
coronasafe/care_fe pull request #4765
Opened 2023-02-05 15:26 UTC by GokulramGHV

## Proposed Changes

- Fixes #4755 
- Removed gray padding in the facility cover images

### Screenshot
![image](https://user-images.githubusercontent.com/40627011/216828389-7830de18-f3e8-47a7-8196-0b26f8c521e2.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-02-05 19:04 UTC, Pranshu1902 commented
@GokulramGHV The care height is irregular for different facilities now
![image](https://user-images.githubusercontent.com/70687348/216839461-60be48ad-ca0e-4288-aa44-db10e2bbb764.png)

2023-02-07 12:50 UTC, Pranshu1902 approved these changes

2023-02-07 13:30 UTC, nihal467 commented
@GokulramGHV 
![image](https://user-images.githubusercontent.com/57055998/217257790-46c2f677-51d5-4d31-9bce-bdcdc2cc530d.png)

the existing staging card size looks good, rather than the size in the deploy preview, can we keep it that way?

2023-02-08 14:19 UTC, rithviknishad requested changes
@GokulramGHV try these changes, it seems to have solved it

2023-02-08 14:19 UTC, rithviknishad commented on src/Components/Facility/FacilityCard.tsx
> +      <div className="block rounded-lg h-64 overflow-clip bg-white shadow hover:border-primary-500">
```suggestion
      <div className="block rounded-lg h-full overflow-clip bg-white shadow hover:border-primary-500">
```

2023-02-08 14:19 UTC, rithviknishad commented on src/Components/Facility/FacilityCard.tsx
> +                className="object-cover w-full h-full"
```suggestion
                className="object-cover h-full"
```

2023-02-08 15:19 UTC, nihal467 commented
@GokulramGHV once you make the changes, mark it for testing

2023-02-09 12:13 UTC, GokulramGHV commented on src/Components/Facility/FacilityCard.tsx
> +      <div className="block rounded-lg h-64 overflow-clip bg-white shadow hover:border-primary-500">
@rithviknishad making this change makes the facility cards' heights not uniform

2023-02-11 14:11 UTC, GokulramGHV commented on src/Components/Facility/FacilityCard.tsx
> +                className="object-cover w-full h-full"
@khavinshankar

2023-02-24 15:14 UTC, GokulramGHV commented
@nihal467 as this pr was discussed with gigin, he apporved the changes and asked me to mark it for testing

2023-02-27 05:51 UTC, nihal467 commented
LGTM

2023-02-27 08:27 UTC, khavinshankar commented
@rithviknishad  can you rereview this

2023-02-27 08:29 UTC, rithviknishad approved these changes

2023-02-27 09:50 UTC, khavinshankar approved these changes

2023-02-27 09:50 UTC, merged