Add hover effect to Cancel button in Advanced Filters
coronasafe/care_fe pull request #4782
Opened 2023-02-07 10:14 UTC by Ashesh3

Fixes #4747 

![KookyKentrosaurus](https://user-images.githubusercontent.com/3626859/217216626-94e1aa69-508a-4a41-b990-727186bc261c.gif)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2023-02-07 11:12 UTC, rithviknishad commented on src/style/CAREUI.css
> +.button-secondary-default { @apply accent-secondary-300 bg-secondary-300 hover:bg-secondary-200 text-secondary-800 !important }
@Ashesh3 this was intentionally kept white. How about reverting the changes for the default type, but preserving your changes for the ghost type alone?

```suggestion
.button-secondary-default { @apply accent-secondary-300 bg-secondary-300 hover:bg-secondary-200 text-secondary-800 !important }
```

2023-02-07 11:12 UTC, rithviknishad requested changes
Preserve white bg for default variant

2023-02-09 08:32 UTC, Ashesh3 commented
> Preserve white bg for default variant

Done!

![GenerousFantail](https://user-images.githubusercontent.com/3626859/217758533-87aca033-a925-4ac1-a8b5-d24bcf89a542.gif)

2023-02-09 08:46 UTC, rithviknishad approved these changes

2023-02-13 05:54 UTC, nihal467 commented
LGTM

2023-02-13 06:10 UTC, khavinshankar approved these changes

2023-02-14 05:45 UTC, merged