Change error statement colour from black to red in patient creation form
coronasafe/care_fe pull request #4882
Opened 2023-02-25 06:03 UTC by siva-balan

## Proposed Changes

- Fixes #4867 
- Changes:
![image](https://user-images.githubusercontent.com/88849832/221341363-c995e1ab-11ca-4000-86e3-e3341d77b989.png)
![image](https://user-images.githubusercontent.com/88849832/221341379-436dd364-f8b9-481f-911f-696293fed58b.png)

- Changed text field to text form field and added red color to errors in the select field.
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-02-25 06:07 UTC, closed without merging

2023-02-25 06:09 UTC, rithviknishad requested changes

2023-02-25 06:09 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +              <span className="text-red-500">Please select ward</span>
@siva-balan wouldn't the FormField component apply the colors automatically?

You can make use of `SelectFormField` for gender select.

```suggestion
              <span className="text-red-500">Please select ward</span>
```

```suggestion
              Please select ward
```

2023-03-02 12:18 UTC, siva-balan commented
@rithviknishad I am unable to use SelectFormField for the States and districts. I am getting some errors, can you help with that... I am able to use that for gender but not for others.

2023-03-02 12:26 UTC, rithviknishad commented
Hey @siva-balan 👋🏼 sure, happy to help you out.

Have a look at [`src/Components/Users/UserAdd.tsx`](https://github.com/coronasafe/care_fe/blob/develop/src/Components/Users/UserAdd.tsx#L887-L921) where similar State and District select menus were implemented using `SelectFormField`.

Let me know if you are still facing issues after looking at this.

![image](https://user-images.githubusercontent.com/25143503/222427990-b0f20dac-2d83-4ed1-af7a-b4ce037795c0.png)

2023-03-02 12:30 UTC, siva-balan commented
@rithviknishad I already had a look at that, and I tried to implement it similarly but I am not able to click the states in the drop-down. Could you take a look at this?
![0d62c76b-532c-4814-9e17-70aeecaf40bb](https://user-images.githubusercontent.com/88849832/222429223-2479c895-da3e-4e42-9289-696f963868be.jpg)
![e385ad7e-9c8d-4626-98ea-777363133cfb](https://user-images.githubusercontent.com/88849832/222429235-b8744e17-815a-4137-a49b-52de73dfbb62.jpg)

Tell me if there's anything I need to change.. Thanks for the help.

2023-03-02 12:43 UTC, rithviknishad commented
@siva-balan I'm guessing that you are using `handleChange` which is for old components and wouldn't work with `FormField` components. For `FormField` components you shall use `handleFormFieldChange`.

2023-03-02 12:44 UTC, rithviknishad commented
@siva-balan once there are no more legacy input fields that's using `handleChange`, you may remove that old `handleChange` altogether.

2023-03-02 14:18 UTC, siva-balan commented
@rithviknishad Thanks for the fix, I was able to implement them, but the drop-down options are not fully visible due to using the select form field. They are being hidden by the below component. Any idea on how to solve that?
![image](https://user-images.githubusercontent.com/88849832/222453786-b89060f9-2395-44af-a3c2-edd263f8eef5.png)

2023-03-02 14:19 UTC, rithviknishad commented
@siva-balan this is probably because the parent container has `overflow-clip` class.

2023-03-02 16:10 UTC, rithviknishad commented
@siva-balan the Material UI's `Card` component can be replaced with a `div` if `Card` is causing the clipping.

You may remove these if so:

![image](https://user-images.githubusercontent.com/25143503/222484858-5d4fd20c-1e16-49c0-a590-264da59a4c3d.png)