Fix using Body Details clone
coronasafe/care_fe pull request #5034
Opened 2023-03-03 09:01 UTC by jeromtom

## Proposed Changes

- Fixes #4871
- Add a card in the Patient Dashboard below "General Instructions" to show additional details about each of the procedures suggested keeping the design consistent with the "Body Details" card.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-03 09:24 UTC, jeromtom commented
Cypress Tests are failing as usual. Let me know if any other change is required.

2023-03-03 09:34 UTC, rithviknishad requested changes
@jeromtom 

1. repetitive is not being shown
2. table contents are clipped, not scrollable even.

![image](https://user-images.githubusercontent.com/25143503/222684482-b859a64f-b997-47f5-8a8e-c5fd67b351fd.png)


![image](https://user-images.githubusercontent.com/25143503/222684415-0ec36fa3-13f4-4ec0-8984-0a313deee627.png)


Patient Consultation: https://deploy-preview-5034--care-net.netlify.app/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/36cdd810-c3e1-45dd-993c-2877a46e35de/consultation/48f289bb-8ae2-46d8-b6b1-4840fa6f2385

2023-03-05 14:08 UTC, jeromtom commented
@rithviknishad , understood will work on it. Do we have to show the "Repetitive" field? How about showing either "Time" or "Frequency" depending on if repetitive field was selected.

2023-03-06 06:33 UTC, rithviknishad commented
@jeromtom I agree with that.

cc: @aparnacoronasafe

2023-03-21 03:51 UTC, rithviknishad requested changes

2023-03-21 03:51 UTC, rithviknishad commented on src/Components/Common/components/ResponsiveProcedureTables.tsx
@jeromtom I'm still not able to do a horizontal scroll, nor contents visible.

How about using `col-span-2 scroll-x-auto`?

![image](https://user-images.githubusercontent.com/25143503/226513304-199b734d-a2c3-4d9b-b86b-7222a3134e98.png)

2023-03-21 03:51 UTC, rithviknishad commented on src/Components/Common/components/ResponsiveProcedureTables.tsx
> +      {windowSize.innerWidth > 1024 ? (
I don't see a reason to have this much complication. Wouldn't tailwind's modifiers be enough?

```suggestion
  useEffect(() => {
    function handleWindowResize() {
      setWindowSize(getWindowSize());
    }

    window.addEventListener("resize", handleWindowResize);

    return () => {
      window.removeEventListener("resize", handleWindowResize);
    };
  }, []);
  return (
    <>
      {windowSize.innerWidth > 1024 ? (
```

2023-04-05 04:14 UTC, closed without merging