remove MUI circularProgress & grid
coronasafe/care_fe pull request #5047
Opened 2023-03-06 17:22 UTC by ayushjnv1

## Proposed Changes

- Fixes #issue?
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-06 17:24 UTC, gigincg commented
@ayushjnv1 Thank you for the PR

Could you please, merge the upstream to resolve the conflicts & update the PR description and link to the Issues you are solving

2023-03-06 17:44 UTC, ayushjnv1 commented
https://github.com/coronasafe/care_fe/issues/4930

2023-03-07 03:55 UTC, rithviknishad approved these changes

2023-03-07 07:30 UTC, nihal467 commented
@ayushjnv1 

![image](https://user-images.githubusercontent.com/57055998/223353266-4ae0e159-6977-468a-8167-5cd6bc7f2535.png)

- [ ] the forgot password text should be left aligned similar to the existing staging
- [ ] the login button should be of the same length as the text box, similar to the existing staging
- [ ] by default, English is selected, so it should be much more highlighted from others and have an underline to make the user understand, the language English is selected, similar to the existing staging.

2023-03-07 07:40 UTC, rithviknishad requested changes
1. The grid classes are unnecessary.
2. Make button `w-full`

2023-03-07 07:40 UTC, rithviknishad commented on src/Components/Auth/Login.tsx
> +                <div className="grid justify-center">
```suggestion
                <div className="justify-start">
```

2023-03-07 07:40 UTC, rithviknishad commented on src/Components/Auth/Login.tsx
> +                <div className="grid justify-center ">
```suggestion
                <div className="justify-start">
```

2023-03-08 04:19 UTC, rithviknishad approved these changes
@ayushjnv1 LGTM.

@nihal467 the language selector issue is a different issue not related to this.

What happens is, if the user has never selected a language in care, it'll be blank and English is not highlighted. Because only when a user selects a language, the preference is stored in the local storage.
In your staging, English is highlighted because you've selected English at some point in time. 

This issue is easily noticeable in all deploy previews.

In my fresh staging (see image) I've never selected a language, so it's not highlighted. Will create an issue for this.

![image](https://user-images.githubusercontent.com/25143503/223618446-c454ec16-aaa1-423e-81e2-6e4af19e3d88.png)

2023-03-08 08:18 UTC, nihal467 commented
LGTM

2023-03-08 10:30 UTC, khavinshankar approved these changes

2023-03-08 10:30 UTC, merged