Added red border on select input fields and removed MUI
coronasafe/care_fe pull request #5089
Opened 2023-03-10 16:22 UTC by Pranshu1902

Fixes #5055 
Added Red border for errors and removed MUI

2023-03-10 16:24 UTC, Pranshu1902 commented
waiting for #5054

2023-03-10 16:25 UTC, rithviknishad reviewed
Prefer using `SelectFormField` over `SelectMenuV2`

2023-03-11 11:36 UTC, rithviknishad requested changes

2023-03-11 11:36 UTC, rithviknishad commented on src/Components/Form/FormFields/SelectFormField.tsx
> +        requiredError={props.requiredError}
```suggestion
        requiredError={!!field.error}
```

2023-03-11 11:36 UTC, rithviknishad commented on src/Components/Form/FormFields/SelectFormField.tsx
> +  requiredError?: boolean;
```suggestion
```

2023-03-11 11:38 UTC, rithviknishad commented
Why would you want to pass a requiredError separately when you can derive whether it's a required field and it has an error or not?

2023-03-11 12:18 UTC, Pranshu1902 commented
> Why would you want to pass a requiredError separately when you can derive whether it's a required field and it has an error or not?

@rithviknishad removed `requiredError`

2023-03-11 13:56 UTC, rithviknishad approved these changes

2023-03-13 08:43 UTC, nihal467 commented
@Pranshu1902 
![image](https://user-images.githubusercontent.com/57055998/224649716-08f4bb4f-ce09-49b1-9f81-03878774e84c.png)

- [ ] the ward is not a mandatory field
- [ ] the date is currently shown in yyyy-mm-dd , and not in dd-mm-yyyy format which is mentioned in the error message

2023-03-13 12:11 UTC, Pranshu1902 commented
@nihal467 Bug resolved
![image](https://user-images.githubusercontent.com/70687348/224697674-4b392fbb-91a0-4137-ad18-54e5cad93ee6.png)

2023-03-13 16:35 UTC, nihal467 commented
LGTM

2023-03-14 04:44 UTC, khavinshankar approved these changes

2023-03-14 04:44 UTC, khavinshankar commented on src/Components/Users/UserAdd.tsx
> +            state.form[field].length == 0 ||
```suggestion
            state.form[field].length === 0 ||
```

2023-03-14 05:06 UTC, merged