Vertically center aligned State logo in Login page by modifying tailw…
coronasafe/care_fe pull request #5125
Opened 2023-03-17 21:43 UTC by rjhaveri1991

## Proposed Changes

- Fixes #5123?
- Modifed tailwind css classes in Auth Component at 2 places as mentioned below
```diff
**Change 1**
- <div className="hidden md:flex gap-6 mb-4">
+ <div className="gap-6 mb-4 min-w-full max-w-lg">
```
```diff
**Change 2**
- <a href={coronasafe_url} className="inline-block" target="_blank" rel="noopener noreferrer">
+ <a href={coronasafe_url} className="flex flex-col items-center" target="_blank" rel="noopener noreferrer">
```
- Issue Fix Screenshot
![Issue #5123 - Fix](https://user-images.githubusercontent.com/127334545/226058373-3e127937-319b-4840-9927-774c78d7f284.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate bug / test a new feature.
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA

2023-03-18 05:16 UTC, rithviknishad requested changes
@rjhaveri1991 you've adjusted the horizontal center alignment.


![image](https://user-images.githubusercontent.com/25143503/226086222-8c13d598-1fcd-4238-9adc-9b68755e9a34.png)

Could you revert the changes and adjust the vertical alignment of the state logo instead and not the CARE logo?

To enable `state_logo` in preview, add the following to `public/config.json` file:

```json
{
  "state_logo": "https://digitalpublicgoods.net/wp-content/themes/dpga/images/logo-w.svg",
}
```

once tested, we can remove it. the `state_logo` is an opt-in feature across deployments.

2023-03-18 05:39 UTC, rjhaveri1991 commented
@rithviknishad - Got it, so state logo should be vertically center aligned in line with care logo right?

2023-03-18 05:42 UTC, rithviknishad commented
@rjhaveri1991 yes! affirmative.

2023-03-18 19:12 UTC, rjhaveri1991 commented
## Proposed Changes

- Fixes #5123?
- Reverted changes done in previous commit and vertically center aligned state logo with below changes
```diff
**Change**
- <div className="hidden md:flex gap-6 mb-4">
+ <div className="hidden md:flex items-center gap-6 mb-4">
```
- Issue Fix Screenshot
![Issue #5123 - Fix](https://user-images.githubusercontent.com/127334545/226131320-760569ac-b036-485e-8765-7906fcee1e33.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate bug / test a new feature.
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA

2023-03-18 19:45 UTC, skks1212 approved these changes
LGTM!

2023-03-19 03:26 UTC, rithviknishad approved these changes

2023-03-20 06:25 UTC, nihal467 commented
LGTM @khavinshankar review it and merge it

2023-03-20 06:33 UTC, khavinshankar approved these changes

2023-03-20 13:28 UTC, merged