Add loading spinner beside add button
coronasafe/care_fe pull request #5129
Opened 2023-03-18 17:10 UTC by AdrianaMoralesQ

## Proposed Changes
Hi, @coronasafe/code-reviewers !
- Fixes issue https://github.com/coronasafe/care_fe/issues/5119
- Implemented loading spinner next to add button in add user skills panel
- Refactored SkillsSlideOver component to make it easier to read
- Fixed eslint warnings 

<img width="1080" alt="LoadingSpinner" src="https://user-images.githubusercontent.com/109168765/226122030-2fb010df-e446-4701-9eed-fe9c3bd27d35.png">

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.

- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-21 03:28 UTC, ayushjnv1 commented on src/Components/Users/SkillsSlideOver.tsx
> +                    isLoading={isLoading}
CircularProgress we can add instead of null

2023-03-21 03:34 UTC, ayushjnv1 commented on src/Components/Users/SkillsSlideOver.Components.tsx
> +const SELECT_SKILLS_COPY = "Select and add some skills";
Why we decleare constant Is this use again & again.

2023-03-21 03:40 UTC, rithviknishad requested changes
@AdrianaMoralesQ 

- [ ] We don't follow `.Components.tsx` file naming formats.
- [ ] For the warning literal strings not allowed, you may make use of translations `const { t } = useTranslations();` and wrap the text like `<Component label={t("add_skill")} />`. Also make sure the key `add_skill` is present in the en locale files such as `en/Common.json` or any other relevant context-specific locales.
- [ ] Would be nice if the loading spinner was inside the button to the left of the "Add" text.

2023-03-21 15:38 UTC, AdrianaMoralesQ commented
Working on this!

2023-03-22 18:53 UTC, AdrianaMoralesQ commented
@rithviknishad and @ayushjnv1 : I've made the changes as requested. 
<img width="898" alt="Screenshot 2023-03-22 at 2 51 05 PM" src="https://user-images.githubusercontent.com/109168765/227007700-c34aebbe-6429-4538-8439-e4ef450639d3.png">
- [ ] Renamed file since we don't follow .Components.tsx file naming formats.
- [ ] Added const { t } = useTranslations(); and wrapped as mentioned.  I added three relevant strings to the en locale files in en/Common.json.
- [ ] Added <CircularProgress/> inside the "Add" button. It replaces the "Add" instead of appearing beside it because IMO it looks better - otherwise the button grows and shrinks when the spinner appears/disappears. 
- [ ] CircularProgress was added instead of null

2023-03-23 03:14 UTC, rithviknishad requested changes
- [ ] The button size changes between loading and not loading states.

Other than that LGTM. 

Just feedback, Kindly make sure to avoid too many irrelevant changes. 90% of the changes present in this PR are not relevant to adding loading the spinner for add button. It would roughly take only 3~6 lines of change to achieve, but we have around 100+ lines of change here.

2023-03-23 15:52 UTC, AdrianaMoralesQ commented
Hi,
 
Feedback noted - I got carried away trying to get rid of the ESLINT error, but I understand that it wasn't in scope. 

I've made the change to the spinner and it's no longer changing in size.

2023-03-23 18:55 UTC, skks1212 approved these changes
LGTM!

2023-03-25 06:25 UTC, rithviknishad approved these changes
LGTM

2023-03-27 09:13 UTC, nihal467 commented
LGTM

2023-03-27 10:06 UTC, khavinshankar approved these changes

2023-03-27 10:06 UTC, merged