replace MUI CircularProgress
coronasafe/care_fe pull request #5136
Opened 2023-03-20 19:27 UTC by ayushjnv1

## Proposed Changes

- Fixes #issue?
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-20 19:28 UTC, ayushjnv1 commented
fix issue #4999

2023-03-21 03:19 UTC, rithviknishad approved these changes

2023-03-21 03:30 UTC, rithviknishad requested changes

2023-03-21 03:30 UTC, rithviknishad commented on src/Components/Shifting/ShiftDetailsUpdate.tsx
@ayushjnv1 this file contains `PageTitle` that can be changed to `Page` wrapper component.

2023-03-21 03:47 UTC, ayushjnv1 commented on src/Components/Shifting/ShiftDetailsUpdate.tsx
ok I will do that.

2023-03-26 08:12 UTC, rithviknishad approved these changes

2023-03-26 08:12 UTC, rithviknishad commented on src/Components/Shifting/ShiftDetailsUpdate.tsx
> +      className="px-2 pb-2"
Avoid using custom padding when using `Page` component unless necessary. Newer components allows us to have consistent designs across the platform out of the box.
```suggestion
```

2023-03-27 09:31 UTC, rithviknishad requested changes
@ayushjnv1 we have a slight problem. All the below marked fields are coming from `HelperInputFields` which indirectly uses `MaterialUI` components.

Could you use the new FormField components for all fields in this page?

![image](https://user-images.githubusercontent.com/25143503/227901850-97b507c7-c265-406b-9ef6-be4d1c05723f.png)

cc: @nihal467

2023-03-27 10:11 UTC, ayushjnv1 commented
ok I will do that

2023-03-27 10:12 UTC, rithviknishad commented
@ayushjnv1 if you could merge the latest develop branch now, you'll be able to see all the old components have been renamed to `Legacy<ComponentName>` so that it's easier to track which needs to be migrated.

Ref: 2c063da4d1f50b008500064f967523c84621cc42

2023-06-22 16:22 UTC, rithviknishad commented
Closing as completed via #5415

2023-06-22 16:22 UTC, closed without merging