vite migration
coronasafe/care_fe pull request #5140
Opened 2023-03-22 03:49 UTC by sainak

## Proposed Changes

- migrate build tools to vite 

## TODO

- [ ] verify that all components work as expected
- [ ] fix service worker (checkout vite-pwa)
- [ ] ...

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-22 03:53 UTC, sainak commented
@rithviknishad the components contaning the phone number field break while previewing a production build, I'm not able to pin point the actual issue but here's the error that I got 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: [missing argument].[missing argument]
```

![image](https://user-images.githubusercontent.com/46787056/226797774-98d91a15-d127-4ebb-b63c-3021f1c7c23e.png)


please check this issue

2023-03-22 06:40 UTC, sainak commented
@rithviknishad the issue is fixed now.
We will have to be careful with what external libraries we use.

2023-03-23 10:02 UTC, gigincg commented
@sainak Can you update the `netlify.toml` and the `Dockerfile` so that @mathew-alex Can test this out in those environments?

cc: @rithviknishad

2023-03-23 10:16 UTC, sainak commented
@gigincg changes to deployment config won't be needed as internally npm run build is calling vite
You can see the latest deploy preview, the components are working fine now but the css file is quite large as compared to cra builds, service worker might be broken, and I'm working on fixing the storybook

2023-03-24 04:11 UTC, skks1212 commented
Just to quantify the impact of this PR, starting the current *CRA app takes 1 minute and 36 seconds* on my laptop with 16 gb ram and an i5-11400H @ 2.70GHz  2.69 GHz CP.
The *Vite app takes just 40 seconds to start* which makes the app start *215%* faster than before. App hot reload also take considerably less time than before. This allows CARE to be developed in less powerful computers. Great feat @sainak

2023-03-24 09:56 UTC, sainak commented
@rithviknishad please update the ci for storybook the build commnad is `build:storybook` and the dist folder is `build-storybook`
also can you verify if the service worker is working correctly?

2023-03-25 06:53 UTC, Ashesh3 commented
With this my build time goes down from `210s` to `57s` and hot reload time goes down to `6s` from `28s`. This is really helpful. Great work! 
Tested on 3.0 GHz Ampere® Altra™ x4 core CPU with 32GB memory.

2023-03-25 08:20 UTC, sainak commented on .storybook/main.ts
> -const config: StorybookConfig = {
lets keep the StorybookConfig type as it'll help us for type hints

2023-03-25 08:20 UTC, sainak commented on .storybook/main.ts
> -        viteConfigPath: "./.storybook/vite.config.ts",
I would recommend using the vite builder as we are using it for our project
and vite builder requires its own config that i created under .storybook/vite.config.ts

2023-03-25 08:20 UTC, sainak commented on .storybook/main.ts
> -  staticDirs: ["../public"],
this is required

2023-03-25 08:20 UTC, sainak commented on package.json
> +    "preview:storybook": "vite preview --outDir storybook build"
this is a conflict with the project build path

2023-03-25 08:20 UTC, sainak commented on package.json
> -    "@storybook/builder-vite": "^7.0.0-rc.6",
this is needed

2023-03-28 07:01 UTC, sainak commented
@gigincg @mathew-alex  the PR is ready to be merged in develop with one breaking change that is the env variable `PUBLIC_URL` needs to be renamed to `REACT_PUBLIC_URL`

2023-03-29 14:48 UTC, skks1212 approved these changes
LGTM!

2023-04-03 05:28 UTC, khavinshankar commented
@sainak can you fix the merge conflicts

2023-04-03 07:01 UTC, khavinshankar requested changes

2023-04-03 07:01 UTC, khavinshankar commented on src/service-worker.ts
> -});
@sainak is this handled anywhere else? I don't see this reimplemented

2023-04-03 07:57 UTC, sainak commented on src/service-worker.ts
> -});
yes, it is handled by vite-pwa

2023-04-03 15:16 UTC, khavinshankar approved these changes

2023-04-04 17:40 UTC, gigincg approved these changes

2023-04-04 17:41 UTC, merged