Added validation for 0 count in Add Bed Capacity
coronasafe/care_fe pull request #5202
Opened 2023-03-30 09:41 UTC by Pranshu1902

Fixes #5201 
Added validation for 0 count in Add Bed capacity
http://localhost:4000/facility/fc09dbc9-015a-4194-8dc8-14ccee34eee9
![image](https://user-images.githubusercontent.com/70687348/228796208-ce2fe409-73ef-41ae-8f25-f2acb7d6664d.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-03-30 13:43 UTC, rithviknishad approved these changes

2023-03-30 13:44 UTC, rithviknishad requested changes
@Pranshu1902 can you also set the `min` prop of the field to 1 instead of 0?

2023-04-03 08:55 UTC, nihal467 commented
LGTM

2023-04-05 03:55 UTC, khavinshankar commented
@rithviknishad can you rereview this pr

2023-04-05 04:29 UTC, rithviknishad approved these changes

2023-04-06 04:11 UTC, khavinshankar approved these changes

2023-04-06 04:11 UTC, merged