Update experience commenced labels to "Years of experience".
coronasafe/care_fe pull request #5207
Opened 2023-03-30 16:22 UTC by Ashesh3

Fixes #5205

Rename label "Experience Commenced On" to "Years of experience" in UserAdd and UserProfile components. This change provides a more clear and concise label that describes the input field. The suffix for the field has also been updated to reflect the new label. This change improves the user experience by making the input field more intuitive and easier to understand.

![image](https://user-images.githubusercontent.com/3626859/228901253-c862dfce-8085-400c-8035-db46ea5ce18c.png)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2023-03-30 16:38 UTC, rithviknishad approved these changes
I thought since the label has changed to `Years of Exp.` we had to change the field also to a number input and calculate experience_commenced_on based on input before firing the request

2023-03-30 16:39 UTC, Ashesh3 commented
> I thought since the label has changed to `Years of Exp.` we had to change the field also to a number input and calculate experience_commenced_on based on input before firing the request

I thought the same, @nihal467 could you take a look if we need to convert the field to a number input?

2023-03-30 19:22 UTC, nihal467 commented
@Ashesh3 we need to convert the field, where it will be a simple input field, for example, we input how many years of experience the doctor has in the area like 1 year

2023-03-30 19:56 UTC, Ashesh3 commented
> @Ashesh3 @rithviknishad we need to convert the field, which will be a simple input field just to input the number of experience in years

Done!

![image](https://user-images.githubusercontent.com/3626859/228949911-6b611017-d2a9-409f-83be-d110f625ff33.png)

![image](https://user-images.githubusercontent.com/3626859/228949928-19d277e6-4d22-4b92-8dbe-ae02f3f4b450.png)

2023-03-31 02:32 UTC, rithviknishad approved these changes

2023-03-31 02:32 UTC, rithviknishad commented on src/Components/Users/UserAdd.tsx
>                      required
👀 
![image](https://user-images.githubusercontent.com/25143503/229008104-f86bca1d-2cc4-43b3-a1e1-c50e930c7262.png)

```suggestion
                    required
                    min={0}
```

2023-03-31 03:54 UTC, Ashesh3 commented on src/Components/Users/UserAdd.tsx
>                      required
😬

2023-04-03 09:47 UTC, rithviknishad requested changes
@Ashesh3 could you also change the field to numeric input in the profile update page?

(reported by @nihal467)

2023-04-03 16:34 UTC, Ashesh3 commented
> @Ashesh3 could you also change the field to numeric input in the profile update page?
> 
> (reported by @nihal467)

Done!

![image](https://user-images.githubusercontent.com/3626859/229572092-f26f930c-7588-44cb-9395-41d95ac8ef7f.png)

2023-04-03 16:37 UTC, rithviknishad approved these changes

2023-04-04 06:40 UTC, nihal467 commented
LGTM

2023-04-05 03:54 UTC, khavinshankar approved these changes

2023-04-05 03:54 UTC, merged