Closed Replace Material UI components in src/Components/Notifications/NoticeBoard.tsx
coronasafe/care_fe pull request #5552
Opened 2023-05-28 08:29 UTC by nikhilagastya

Created custom components by removing Material UI 
- Fixed #4973 
- Migrated all Material UI components to use new Care UI / custom components
- Migrated all Material UI icons to use care icons.
- Migrated  PageTitle to Page

2023-05-28 08:33 UTC, nikhilagastya commented
@rithviknishad  can you please check the PR

2023-05-28 09:07 UTC, rithviknishad requested changes
Why are changes from https://github.com/coronasafe/care_fe/pull/5544 present here? 

Ensure your changes from other branches are not present.

2023-05-28 09:07 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
>      </div>
1. Page component shouldn't be wrapped with a parent padding. The goal is to have consistent layout and padding across the platform by using the new generic Page component.
2. Page component should wrap all the contents. Why is the notices not wrapped?

2023-05-28 09:29 UTC, nikhilagastya commented
> Why are changes from #5544 present here?
> 
> Ensure your changes from other branches are not present.

yeahh ill change that

2023-05-28 09:49 UTC, nikhilagastya commented
@rithviknishad can you check if this is okay !

2023-05-28 09:50 UTC, rithviknishad commented
The changes from other branch are still present. Feel free to create a new branch and re-open another PR. This can mess up when the other PR and this PR merges.

2023-05-28 09:52 UTC, rithviknishad commented
Or you could make these changes in the other PR itself since that already removes some of the mui componennts, and link 2 issues to that PR if you are facing difficulty.

2023-05-28 11:46 UTC, nikhilagastya commented
Hey @rithviknishad ig now the changes  from other branches are not present. If you still find them can you just tell me what they are so that i can fix it

2023-05-28 11:53 UTC, rithviknishad requested changes
1. You've moved the line of import of MUI components. This might go undetected without a merge conflict when both your PRs are merged. Feel free to push changes directly to your other PR and link both issues there. This is much easier.

2. Why are there diffs in other files? Kindly configure your git to use proper line endings (LF).

![image](https://github.com/coronasafe/care_fe/assets/25143503/e5101a15-3966-4a48-b97f-fc443bf0de0d)

2023-05-28 11:58 UTC, nikhilagastya commented
> 1. You've moved the line of import of MUI components. This might go undetected without a merge conflict when both your PRs are merged. Feel free to push changes directly to your other PR and link both issues there. This is much easier.
> 2. Why are there diffs in other files? Kindly configure your git to use proper line endings (LF).
> 
> ![image](https://user-images.githubusercontent.com/25143503/241557826-e5101a15-3966-4a48-b97f-fc443bf0de0d.png)

can you tell me how do I merge two two issues ?

2023-05-28 12:02 UTC, rithviknishad commented
```bash
git checkout <old-branch-name>
git merge <this-branch>
git push
```

Also, make sure the files have been changed correctly and that there is no more material ui usage on the entire file. After that, you should update your main comment on that PR to link issues related to this PR too.

2023-05-28 12:32 UTC, nikhilagastya commented
> ```shell
> git checkout <other-pr-branch-name> # "develop"
> git merge <this-pr-branch-name> # "NoticeBoard"
> git push
> ```
> 
> Also, make sure the files have been changed correctly and that there is no more material ui usage on the entire file. After that, you should update your main comment on that PR to link issues related to this PR too.

Can I add a comment in the Illustrations issue ,that this issue is a duplicate of the current issue to link them ?

2023-05-28 12:56 UTC, rithviknishad approved these changes
Nice work @nikhilagastya

2023-05-28 12:58 UTC, nikhilagastya commented
> Nice work @nikhilagastya

Thanks @rithviknishad !!

2023-05-29 11:47 UTC, nihal467 commented
@nikhilagastya 
![image](https://github.com/coronasafe/care_fe/assets/57055998/21c886bc-5c87-48b4-9714-30d3c228d499)

- [ ] remove the shadow in the cards
- [ ] increase the width of the card similar to the existing staging in the normal view

2023-05-29 11:51 UTC, rithviknishad approved these changes

2023-05-29 11:51 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +            className="max-w-sm rounded overflow-hidden shadow-lg "
```suggestion
            className="rounded overflow-hidden shadow-md"
```

2023-05-29 12:06 UTC, rithviknishad requested changes
Use Care Icon's `bell-slash` icon instead of illustration.

changes requested by @nihal467

2023-05-29 12:06 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +          </p>
```suggestion
```

2023-05-29 12:06 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +          </p>
Remove this

2023-05-29 12:06 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +            You Dont Have Any Notices
Centre align this text

2023-05-29 12:06 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +        <img
Vertically center align the whole component wrt to the page

2023-05-29 12:08 UTC, rithviknishad requested changes

2023-05-29 12:08 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +        </div>
We don't need this either.

changes requested by @nihal467

2023-05-29 12:10 UTC, rithviknishad commented on src/Components/Notifications/NoticeBoard.tsx
> +        </div>
We don't need this either. changes requested by @nihal467 
```suggestion
```

2023-05-29 12:12 UTC, rithviknishad requested changes

2023-05-29 12:12 UTC, rithviknishad commented on public/images/Notificationbell.png
Delete this too

cc: @nihal467

2023-05-29 12:21 UTC, nihal467 commented
@nikhilagastya 
![image](https://github.com/coronasafe/care_fe/assets/57055998/18f627b9-ff3a-4c61-a75b-cb52fdc7f449)

- This is a new design mock-up. Please try to adhere to this design and ensure that the content and text are center-aligned. Additionally, use the color grey-500.

2023-05-29 13:58 UTC, nikhilagastya commented
sure @nihal467 ill work on it

2023-05-29 14:33 UTC, nikhilagastya commented
@nihal467 @rithviknishad  do we already have bell-slash in care icons ?

2023-05-29 14:34 UTC, rithviknishad commented
@nikhilagastya all unicons are present in care icons. you just need to prefix `care-l-<icon_name>`. Refer the #5006 to know more about care icons

2023-05-29 15:48 UTC, nikhilagastya commented
@rithviknishad kindly check if that works !

2023-05-29 16:15 UTC, rithviknishad approved these changes
Awesome!

2023-05-30 06:20 UTC, nihal467 commented
LGTM

2023-05-30 11:18 UTC, khavinshankar approved these changes

2023-05-30 11:18 UTC, merged