Removed MUI Components from AddLocationCard
coronasafe/care_fe pull request #5558
Opened 2023-05-29 07:35 UTC by divyanshkhetan

### WHAT
Removed the Card and Card Content tags from the `AddLocation.tsx` file.

## Proposed Changes

- Fixes #4944 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

Screenshots:
| Before | After |
| - | - |
| ![Add Location Card Before](https://github.com/coronasafe/care_fe/assets/68158825/786a797f-b153-4bc4-b7c4-be586e28d0ed) | ![Add Location Card After](https://github.com/coronasafe/care_fe/assets/68158825/d6a5992c-1d7f-435e-b8fe-3f5ba5be0ff8) |

2023-05-29 10:22 UTC, rithviknishad requested changes
Nice work, however you have not converted PageTitle to Page component yet.

Also ensure there are no paddings before the page component. this is to keep layout consistent.

2023-05-29 12:36 UTC, divyanshkhetan commented
@rithviknishad PTAL and let me know if any changes are needed.

2023-05-29 14:37 UTC, rithviknishad approved these changes

2023-05-30 06:43 UTC, nihal467 commented
LGTM

2023-05-30 11:19 UTC, khavinshankar approved these changes

2023-05-30 11:19 UTC, merged