Replace Material UI components in src/Components/Shifting/ListFilter.tsx. Fixes  #4996
coronasafe/care_fe pull request #5572
Opened 2023-05-31 10:07 UTC by JahnabDutta

### WHAT
Replacing of the Material UI CircularProgress  present in src/Components/Shifting/ListFilter.tsx with the Care common component CircularProgress.
## Proposed Changes

- Fixes #4996 
- Change MUI CircularProgress Icon to Care common component CircularProgress.
- Video comparison(Top is Care common component and bottom is MUI component)
[comparison.webm](https://github.com/coronasafe/care_fe/assets/76475829/d03e0d46-f5be-4da8-8391-0f58a5a78cb0)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### HOW
- Remove MUI CircularProgress component
- Import CircularProgress from src/Commom/Components/CircularProgress and replace it where MUI component was used.
- Change size of CircularProgress to be similar to the MUI component.

2023-05-31 10:09 UTC, rithviknishad requested changes
You've not changed `LegacySelectField` to `SelectFormField`

2023-05-31 11:01 UTC, JahnabDutta commented
Hey, could you let me know where do I have to go to on my localserver website to view the changes being made in the form.

2023-05-31 12:14 UTC, rithviknishad commented
Open the filters in the shifting page.

2023-05-31 13:04 UTC, JahnabDutta commented
I have tried changing the `LegacySelectField` to `SelectFormField`. Could you please review again?

2023-05-31 13:31 UTC, rithviknishad approved these changes

2023-06-02 05:15 UTC, khavinshankar commented
@JahnabDutta can you also fix the cypress tests
![image](https://github.com/coronasafe/care_fe/assets/29787772/3f3d07e3-d7ed-44fe-82ac-a04415a179ef)

check this action for the failing tests
https://github.com/coronasafe/care_fe/actions/runs/5142676229/jobs/9263088413?pr=5572

2023-06-02 11:17 UTC, JahnabDutta commented
I tried to modify some functions to match the code in development but it appears that there is some kind of problem with the original code too because of which the filters are not working properly. There are some things which are not clear to me? Some fields have the value "--". Is this a type of valid option or is it just supposed to mean "Show all". The way this has been configured is not clear to me.

2023-06-02 11:47 UTC, rithviknishad commented
Consider refactoring '--' to be considered as "Filter Not Applied"

2023-06-02 11:50 UTC, rithviknishad commented
Consider refactoring '--' away.
'--' as of now means 'Filter not applied'

You may make the filters behaviour / value consistent with other filters like Patient Filters / Asset Filter / Facility Filter.

2023-06-02 13:15 UTC, JahnabDutta commented
hey, @rithviknishad @khavinshankar I think I have fixed the errors on my end. However cypress tests are failing because they have been written for the older components and hence cannot locate the new components. Should I commit my code?

2023-06-02 13:22 UTC, rithviknishad commented
@JahnabDutta you are expected to update the cypress tests themselves if you think cypress is made for old components.

2023-06-05 08:10 UTC, nihal467 commented
@JahnabDutta 
<img width="602" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/110dfc6e-94b9-464c-9c6b-00c8650c6d38">
<img width="494" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/a0aee7f3-17f7-4369-b139-4307ccc6edcf">

- the date filters and assign to filters are still not changed to tailwind 

CC: @rithviknishad

2023-06-05 08:13 UTC, rithviknishad requested changes
Change `DateRangePicker` to its equivalent `FormField` component.

2023-06-05 10:09 UTC, JahnabDutta commented
Hey @rithviknishad, I changed the DateRangePicker to DateRangeFormField and tried adding a meaningful cypress test. However, I don't understand how to change the 'Assigned to' part. Also could you review the latest [commit ](https://github.com/coronasafe/care_fe/pull/5572/commits/ffff958ec829415e77e1ddb297526756cf950bc3). I'm not sure why this popped up and if it changes any files.

2023-06-08 17:28 UTC, rithviknishad commented
@JahnabDutta you'll have `UserAutocompleteFormField` once #5626 is merged.

Or you could merge that branch into this branch if you want to make use of it right away!

2023-06-11 09:12 UTC, JahnabDutta commented
@rithviknishad I have merged #5626 and made the requested changes. I have modified the cypress tests as well. Please review it if possible and let me know if it the changes are okay. 
Thanks!!

2023-06-13 04:42 UTC, rithviknishad requested changes

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("ordering")}</FieldLabel>
Pass label `prop` to form field components instead of using `FieldLabel`

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("is_emergency_case")}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>            <FieldLabel>{`${t("is")} ${kasp_string}`}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("is_upshift_case")}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("disease_status")}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("is_antenatal")}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
>          <FieldLabel>{t("breathlessness_level")}</FieldLabel>
same here

2023-06-13 04:42 UTC, rithviknishad commented on src/Components/Shifting/ListFilter.tsx
> +      </div>
Why is this wrapped inside a grid?

2023-06-13 09:32 UTC, JahnabDutta commented
Hey @rithviknishad,  I've made the requested changes. LMK if there's anything else as well.

2023-06-13 10:44 UTC, JahnabDutta commented
I tried using the following command to rebase-
![image](https://github.com/coronasafe/care_fe/assets/76475829/aeb72db4-c1c5-4696-8d50-1876c0436663)
However, I did not have any success. How do I solve the conflicts?

2023-06-13 10:46 UTC, rithviknishad commented
I do it without rebase.

```
git merge develop
git checkout <pr-branch>
git merge develop

# Resolve conflicts in editor
continue merge
```

2023-06-13 10:47 UTC, rithviknishad commented
Its a small conflict so you can just use github's editor itself if you want

2023-06-17 05:26 UTC, rithviknishad approved these changes

2023-06-20 06:40 UTC, nihal467 commented
LGTM

2023-06-21 06:45 UTC, khavinshankar approved these changes

2023-06-21 06:46 UTC, merged