Replaced Material UI with Care UI components in add bed form
coronasafe/care_fe pull request #5594
Opened 2023-06-03 23:03 UTC by print-Sathvik

## Proposed Changes

- Fixes #4942 
- Replaced Material UI with Care UI components in add bed form
- Replaced legacy form fields with newer fields

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2023-06-04 06:04 UTC, rithviknishad requested changes

2023-06-04 06:04 UTC, rithviknishad commented on src/Components/Facility/AddBedForm.tsx
> +                    />
@print-Sathvik do you have to pass the select as an optional manually? 
The newer components would auttomatically show the `placeholder` as an option based on `reuquired` prop

```suggestion
                    <SelectFormField
                      id="bed-type"
                      name="bed_type"
                      label="Bed Type"
                      required
                      options={LOCATION_BED_TYPES}
                      optionValue={(bedType) => bedType.id}
                      optionLabel={(bed) => bed.name}
                      value={bedType}
                      onChange={({ value }) => {
                        setBedType(value);
                      }}
                      error={errors.bedType}
                    />
```

2023-06-04 07:06 UTC, rithviknishad approved these changes

2023-06-05 13:24 UTC, nihal467 commented
@print-Sathvik check the cypress failing and fix it

2023-06-07 10:55 UTC, nihal467 commented
LGTM

2023-06-07 11:35 UTC, khavinshankar approved these changes

2023-06-07 11:36 UTC, merged