Handled the Rhythm card when no data is present
coronasafe/care_fe pull request #5641
Opened 2023-06-09 13:16 UTC by nikhilagastya

- Fixes #5468 
- Added a check before using the map

2023-06-09 14:02 UTC, rithviknishad approved these changes

2023-06-12 05:18 UTC, nihal467 commented
@nikhilagastya 
![image](https://github.com/coronasafe/care_fe/assets/57055998/dbf7a222-af84-4860-97c7-da3af094f11a)
![image](https://github.com/coronasafe/care_fe/assets/57055998/ce8d250c-2659-4613-8231-ba82d9347f03)

make it center aligned

2023-06-13 07:19 UTC, nikhilagastya commented
can you review it once @nihal467 !

2023-06-13 07:42 UTC, nihal467 commented
@nikhilagastya 
![image](https://github.com/coronasafe/care_fe/assets/57055998/bcb9e614-f0e6-4b9d-bd00-3b947eea7d46)

currently, when there is data, there is a lot of white space coming in both side

@Ashesh3 can you review it

2023-06-13 08:07 UTC, Ashesh3 requested changes

2023-06-13 08:07 UTC, Ashesh3 commented on src/Components/Facility/Consultations/PrimaryParametersPlot.tsx
> +        <div className="md:w-full flex justify-center overflow-x-auto pt-4 m-2 px-4 bg-white border rounded-lg shadow h-80">
@nikhilagastya We want the element taking up full width and centered. 

When there is no data available, we want the message to be at the center:

![image](https://github.com/coronasafe/care_fe/assets/3626859/d74c54d8-d520-4149-866f-981c15448a43)

When there is data, we want it to take full width, as mentioned by Nihal in the previous message. Try not to have padding/margins on x axis to center the elements, just setting the item's alignment to center should work. Let it take full width.

2023-06-13 08:07 UTC, rithviknishad requested changes

2023-06-13 08:07 UTC, rithviknishad commented on src/Components/Facility/Consultations/PrimaryParametersPlot.tsx
> +        <div className="md:w-full flex justify-center overflow-x-auto pt-4 m-2 px-4 bg-white border rounded-lg shadow h-80">
```suggestion
        <div className="md:w-full flex overflow-x-auto pt-4 m-2 px-4 bg-white border rounded-lg shadow h-80">
```

2023-06-13 08:07 UTC, rithviknishad commented on src/Components/Facility/Consultations/PrimaryParametersPlot.tsx
> +            <p className="px-4 self-center">No Rhythm data available.</p>
```suggestion
            <p className="mx-auto self-center">No Rhythm data available.</p>
```

2023-06-13 09:01 UTC, nikhilagastya commented
@nihal467 @Ashesh3 @rithviknishad is it okay now ?

2023-06-13 10:20 UTC, nihal467 commented
@rithviknishad @nikhilagastya 
![image](https://github.com/coronasafe/care_fe/assets/57055998/ae81f449-9698-4af1-a851-60d64089b120)

the bug still persist

2023-06-20 09:15 UTC, Ashesh3 commented
@nihal467 Made the changes.

![image](https://github.com/coronasafe/care_fe/assets/3626859/432b187e-2b02-49f1-8604-1fb01e6787d0)
![image](https://github.com/coronasafe/care_fe/assets/3626859/8f76d6a5-6a5e-4ae3-afdf-e5f16bdd716a)

![image](https://github.com/coronasafe/care_fe/assets/3626859/a44f8f9c-b58e-4753-920d-e3589f1f9877)
![image](https://github.com/coronasafe/care_fe/assets/3626859/3cc39873-a19e-4c54-af71-b842e6acdecb)
![image](https://github.com/coronasafe/care_fe/assets/3626859/c30cf056-3f3b-4636-9df2-a793d558f519)

2023-06-20 09:36 UTC, nihal467 commented
LGTM

2023-06-21 06:58 UTC, khavinshankar approved these changes

2023-06-21 06:59 UTC, khavinshankar commented
@Ashesh3 @rithviknishad can you review this pr again

2023-06-21 07:04 UTC, Ashesh3 approved these changes

2023-06-21 09:38 UTC, merged