wrapping of text patient note bug fixed
coronasafe/care_fe pull request #5645
Opened 2023-06-10 06:21 UTC by Mustafa-Azad025

### WHAT
Bug fixed : Text Overflow from Card in PatientNotes

##Changes

- Fixes #5633 
- White-space pre removed
- max-width : 100% added
-  Some padding added for alignment

## After Fixes
![image_Fixes](https://github.com/coronasafe/care_fe/assets/97380192/37c05791-56f7-4e09-9fc0-1fda58bbb8e7)

@rithviknishad  @kunal00000

2023-06-12 05:21 UTC, nihal467 commented
@khavinshankar @rithviknishad @Ashesh3 can anyone review this

2023-06-12 05:29 UTC, rithviknishad requested changes
Would multi-line doctor notes work this way since you've removed `whitespace-pre`? Was that necessary?

2023-06-12 05:32 UTC, kunal00000 commented
> Would multi-line doctor notes work this way since you've removed `whitespace-pre`? Was that necessary?

`whitespace-pre` doesn't wrap content, `whitespace-pre-wrap` would do all the work as expected.

2023-06-12 06:56 UTC, Mustafa-Azad025 commented
Thank you for reviews 😊.
I will try to do that changes.
But there is not a problem by removing white-space-pre as I added padding from left and it works same .

2023-06-12 07:22 UTC, kunal00000 commented
Try adding this note.
```
Hi,

Sample text

Today is Monday.
```

Without `whitespace-pre`:
```
Hi, Sample text Today is Monday.
```

2023-06-14 03:32 UTC, rithviknishad commented
@Mustafa-Azad025 any updates on this?

2023-06-14 03:52 UTC, Mustafa-Azad025 commented
Yes, I tried yesterday to inculcate whitespace pre wrap but the text overflow from container ! .I am finding solution that how I can use whitespace with wrap !?
But I will raised PR today anyhow with solution.

2023-06-14 03:54 UTC, kunal00000 commented
> Yes, I tried yesterday to inculcate whitespace pre wrap but the text overflow from container ! .I am finding solution that how I can use whitespace with wrap !?
> But I will raised PR today anyhow with solution.

Hey, just change `whitespace-pre` with `whitespace-pre-wrap`.

2023-06-14 03:56 UTC, rithviknishad commented
With `whitespace-pre-wrap` 

![image](https://github.com/coronasafe/care_fe/assets/25143503/2d5e47a2-5d46-4d38-8482-a776ff39933c)

2023-06-14 04:34 UTC, kunal00000 commented
> With `whitespace-pre-wrap`
Sorry, I didn't check it properly.
<img width="1171" alt="Screenshot 2023-06-14 at 10 02 57 AM" src="https://github.com/coronasafe/care_fe/assets/92316166/2c3f8fac-73ae-4025-a92c-0fefbcf1e129">
Now what I have observed is that if sentence has spaces between words it gets wrapped and if not it doesn't

2023-06-14 06:03 UTC, Mustafa-Azad025 commented
Hi @rithviknishad and @kunal00000 ,
please check my PR.
I used break words to solve this issue.

2023-06-14 09:20 UTC, rithviknishad commented
You've not made any commits to this branch i guess

2023-06-14 09:21 UTC, rithviknishad commented
Looks like you've made a new PR

2023-06-14 09:21 UTC, closed without merging

2023-06-14 09:23 UTC, Ashesh3 commented
Closed in favor of https://github.com/coronasafe/care_fe/pull/5671

2023-06-14 12:39 UTC, Mustafa-Azad025 commented
> Looks like you've made a new PR

Yes, I made new PR