Bug Fixed : Default filters on patients page loads
coronasafe/care_fe pull request #6189
Opened 2023-08-31 02:06 UTC by mustafaazad03

### WHAT
Solved the bug for An empty filter for emergency phone numbers to be applied by default.

## Proposed Changes
![image](https://github.com/coronasafe/care_fe/assets/97380192/fd753a5d-ae7f-4aa6-b7dd-9337d3b7e4dd)
![image](https://github.com/coronasafe/care_fe/assets/97380192/bbd742e1-5111-423a-896a-7396b2e930de)

- Fixes #6101 
- Implement the check for phone number and also make it null
- Implement the check for emergency phone number and make it null
- Make the limit equal to null as a default

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2023-08-31 03:57 UTC, rithviknishad requested changes
Nice work on fixing it! However, is setting limit=null necessary?

`useFilters`'s limit prop is for identifying the pagination limit when paginating, and is not a default value!

And hence causes to:
<img width="585" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/71f47158-971a-4200-8e6c-584930f214c4">

Rest all LGTM!

2023-08-31 03:58 UTC, rithviknishad commented
Btw, you can keep pushing to this current branch instead of always re-opening a new PR! The commits will be squashed and merged anyways once tested!

2023-08-31 04:03 UTC, mustafaazad03 commented
Ok I will see thanks for pointing out 🙂.

2023-08-31 04:04 UTC, rithviknishad requested changes

2023-08-31 04:04 UTC, rithviknishad commented on src/Components/Patient/ManagePatients.tsx
> +    limit: null,
```suggestion
    limit: 12,
```

2023-08-31 04:04 UTC, rithviknishad commented on src/Components/Patient/ManagePatients.tsx
> +      // updateQuery({ phone_number: "" });
```suggestion
```

2023-08-31 04:13 UTC, mustafaazad03 commented
Hi @rithviknishad, I update all suggested changes will you please check

2023-08-31 04:16 UTC, rithviknishad approved these changes
Nice work @mustafaazad03! LGTM.

2023-09-05 09:03 UTC, nihal467 commented
LGTM

2023-09-05 14:47 UTC, khavinshankar approved these changes

2023-09-05 14:47 UTC, merged