Replace all window.location.reload() with data refetch.
coronasafe/care_fe pull request #6892
Opened 2023-12-21 14:02 UTC by sriharsh05

## Proposed Changes

- Fixes #6756 
- replaced window.location.reload with fetchdata function in patient discharge.
- replaced window.location.reload with  refetch while updating facility cover image.
- replaced window.location.reload with  refetch in assetImportModal.
-replaced window.location.reload with appropriate refetch in update app.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-12-21 14:46 UTC, rithviknishad requested changes

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Common/UpdatableApp.tsx
`UpdatableApp` needs to do `window.location.reload()` itself since all the latest resources needs to be re-fetched.

Revert changes made related to `UpdatableApp`

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Assets/AssetImportModal.tsx
> +      onUpdate && onUpdate();
```suggestion
      onUpdate?.();
```

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Assets/AssetsList.tsx
> +  };
Why refetch everything when only the asset list is being updated?

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Patient/PatientInfoCard.tsx
> +                props.fetchPatientData({ aborted: false });
```suggestion
              props.fetchPatientData?.({ aborted: false });
```

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Patient/PatientInfoCard.tsx
> +            }}
Wouldn't this cause this to unnecessarily refetch when the dialog is closed without clicking on submit?

2023-12-21 14:46 UTC, rithviknishad commented on src/Components/Users/UserProfile.tsx
> +  };
Not relevant. Updatable App should cause `window.location.reload()` itself instead of simply re-fetching user profile details.

```suggestion
```

2023-12-21 18:37 UTC, sriharsh05 commented
@rithviknishad 
Please review the changes.

2023-12-22 03:14 UTC, rithviknishad approved these changes

2023-12-27 14:44 UTC, nihal467 commented
LGTM

2023-12-28 01:07 UTC, khavinshankar approved these changes

2023-12-28 01:10 UTC, merged