Added Timeline UI for Bed Activity
coronasafe/care_fe pull request #6901
Opened 2023-12-24 09:35 UTC by thedevildude

## Proposed Changes

- Fixes #6771 
- Integrated Timeline for Bed Activity using **BedActivityTimeline**

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2023-12-25 07:34 UTC, rithviknishad requested changes
Nice attempt, but couple of things:

1. It'd be nice to have the screenshot of the changes always attached if it's a UI change.

2. The folder name "BedAdministration" does not make sense. 

3. The UI could be improved, like the "IN USE" chip seems to be relatively bigger than the surrounding elements. This can be made small.

3. The first element does not seem to have a connecting line to the second element. 

4. The last element seems to have an unnecessary connecting line drawn to a no element existing beyond it. This can be removed.

2023-12-27 03:26 UTC, rithviknishad approved these changes

2023-12-27 03:30 UTC, rithviknishad requested changes
We are currently showing time in two places which is redundant.

Also can we improve the wording to something like this instead (just suggesting, feel free to add your creativity)

```
- Transferred to <b>{bed_name} in {location_name}</b>   (relative time)
- Transferred to <b>{bed_name} in {location_name}</b>   (relative time)
- Occupied <b>{bed_name} in {location_name}</b>         (relative time)
```

2023-12-29 09:58 UTC, thedevildude commented
> We are currently showing time in two places which is redundant.
> 
> Also can we improve the wording to something like this instead (just suggesting, feel free to add your creativity)
> 
> ```
> - Transferred to <b>{bed_name} in {location_name}</b>   (relative time)
> - Transferred to <b>{bed_name} in {location_name}</b>   (relative time)
> - Occupied <b>{bed_name} in {location_name}</b>         (relative time)
> ```

I'll be working on some mockups and share them on channel

2024-02-15 15:18 UTC, rithviknishad approved these changes

2024-02-20 07:27 UTC, rithviknishad approved these changes

2024-02-20 10:16 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/0200e474-ee0b-443d-a13f-ed7a0d08aef3)

@aparnacoronasafe is this UI Ok ?

2024-02-21 08:14 UTC, nihal467 commented
@thedevildude make the following changes to the PR: 

![image](https://github.com/coronasafe/care_fe/assets/57055998/7c1c3e6c-1c17-4da7-8fe0-f5bffad2c6d8)

- [ ] move all the input field's to one row
- [ ] change the in use badge to similar design as of no consultation badge and primary colour
- [ ] move relative time (created at) into a pop-over of (i) icon , and replace the relative time with (i) icon in the design
- [ ] modify the asset linked text to explicitly mention the asset is linking or unlinking in a bed and dont have a explicit heading called linked assets
![image](https://github.com/coronasafe/care_fe/assets/57055998/84932ab6-90aa-402e-b18c-937c582a0652)

- [ ] have explicit icons for asset link (need to add) , asset unlinking (need to add) and bed assigned(already exist in your PR)

2024-03-11 10:31 UTC, thedevildude commented
@aparnacoronasafe 
Looking for your input on the current Timeline UI for Bed activity. As we are not tracking asset changes on the backend, I have implemented manual checks on the frontend to determine which assets have changed.  I've segregated the assets into three categories for each Timeline Node namely, Newly Linked Assets (assets linked in that node), Existing Assets (carry over from previous object) and Unlinked Assets (assets that were unlinked in that node. 

![image](https://github.com/coronasafe/care_fe/assets/63492939/a1211ee1-23c5-406a-9901-7f8086f8d153)

2024-03-17 12:23 UTC, rithviknishad reviewed
LGTM

2024-03-17 12:23 UTC, rithviknishad commented on src/Components/Facility/Consultations/BedActivityTimeline.tsx
> +        )}
```suggestion
        {bed.end_date === null && (
          <Chip
            text="In Use"
            startIcon="l-notes"
            size="small"
            variant="primary"
            className="ml-5"
          />
        )}
```

2024-03-17 12:23 UTC, rithviknishad approved these changes
LGTM

2024-03-18 16:22 UTC, Ashesh3 approved these changes

2024-03-19 09:40 UTC, nihal467 commented
@thedevildude 
![image](https://github.com/coronasafe/care_fe/assets/57055998/88eb8562-dc7a-4856-b973-76d7d625eff5)

- [ ] in one of the EOD call, we decided to keep each individual field in its separate rows.

![image](https://github.com/coronasafe/care_fe/assets/57055998/0314913a-ff7b-4ef4-99d0-e0a586fbb880)

- [ ] the icon of present bed should be green for the current bed

2024-03-21 05:35 UTC, rithviknishad requested changes
There is uneven spacing between the fields now...

<img width="764" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/f68df73e-7d58-4916-a6af-59a87bd30cd5">

2024-03-21 05:36 UTC, rithviknishad commented
Also, can we have a divider between the form and the timeline?

And maybe move the move to bed button to the right?

2024-03-22 06:03 UTC, rithviknishad approved these changes

2024-03-23 06:00 UTC, Ashesh3 approved these changes

2024-03-26 17:08 UTC, nihal467 commented
@thedevildude 
![image](https://github.com/coronasafe/care_fe/assets/57055998/856af797-afbf-4289-9caa-4eb684aa9aa1)

hide the "No asset linked" , only show details about asset, if anything is linked

2024-04-16 22:09 UTC, nihal467 commented
@thedevildude fix the lint

2024-04-17 20:21 UTC, thedevildude commented
@nihal467 not sure if the Lint workflow is providing correct results. Locally the said files doesn't have any linting errors.

2024-04-18 06:46 UTC, rithviknishad commented
try re-installing the packages in your local. Recently the version has changed and seems to be causing similar issues for couple of contributors

2024-04-24 06:12 UTC, nihal467 commented
LGTM

2024-04-24 11:35 UTC, Ashesh3 approved these changes

2024-04-24 11:39 UTC, khavinshankar approved these changes

2024-04-24 12:09 UTC, rithviknishad approved these changes

2024-04-24 12:10 UTC, merged