Doctor
coronasafe/care_fe pull request #6913
Opened 2023-12-25 19:52 UTC by shramanpaul

## Proposed Changes

- Fixes #6824 

- Change 1 :  submit by pressing enter on the keyboard
- Change 2 : have a draft feature for the messages that were typed and not posted (this should also fix the issue of typed message going away when going full screen or vice versa)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

https://github.com/coronasafe/care_fe/assets/110323017/5546a8e2-b922-42fa-8734-d3de06d17eae

please have a review @rithviknishad

2023-12-27 03:18 UTC, rithviknishad commented on src/Components/Form/FormFields/TextFormField.tsx
> +      onChange={props.onChange}
Why was this changed?

This would break all of the other existing usages of the text form field in the platform.

2023-12-27 03:20 UTC, rithviknishad requested changes
Check how `TextFormField` is used in other places. We are using custom components that has slightly different interface from the standard HTML input elements' interface.

2023-12-27 03:20 UTC, rithviknishad commented on src/Components/Form/FormFields/TextFormField.tsx
> +      onChange={props.onChange}
Why was this changed?

This would break all of the other existing usages of the text form field in the platform.

2023-12-27 03:22 UTC, rithviknishad requested changes

2023-12-27 03:22 UTC, rithviknishad commented on package-lock.json
Revert the package lock changes too

2023-12-27 03:33 UTC, rithviknishad requested changes
@shramanpaul you can ignore the keyboard shortcut feature as it's already covered correctly in #6915

2023-12-27 03:34 UTC, rithviknishad commented
It'd also be nice to change the PR title to be something more appropriate to the changes you've made.

2023-12-27 13:35 UTC, shramanpaul commented
Ok @rithviknishad then i will be making a new PR with the proposed changes and will be linking this pr along with it.

2023-12-30 05:01 UTC, closed without merging

2023-12-30 05:01 UTC, rithviknishad commented
Closing as alt. #6932