added the draft feature in the doctor's notes
coronasafe/care_fe pull request #6932
Opened 2023-12-27 16:07 UTC by shramanpaul

## Proposed Changes

- Fixes #6824
- added the draft feature using localstorage 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

https://github.com/coronasafe/care_fe/assets/110323017/e5600f92-6c45-44c1-8e54-18c66c4f97ef

continuing from PR #6913 

made the requested changes @rithviknishad

2023-12-27 16:31 UTC, rithviknishad requested changes
the draft is not specific to a consultation

2023-12-28 13:42 UTC, shramanpaul commented
> the draft is not specific to a consultation

Thank you for your feedback! Could you please provide more details or guidance on what you mean by 'the draft is not specific to a consultation'?

2023-12-28 15:39 UTC, rithviknishad commented
let's say you've typed a message and not posted for consultation A of patient A.

you've opened consultation B of patient B, and this would end up restoring the draft of consultation A, right?

the local storage key/value is not uniquely identifying which consultation it belongs to

2023-12-28 17:01 UTC, shramanpaul commented
Thank you for the clarification. I have made the draft specific to consultation 

https://github.com/coronasafe/care_fe/assets/110323017/69bd27b5-ba3d-449f-85b2-3933fa783312

2023-12-29 05:50 UTC, rithviknishad commented on src/Components/Facility/PatientNotesSlideover.tsx
> +  const localStorageKey = `patientNotesNoteField_${patientId}`;
Its better to keep it consultation-specific rather than patient-specific since a patient can have multiple consultations.

2023-12-29 05:50 UTC, rithviknishad requested changes
ts better to keep it consultation-specific rather than patient-specific since a patient can have multiple consultations.

2023-12-30 05:02 UTC, rithviknishad requested changes

2023-12-30 05:02 UTC, rithviknishad commented on src/Components/Facility/PatientNotesSlideover.tsx
> +  const localStorageKey = `patientNotesNoteField_${patientId}`;
This is specific to a patient, not specific to a consultation.
```suggestion
  const localStorageKey = `patientNotesNoteField_${consultationId}`;
```

2023-12-30 08:20 UTC, shramanpaul commented
Ok @rithviknishad I will be making the changes to the PR today

2023-12-30 15:03 UTC, rithviknishad approved these changes

2024-01-01 12:57 UTC, nihal467 commented
LGTM

2024-01-04 03:21 UTC, khavinshankar approved these changes

2024-01-04 03:21 UTC, merged