date format changed
coronasafe/care_fe pull request #6950
Opened 2023-12-30 04:50 UTC by AdityyaX

## Proposed Changes

- Fixes #6830 
- Format of DOB in patient section changed to DD/MM/YYYY Format

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Screenshot
<img width="1440" alt="Screenshot 2023-12-30 at 10 18 52 AM" src="https://github.com/coronasafe/care_fe/assets/103623274/56a9847d-031c-4800-b6a3-5e9e13493a20">

made the requested changes @rithviknishad

2023-12-30 04:54 UTC, rithviknishad requested changes
We already have a reusable utility function called: `formatDate` that does this for you.

2023-12-30 04:54 UTC, rithviknishad commented on src/Components/Patient/PatientHome.tsx
> +
```suggestion
```

2023-12-30 04:54 UTC, rithviknishad commented on src/Components/Patient/PatientHome.tsx
> +                    {formatDateOfBirth(patientData?.date_of_birth)}
```suggestion
                    {formatDate(patientData?.date_of_birth)}
```

2023-12-30 05:16 UTC, AdityyaX commented
@rithviknishad 
Okay i have made the suggested changes

2023-12-30 05:18 UTC, rithviknishad reviewed
Are you sure you've imported the required method?

2024-01-07 04:24 UTC, rithviknishad approved these changes

2024-01-10 07:20 UTC, nihal467 commented
LGTM

2024-01-10 07:54 UTC, khavinshankar approved these changes

2024-01-10 07:55 UTC, merged