Fix: hide Monitors without a patient checkbox filter is not toggling
coronasafe/care_fe pull request #6992
Opened 2024-01-07 11:44 UTC by GokulramGHV

## Proposed Changes

- Fixes #6991 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-01-07 13:23 UTC, rithviknishad requested changes
why is a state required? query params itself holds the state and it worked before that way.

2024-01-07 13:28 UTC, GokulramGHV commented
> why is a state required? query params itself holds the state and it worked before that way.

If I don't use a state then the checkbox doesn't get checked or unchecked quickly, there's some noticeable delay when you do so.

2024-01-07 13:30 UTC, rithviknishad commented
why is the noticeable delay being caused?

2024-01-07 13:37 UTC, GokulramGHV commented
> why is the noticeable delay being caused?

Sorry my bad, the delay was seemed to have caused because of my computer slowing down. 
I tried again and the checking and unchecking the checkbox works without any delay.
I'll update the PR with the suggested changes.

2024-01-07 13:39 UTC, GokulramGHV commented
But there's still a noticeable delay when you click the checkbox and the monitors (without patients) appearing and reappearing due to the api call.
Do you want me to add a loading icon for this?

2024-01-07 17:02 UTC, rithviknishad commented on src/Components/Facility/CentralNursingStation.tsx
> +                        updateQuery({ [name]: value });
are you sure this is right? we don't want to filter by `bed_is_occupied==False` when unchecked, rather we don't want to perform the filter itself based on `bed_is_occupied` when unchecked right?

2024-01-07 17:05 UTC, rithviknishad commented
> But there's still a noticeable delay when you click the checkbox and the monitors (without patients) appearing and reappearing due to the api call.
> Do you want me to add a loading icon for this?

Yup that can be done! We can show the CARE loading icon when the useQuery's `loading` is true.

2024-01-08 09:55 UTC, rithviknishad approved these changes
@GokulramGHV 

I've pushed the fix (and also shows the loading component when refetching) as this had to be fixed by today evening. cc: @nihal467 

The issue was the query param variable is of type string, but the checkbox expected value of type boolean. Hence the issue.

2024-01-08 11:24 UTC, GokulramGHV commented
> I've pushed the fix (and also shows the loading component when refetching) as this had to be fixed by today evening. cc: @nihal467
> 
> The issue was the query param variable is of type string, but the checkbox expected value of type boolean. Hence the issue.

@rithviknishad Thanks for pushing a fix. I'm so sorry for not seeing your comment earlier and fixing it.

2024-01-08 12:06 UTC, nihal467 commented
LGTM

2024-01-08 12:09 UTC, khavinshankar approved these changes

2024-01-08 12:09 UTC, merged