Fixed close Button in Treatment Summary
coronasafe/care_fe pull request #7001
Opened 2024-01-10 16:05 UTC by sriharsh05

## Proposed Changes

- Fixes #6877 
- Fixed close Button in Treatment Summary.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-01-10 17:08 UTC, rithviknishad requested changes

2024-01-10 17:08 UTC, rithviknishad commented on src/Components/Facility/TreatmentSummary.tsx
> +              }
use `goBack` from `useAppHistory` instead of useSlug + navigate

2024-01-11 09:40 UTC, sriharsh05 commented on src/Components/Facility/TreatmentSummary.tsx
> +              }
Close Button in treatment summary is not functioning only when you access the page using a link.

Try closing treatment summary using this link : https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/treatment-summary

 If I use `goBack` or `window.history.go(-1)` the close button is working fine in normal cases but not working when you access the page directly through the link.

2024-01-11 12:19 UTC, rithviknishad commented on src/Components/Facility/TreatmentSummary.tsx
> +              }
pass that url to the goBack as arg. it'll be used as a fallback if no history is present in the app.

2024-01-11 12:34 UTC, sriharsh05 commented
@rithviknishad 
Please review the changes.

2024-01-11 12:48 UTC, rithviknishad approved these changes

2024-01-16 12:38 UTC, Ashesh3 approved these changes
LGTM.

I wonder if we could have just used `..` as the fallback URL.

2024-01-16 19:16 UTC, nihal467 commented
@sriharsh05 cypress is failing, fix the issue

2024-01-23 06:51 UTC, sriharsh05 commented
@rithviknishad 
Please approve the PR.

2024-01-23 07:12 UTC, rithviknishad approved these changes

2024-01-29 19:49 UTC, nihal467 commented
LGTM

2024-01-31 07:41 UTC, khavinshankar approved these changes

2024-01-31 07:41 UTC, merged