Added authorization on route for asset creation
coronasafe/care_fe pull request #7111
Opened 2024-01-27 11:00 UTC by kshitijv256

## Proposed Changes

- Fixes #7081 
- Added Authorized route on asset creation allowing only NonReadonly user to access

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-01-27 11:41 UTC, rithviknishad requested changes
@kshitijv256 Update permissions in backend too to disallow this operation for read only users

2024-01-27 11:41 UTC, rithviknishad commented on src/Utils/AuthorizeFor.tsx
> +});
We already have the filter function defined just below it. Re-use it.

```suggestion
export const NonReadOnlyUsersList = USER_TYPES.filter(NonReadOnlyUsers);
```

2024-02-23 09:38 UTC, rithviknishad requested changes
by mistake

2024-02-23 09:39 UTC, rithviknishad approved these changes

2024-02-23 09:40 UTC, rithviknishad commented
@kshitijv256 still not followed up on the backend PR
https://github.com/coronasafe/care/pull/1868#pullrequestreview-1896428501

2024-02-23 10:19 UTC, kshitijv256 commented
@rithviknishad I have made the requested changes in backed PR as well, can I take on other issues or wait for that to be closed first ?

2024-02-23 10:24 UTC, rithviknishad commented
Yes @kshitijv256 you can take other issues 🚀

2024-03-10 04:13 UTC, closed without merging