Add max validation for doctor experience years in add user form
coronasafe/care_fe pull request #7161
Opened 2024-02-04 04:50 UTC by sriharsh05

## Proposed Changes

- Fixes #7143 
- Add max validation for doctor experience years in add user form.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-02-04 04:53 UTC, rithviknishad requested changes
The validation should also be present in Edit User Profile page

2024-02-04 05:15 UTC, sriharsh05 commented
@rithviknishad 
Please review the changes.

2024-02-04 05:21 UTC, rithviknishad approved these changes

2024-02-04 05:26 UTC, Ashesh3 approved these changes

2024-02-04 21:44 UTC, nihal467 commented
LGTM

2024-02-06 19:37 UTC, khavinshankar approved these changes

2024-02-06 19:37 UTC, merged