Add Cypress test to patient file upload
coronasafe/care_fe pull request #7197
Opened 2024-02-08 20:40 UTC by AshrafMd-1

## Proposed Changes

- Fixes #7086 
- Add IDs to tags
- Add cypress testing

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-02-08 20:42 UTC, AshrafMd-1 commented
@nihal467 for the following 

[ ] Verify the uploaded file can only be modified by the author, district admin, and above users.
[ ]  Verify file download is possible for all users.

Do I need to sign to each kind of user and check or is there a different way?

2024-02-11 18:27 UTC, nihal467 commented
@AshrafMd-1 

way of approach should be like , use two nurse type and one district admin

Test - 1 Part-1 : Verify the uploaded file can only be modified by the author, district admin, and above users.
- [ ] First, upload a file to a patient file using the nurse user ID-1, and edit the file successfully.
- [ ] Now, log out as nurse user ID-1 and log in as nurse user ID-2. Then try to edit the same file. Expected behavior: "Nurse user ID-2 shouldn't be able to edit the file uploaded by nurse user ID-1." Verify this behavior.
- [ ] Now, log out as nurse user ID-2 and log in as a district admin. Edit the file uploaded by nurse user ID-1. Expected behavior: "The admin should be able to edit the file uploaded by nurse user ID-1."

Test - 1 Part-2 : Verify file download is possible for all users.

- [ ] Verify that the download functionality is working for nurse user ID-1 and the district admin, along with the part-1 test.

@AshrafMd-1 Answer to the question : Only check for district admin and nurse userID

2024-02-11 18:30 UTC, AshrafMd-1 commented
@nihal467 done I understood

Also other small doubt what patient should I use

2024-02-11 19:02 UTC, nihal467 commented
@AshrafMd-1 don't create a new patient, just select a patient in the existing dummy data

2024-02-15 19:09 UTC, AshrafMd-1 commented
@nihal467 is there any credentials for 
nurse id-1 and nurse id-2 or should I create a new user first

2024-02-18 09:02 UTC, AshrafMd-1 commented
@nihal467 can you check this once 

cc: @rithviknishad

2024-02-26 17:57 UTC, nihal467 requested changes

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
```suggestion
    cy.verifyNotification("File Uploaded Successfully");
```

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
```suggestion
    cy.verifyNotification("File Uploaded Successfully");
```

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
```suggestion
    cy.verifyNotification("File name changed successfully");
```

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
cy.verifyNotification("File archived successfully");

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
replace with cy.verifyNotification

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    patientFileUploadPage.verifySuccessNotification(
replace with cy.verifyNotification

2024-02-26 17:57 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +      "File name changed successfully"
replace with cy.verifyNotification

2024-02-26 17:57 UTC, nihal467 commented on cypress/pageobject/Patient/PatientFileupload.ts
> +    cy.get("#submit").click();
cy.submitButton("text inside the button");

2024-02-26 17:57 UTC, nihal467 commented on cypress/pageobject/Patient/PatientFileupload.ts
> +    cy.get("#submit").click();
cy.submitButton("text inside the button");

2024-02-26 17:57 UTC, nihal467 commented on cypress/pageobject/Patient/PatientFileupload.ts
> +  verifySuccessNotification(msg: string) {
delete this variable since we will be using the verify notification from command.ts file

2024-02-26 18:00 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    );
along with the notification, verify it is visible in the file list

2024-02-26 18:00 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    );
along with the notification, verify it is visible in the file list

2024-02-26 18:00 UTC, nihal467 commented on cypress/e2e/patient_spec/patient_detailpage.cy.ts
> +    );
along with the notification, verify it is visible in the file list

2024-02-26 18:30 UTC, nihal467 commented on cypress/pageobject/Patient/PatientFileupload.ts
> +    cy.get("#file-div").should(
verify the archive reason by clicking "more details"

2024-02-26 18:33 UTC, nihal467 commented
Test 1: Record an Audio and download the file.

Record an audio.
Verify its success through notification and reflection in the list.
Verify the file and ensure its reflection in the list as well as notification.
Try to download the file and verify its success using API response with cy.intercept.

By performing the above tasks, you can remove the following tests:

"Verify uploaded file can be edited by author"
"Verify that file download is possible for district admin and above"
"Verify that file download is possible for author"

Test 2: Upload a File and archive it

Upload a file and verify its reflection in the list.
Archive the file and verify the file list along with the reason.

By performing the above tasks, you can remove the test "Archive file and verify it."

Test 3: User-level Based Permission for File Modification

Upload a file using Nurse ID-1 and download it.
Edit the file using Nurse ID-1.
Log in as Nurse ID-2 and verify that the file can't be edited.
Log in as district admin and verify that the file can be edited.

You can remove the test "Verify that file download is possible for users below district admin."

2024-03-01 07:52 UTC, AshrafMd-1 commented
@nihal467 
for 
> Test 1: Record an Audio and download the file.
> - Try to download the file and verify its success using API response with cy.intercept.

Its a anchor tag so verifying with API is not possible so what if I change the tests in this format 

how about this 

> test1 : Upload a file and download file

>test2 : record a audio and archive it

2024-03-01 18:36 UTC, AshrafMd-1 commented
@nihal467 can u check once

2024-03-03 07:34 UTC, AshrafMd-1 commented
@nihal467 can you check once why Cypress is failing 
because it works perfectly on my computer 

I feel it's due to not having the nurse logins

2024-03-08 06:42 UTC, AshrafMd-1 commented
@rithviknishad  can u remove the merge-conflict label 

also is it possible to add nurse login to dummy database in care ?

2024-03-12 04:34 UTC, rithviknishad commented
Yup, you can load the dummy data on to a fresh volume, add the required users and dump it again as json

2024-03-12 06:49 UTC, nihal467 commented
> @nihal467 for
> 
> > Test 1: Record an Audio and download the file.
> > 
> > * Try to download the file and verify its success using API response with cy.intercept.
> 
> Its a anchor tag so verifying with API is not possible so what if I change the tests in this format
> 
> <img alt="image" width="268" src="https://private-user-images.githubusercontent.com/98876115/309187006-116309e4-1ce2-461d-9d1e-e0d781d95865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjYwMTgsIm5iZiI6MTcxMDIyNTcxOCwicGF0aCI6Ii85ODg3NjExNS8zMDkxODcwMDYtMTE2MzA5ZTQtMWNlMi00NjFkLTlkMWUtZTBkNzgxZDk1ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZTgyNGFkMzdmNzcyMTNiODI3MGJmYzc5MjQ1MDZiNjUwYzk1ODdjZDE5MjkwYTRiMzA3ZjZhYWE2ZTk3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n735IbyQ_w9FGw2oJmF8OrUdvP1MfvFKDPitjGB8ymk">
> how about this
> 
> > test1 : Upload a file and download file
> 
> > test2 : record a audio and archive it

@AshrafMd-1 when you upload a file the API "https://care.coronasafe.in/api/v1/files/" gives you 201 responses verify that using the cy.intercept .

_Note: Its fine to only do api verification for file upload in this case_

2024-03-12 16:37 UTC, AshrafMd-1 commented
@nihal467 I have made changes as you have referenced 
Can you check once

2024-03-17 20:14 UTC, nihal467 commented
@AshrafMd-1 your test is failing

2024-03-19 04:31 UTC, AshrafMd-1 commented
@nihal467 once this PR gets merged in care related to nurse logins, then I will rerun the tests 

https://github.com/coronasafe/care/pull/1985

2024-03-19 11:18 UTC, nihal467 commented
@AshrafMd-1 the test is again failing, the backend is merged

2024-03-19 17:08 UTC, AshrafMd-1 commented
@nihal467 I am not able to understand the error 
The tests works locally but when I upload here no patients are found 

- I did check the district `ernakulam`
- The home facility `dummy facility 40`

But then the screenshots says no patients are found 

So can you give me some guidance on what to do?

2024-03-19 18:57 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/75b74939-32d9-4ba0-bb99-0ba01bb0ed13)

@AshrafMd-1 check the login id user access, whether it is having the particular facility access

2024-03-20 15:55 UTC, AshrafMd-1 commented
@nihal467 

Here is the nurse1 profile
<img width="415" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/1a625c53-79c5-4f75-9d25-a34ebd122440">

Here is its data

<img width="505" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/03bbebca-0ff8-4dcb-80c6-ca8b2aa3bff0">


But its showing no facility or patients 
<img width="668" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/2bfe4d02-00d6-446e-ad01-38477424faf5">

2024-03-20 15:58 UTC, AshrafMd-1 commented
```
{"model": "users.user",
        "pk": 23,
        "fields": {
            "password": "argon2$argon2id$v=19$m=102400,t=2,p=8$WDE0YXVzR1dIV09zNWJZalF4QzdXSw$ZTpeDj5sbB3TKfu0DEJ5EkQnL3EmM2vGgvdx+Qt2sAw",
            "last_login": "2024-03-18 17:04:08.753272+00",
            "is_superuser": false,
            "first_name": "Dummy",
            "last_name": "Nurse",
            "email": "dummynurse1@test.com",
            "is_staff": false,
            "is_active": true,
            "date_joined": "2024-03-08 06:31:23.199154+00",
            "username": "dummynurse1",
            "user_type": 14,
            "created_by": 1,
            "ward": null,
            "local_body": null,
            "district": 7,
            "state": 1,
            "phone_number": "+918878825662",
            "alt_phone_number": "+918878825662",
            "gender": 2,
            "age": 21,
            "home_facility": 1,
            "verified": true,
            "deleted": false,
            "pf_endpoint": null,
            "pf_p256dh": null,
            "pf_auth": null,
            "asset": null,
            "groups": [],
            "user_permissions": []
            }
```
            
Also here is the data for nurse 1 is there any wrong?

cc: @rithviknishad

2024-03-25 13:44 UTC, AshrafMd-1 commented
@nihal467 once this PR https://github.com/coronasafe/care/pull/2012 is merged i will  test it again 

Also I will create a new PR as there are test commits here

2024-03-31 07:20 UTC, AshrafMd-1 commented
Add this PR has many test commits I will close and open a new PR

2024-03-31 07:20 UTC, closed without merging