Replace useDispatch with useQuery and request in PatientRegistration form.
coronasafe/care_fe pull request #7216
Opened 2024-02-15 02:31 UTC by sriharsh05

## Proposed Changes

- Fixes #7171 
- Replace useDispatch with useQuery and request in PatientRegister.tsx

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-02-15 02:44 UTC, sriharsh05 commented
Hey @rithviknishad ,

In the useQuery block of the `getPatient` API call, the patient details are not being assigned to the form. I have console logged the data, which is fetched at line no: 448. The data logs properly, but it is not being dispatched at line no: 449.

Can you please point out what mistake I made?

2024-02-15 03:52 UTC, rithviknishad requested changes
Although the reducer state is being updated, the `field` from the `<Form>` is not being updated. `<Form>` already has a reducer to handle form state and errors. And in the Patient Register page we are keeping another reducer to handle form state and errors for the same purpose. This leads to not having a single source of truth.

Either use `<Form>` alone by removing the reducer and rely on it's `asyncDefaults` prop to pre-fill the form during edit form, or remove the usage of `<Form>` and rely on the custom defined reducer alone.

2024-02-15 03:52 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +  const [localBodyId, setLocalBodyId] = useState<number>();
Why are these states added? We are already tracking these in the form reducer right?

2024-02-15 03:52 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +        setLocalBodyId(data.local_body),
What is a setState call doing inside Promise.all?

2024-02-15 04:05 UTC, rithviknishad commented
Although not recommended, you could set key of the form with a value dependent on the form state (maybe a hash or something), to force update the Form's provider value. Use this as a last resort.

<img width="922" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/5988d89f-c5b0-4019-9535-0a59f8913439">

2024-02-22 02:57 UTC, sriharsh05 commented
@rithviknishad 
Please review the changes.

2024-02-22 04:06 UTC, rithviknishad requested changes

2024-02-22 04:06 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +  const [localBodyId, setLocalBodyId] = useState<number>();
This is still unresolved.

2024-02-23 03:07 UTC, sriharsh05 commented
@rithviknishad 
Please review the code.

2024-02-23 03:19 UTC, rithviknishad approved these changes

2024-02-23 05:33 UTC, Ashesh3 approved these changes

2024-02-27 10:29 UTC, nihal467 commented
LGTM

2024-02-28 04:16 UTC, khavinshankar approved these changes

2024-02-28 04:16 UTC, merged