Added IP Days Chip in Patient List and Patient Dashboard
coronasafe/care_fe pull request #7252
Opened 2024-02-22 18:16 UTC by konavivekramakrishna

## Proposed Changes

- Fixes #6684 
- Added IP days chip in patient list and patient dashboard
![image](https://github.com/coronasafe/care_fe/assets/101407963/511c1abb-2022-41b8-a4f3-136863e08868)
![image](https://github.com/coronasafe/care_fe/assets/101407963/1ab5da27-85a7-4602-89a3-486a12d36a96)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-02-22 18:46 UTC, rithviknishad approved these changes

2024-02-22 19:08 UTC, Ashesh3 requested changes

2024-02-22 19:08 UTC, Ashesh3 commented on src/Utils/utils.ts
> +}
```suggestion
export function daysUntilToday(inputDate: Date | string) {
  const date = dayjs(inputDate);
  return dayjs().diff(date, 'day');
}
```

Let's use dayjs for cleaner code.

2024-02-23 05:34 UTC, Ashesh3 approved these changes

2024-02-28 06:24 UTC, nihal467 commented
@konavivekramakrishna 
![image](https://github.com/coronasafe/care_fe/assets/57055998/c18bd520-1390-4741-8e08-50badb4a8cb9)

- [ ] Make the IP Days a circle badge on the consultation page similar to the MEWS score.

2024-03-01 08:56 UTC, vivramkrishna commented
![image](https://github.com/coronasafe/care_fe/assets/101407963/f11f2d40-e10a-4cbc-ba44-9efa5c5b0b95)


edge case when the year is 0202 it returns NaN

should this be handled?

2024-03-13 04:19 UTC, rithviknishad commented
> edge case when the year is 0202 it returns NaN

can be ignored. newer data wouldn't have weird years right.

2024-03-13 04:21 UTC, rithviknishad requested changes

2024-03-13 04:21 UTC, rithviknishad commented on src/Components/Patient/PatientInfoCard.tsx
> +                    : "0"}
Can we hide IP days for Non Admission Cases instead of showing 0?

2024-04-16 13:06 UTC, nihal467 commented
@konavivekramakrishna resolve the merge conflict

2024-04-18 13:17 UTC, konavivekramakrishna commented
- ![image](https://github.com/coronasafe/care_fe/assets/101407963/0cd41b0c-60cf-4373-8a2f-a03519341d2c)
- ![image](https://github.com/coronasafe/care_fe/assets/101407963/8afef3c7-ac47-476d-915e-46e21eefa452)

2024-04-23 20:04 UTC, nihal467 commented
@konavivekramakrishna 
![image](https://github.com/coronasafe/care_fe/assets/57055998/7722f9ef-9031-460d-bb63-7b8a6d7efa84)

the badge is missing text in the patient list view

2024-04-24 10:59 UTC, konavivekramakrishna commented
I did't undertood,

can you please specify what text it is missing,

IG everything is working as intended

2024-04-24 12:13 UTC, rithviknishad commented
@nihal467 could you elaborate a bit more? Everything seems fine to me, IP Days are present in the patient list as well as consultation dashboard.

2024-04-24 12:14 UTC, rithviknishad approved these changes

2024-04-29 09:53 UTC, nihal467 commented
@rithviknishad can you push the two minor fix :

![image](https://github.com/coronasafe/care_fe/assets/57055998/0b45b995-7359-45ce-b04a-060da89873a2)

- [ ] add a prefix in the patient list page "IP Days"
- [ ] only show this badge if the patient is having a live consultation

2024-04-29 10:14 UTC, rithviknishad commented
Closing as completed in #7735

2024-04-29 10:14 UTC, closed without merging