Restrict Unauthorized Users from Accessing Facility's Patient Registration
coronasafe/care_fe pull request #7268
Opened 2024-02-24 15:30 UTC by AshrafMd-1

## Proposed Changes

- Fixes #7244 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-02-25 15:18 UTC, AshrafMd-1 commented
@rithviknishad The way I completed it is if you are a doctor it directly searches for the home facility but the problem is that the facility names are not unique so it may become a problem 

One way is directly searching by ID but the backend doesn't have any query related to that

2024-03-01 23:57 UTC, rithviknishad reviewed
Just curious, why would a user who is of type lower than District Admin would want to use "Facility search of home facilities" in the first place when they are going to have only 1 home facility linked to them?

(Correct me if I'm missing something)

2024-03-02 16:01 UTC, AshrafMd-1 commented
@rithviknishad Yeah that's a good point so 

what i will do is 

1. When the user clicks on the Create patient
2. it directly goes to the patient creation page if the user is below district admin

2024-03-03 06:44 UTC, AshrafMd-1 commented
@rithviknishad can u check once

2024-03-16 16:13 UTC, AshrafMd-1 commented
@rithviknishad can u check once

2024-03-17 12:20 UTC, rithviknishad requested changes

2024-03-17 12:20 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +  }, []);
Redirecting on mount doesn't seem to be a nice idea. It'd lead to weird behaviour if user is not allowed to enter the page. If at all user accidentally enters a page that user is not permitted to visit, we should show page not found instead.


Also, are you sure the authzn checks are correct?

2024-03-17 12:20 UTC, rithviknishad commented on src/Components/Patient/ManagePatients.tsx
> +                const showAllFacilityUsers = ["DistrictAdmin", "StateAdmin"];
A state admin has access only to the facility belonging to the users state. 
A district admin has access only to the facility belonging to the users district.

2024-03-19 16:20 UTC, AshrafMd-1 commented
@rithviknishad can u check once

2024-03-29 12:41 UTC, AshrafMd-1 commented
There seem to be some errors so I will reopen a new PR

2024-03-29 12:41 UTC, closed without merging