Log update vital feature remodified
coronasafe/care_fe pull request #7348
Opened 2024-03-06 10:56 UTC by saloni0419

## Proposed Changes
Updated the human-readable value for the pain scale.

- Fixes #7301 

Screenshot of the fix
![image](https://github.com/coronasafe/care_fe/assets/100074110/9d6c57a1-0168-4d97-9a9b-d7bd328ec83d)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers @khavinshankar 

## Merge Checklist

- [ ] removed the appearance of "normal" against 1-4 painscale

2024-03-07 07:12 UTC, khavinshankar requested changes
Just a minor change requiried, removed unwanted params

2024-03-07 07:12 UTC, khavinshankar commented on src/Components/CriticalCareRecording/Pain/CriticalCare__PainInputModal.res
> +let getStatus = (min, minText, max, maxText, val) => {
```suggestion
let getStatus = (val) => {
```

2024-03-07 07:12 UTC, khavinshankar commented on src/Components/CriticalCareRecording/Pain/CriticalCare__PainInputModal.res
> +                    getLabel={getStatus(0.0, "No pain", 5.0, "Unbearable")}
```suggestion
                    getLabel={getStatus}
```

2024-03-08 19:31 UTC, saloni0419 commented
@khavinshankar I have done the changes , please do tell if there is anything more to do

2024-03-12 11:58 UTC, khavinshankar approved these changes

2024-03-12 12:08 UTC, rithviknishad requested changes
1. Conflicting with ideas in https://github.com/coronasafe/care_fe/issues/7378 cc: @skks1212 
2. As per the issue, 0 and 5 only needs to have text. Rest all options does not need a text.
3. Issue not linked to the PR. (Ref: https://github.com/coronasafe/care_fe?tab=readme-ov-file#contributing-to-care)

2024-03-12 12:23 UTC, saloni0419 commented
@rithviknishad These changes were told to me by @khavinshankar . Should I change it or not. Please tell me
https://github.com/coronasafe/care_fe/pull/7301#discussion_r1513172595

2024-03-12 12:55 UTC, skks1212 commented
@saloni0419 It appears new changes were requested in another issue, that were solved in a PR here https://github.com/coronasafe/care_fe/pull/7380, which conflicts with this PR.

Due to this, the current PR will need to be closed : (

Thank you for your contributions!

2024-03-12 12:56 UTC, closed without merging