Fix/comment section stretching
coronasafe/care_fe pull request #7402
Opened 2024-03-13 06:23 UTC by Thanush19

## Proposed Changes

- Fixes #6637
- Resolved Stretching issue of Comment Section
- Added Feature of Read More and Read Less in Comment Section
- Added Multilingual Support to Read More and Read Less in all the supported languages(ml,ma,ta,en,kn)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers
@nihal467  @rithviknishad
## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-03-13 06:53 UTC, rithviknishad requested changes

2024-03-13 06:53 UTC, rithviknishad commented on src/Components/Shifting/CommentsSection.tsx
> +            <button onClick={toggleExpanded} className="ml-2 text-green-600">
Use `primary` colour instead of green

2024-03-13 07:59 UTC, Thanush19 commented
hey @rithviknishad , done with the changes u asked for..

2024-03-19 11:13 UTC, nihal467 commented
@Thanush19 
![image](https://github.com/coronasafe/care_fe/assets/57055998/b01a91ca-02e1-4889-98e0-9cc27e800a65)

the entire alignment is inconsistent in the entire page now

2024-03-30 13:42 UTC, closed without merging