Solved issue "Enhancement to MEWS Score"
coronasafe/care_fe pull request #7438
Opened 2024-03-19 13:13 UTC by r-nikhilkumar

- Fixes #7373 
- Allow calculation of MEWS score by fetching the relevant 5 data points spread across multiple log updates filed within a time frame of 30 min✅
- Add measured at time under the MEWS on Patient dashboard. mention the time stamp of the latest of the 5-parameters✅

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-03-28 05:35 UTC, r-nikhilkumar commented
@rithviknishad, please remove stale label

2024-04-02 16:47 UTC, nihal467 commented
@r-nikhilkumar 
![image](https://github.com/coronasafe/care_fe/assets/57055998/9abb0374-e25c-4fdc-8e2c-a7eff2aeaec0)

the deploy build is failing fix it

2024-04-03 02:50 UTC, r-nikhilkumar commented
@nihal467 first need to merge the backend then the test will be passed

2024-04-03 02:55 UTC, rash-27 commented
@r-nikhilkumar ig the problem is with the typescript errors , see the screenshot attached

2024-04-03 03:06 UTC, r-nikhilkumar commented
@rash-27 yeah, sorry I didn't see ss

2024-04-03 03:06 UTC, rithviknishad commented
@r-nikhilkumar We've recently introduced type-checks at the build step to voluntarily fail the build if there were type errors. This was done to improve code quality and catch potential bugs early on before it even gets merged. Ref: https://github.com/coronasafe/care_fe/pull/7469

It'd be appreciated if you could fix the type errors introduced in this PR.

2024-04-03 03:39 UTC, r-nikhilkumar commented
@nihal467 solved the typeError now you can test it, sorry for inconvenience

2024-04-03 05:15 UTC, rithviknishad requested changes
Proper types needed. Setting to `any` defeats the purpose of enforcing type-safety.

2024-04-03 06:38 UTC, r-nikhilkumar commented
so for that I need to make changes in consultationModel interface and I also need to create an interface for mewFields with all the required attribute, could I make changes in model interface

2024-04-03 12:03 UTC, rithviknishad approved these changes

2024-04-03 12:03 UTC, rithviknishad commented on src/Components/Facility/Consultations/Mews.tsx
> +// import { mewsFieldsModel } from "../../Patient/models";
```suggestion
import { MewsFieldModel } from "../../Patient/models";
```

2024-04-08 11:44 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/bb06c5d2-b088-4c37-b1e0-d0e4a84eedc2)

**Above is PR deployment**

![image](https://github.com/coronasafe/care_fe/assets/57055998/de02abbd-6c37-4e65-b9c9-b38d0f56a8cd)

**Above is the current staging**

@r-nikhilkumar When there is a log update present for a patient, and the MEWS relevant data are missing, the MEWS score should be displayed as "-" Upon hovering over it, the related tooltip should show the missing data and related information. This functionality is currently working properly in the staging environment but is missing in your pull request.

It is a basic functionality of the MEWS score. Therefore, I kindly request you to familiarize yourself with the function first, understand its functionality, make the necessary changes, conduct self QA of the function, and then submit it for review.

2024-04-08 13:58 UTC, r-nikhilkumar commented
@nihal467 it is because I mentioned this
![image](https://github.com/coronasafe/care_fe/assets/91010142/11ff5897-da9c-4f27-9bba-cdbeb7c3b6b2)


in my local its showing the mews field as you shown in staging view, it is not showing in deployed preview might be a reason that from backend mews_field is getting sent as a response field and to get mews_field in response first need to make changes from backend and for the backend changes i raised a pr already once that will be deployed in main server, then the mews_field response will be fetched successfully and the mews score will be show too
![image](https://github.com/coronasafe/care_fe/assets/91010142/73e0decc-0dfe-40b5-ab1c-5cf11f207a32)

2024-04-16 13:03 UTC, nihal467 commented
discussion is going on in the backend repo : https://github.com/coronasafe/care/pull/1991

2024-04-25 17:50 UTC, r-nikhilkumar commented
@rithviknishad what about this pr, is this going to be wasted? no use?😞

2024-05-14 09:57 UTC, nihal467 commented
@r-nikhilkumar closing this PR and unassigning you from this issue due to inactivity, feel free to reopen the same if you are still working on it

2024-08-19 05:48 UTC, r-nikhilkumar commented
@nihal467 is the issue still in progress and not resolved, why you reopened this my PR?🤔

2024-09-06 15:14 UTC, nihal467 commented
@r-nikhilkumar https://github.com/ohcnetwork/care_fe/issues/7373#issuecomment-2296147719 , can you post a reply to this message

2024-09-20 15:52 UTC, closed without merging

2024-09-20 15:52 UTC, bodhish commented
Closing this PR due to lack of recent progress.