Added consent form to patient consultation
coronasafe/care_fe pull request #7461
Opened 2024-03-23 10:23 UTC by skks1212

NOTE: Depends on https://github.com/coronasafe/care/pull/2006

## Proposed Changes

- Fixes #7416 
- Adds Consent form to patient consultation
![image](https://github.com/coronasafe/care_fe/assets/23238460/89c0fe2b-af9e-4032-bca5-59187759f25d)
![image](https://github.com/coronasafe/care_fe/assets/23238460/cd759106-ec7b-46fe-8480-91420d6a7ef0)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-03-27 08:09 UTC, nihal467 commented
@skks1212 
![image](https://github.com/coronasafe/care_fe/assets/57055998/31677bca-1b42-4503-8b19-509b3c31dde2)

unable to upload the consent file in the patient consultation file

2024-03-28 00:35 UTC, Ashesh3 requested changes
- Lint checks are failing 
- Could you exclude changes to vite.config.mts from this pr?

2024-03-28 10:49 UTC, skks1212 commented
@Ashesh3 Fixed the vite issue
For some reason husky just fails on my machine, thus the linting issues. Can you run the lint for me if it fails again 😅

2024-03-28 16:36 UTC, Ashesh3 approved these changes

2024-03-28 16:42 UTC, khavinshankar approved these changes

2024-03-28 16:45 UTC, merged

2024-03-28 16:46 UTC, rithviknishad approved these changes