fixes "Set average weekly working hour" button in user tab is not responsive Fixes #7309
coronasafe/care_fe pull request #7480
Opened 2024-03-27 06:58 UTC by kabirrajsingh

Fixes  #7309
Removed useless classes in parent component and added necessary classes in child component
Screenshots attached

![Screenshot_14](https://github.com/coronasafe/care_fe/assets/24957846/e83daf71-de8e-4dd5-b229-04c7b720db3a)
![Screenshot_13](https://github.com/coronasafe/care_fe/assets/24957846/102257f4-c3b8-432a-9d52-7b2f4de3d4f4)

2024-04-03 12:16 UTC, rithviknishad approved these changes

2024-04-03 12:16 UTC, rithviknishad commented on src/Components/Users/ManageUsers.tsx
> +                        className="flex w-full"
```suggestion
                        className="w-full"
```

2024-04-03 12:16 UTC, rithviknishad commented on src/Components/Users/ManageUsers.tsx
> +                    <div className="">
```suggestion
                    <div>
```

2024-04-03 12:21 UTC, Ashesh3 commented
Deploy is failing

2024-04-04 08:30 UTC, Ashesh3 approved these changes

2024-04-16 13:09 UTC, nihal467 commented
@kabirrajsingh fix the deploy issue

2024-04-21 12:18 UTC, kabirrajsingh commented
@nihal467 it should work now. Apologies for the delay, had exams.

2024-04-23 10:07 UTC, nihal467 commented
@kabirrajsingh 
![image](https://github.com/coronasafe/care_fe/assets/57055998/47127b26-6bff-4057-8a23-5527dfd3cc5c)

it is not fixed yet

2024-05-06 11:01 UTC, rithviknishad requested changes

2024-05-06 11:01 UTC, rithviknishad commented on src/Components/Users/ManageUsers.tsx
> +                        <p className="whitespace-nowrap md:whitespace-normal">
```suggestion
                        <p className="whitespace-normal md:whitespace-nowrap">
```

2024-05-06 11:01 UTC, rithviknishad approved these changes

2024-05-07 06:06 UTC, nihal467 commented
LGTM

2024-05-07 09:02 UTC, khavinshankar approved these changes

2024-05-07 09:03 UTC, merged