Add "needs testing" label if contributor comments "ready for testing"
coronasafe/care_fe pull request #7488
Opened 2024-03-28 15:35 UTC by saloni0419

## Proposed Changes
Adds "needs testing" label if contributor comments "ready for testing" 

- Fixes #7479 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-04-10 03:08 UTC, saloni0419 commented
@rithviknishad @aparnacoronasafe @Ashesh3  please check this pr.

2024-04-10 13:44 UTC, rithviknishad approved these changes

2024-04-16 13:36 UTC, nihal467 commented
Marking it tested as nothing to test from QA side, @khavinshankar review and merge it

2024-04-17 09:51 UTC, khavinshankar approved these changes

2024-04-17 09:56 UTC, khavinshankar requested changes

2024-04-17 09:56 UTC, khavinshankar commented on .github/workflows/auto-testing-label.yml
> +            if ((isReadyForTestingComment && !isDraft) || (!isDraft && pr.draft_changed) || isChangesRequired) {
```suggestion
            if ((isReadyForTestingComment && !isDraft) || (!isDraft && pr.draft_changed)) {
```

should the `need testing` label be added if changes are requested?

2024-04-17 09:56 UTC, khavinshankar commented on .github/workflows/auto-testing-label.yml
> +            if (isChangesRequired) {
Also we could remove `need testing` label when changes are requested, not mandatory but good to have

cc: @nihal467

2024-05-07 09:04 UTC, khavinshankar approved these changes

2024-05-07 09:05 UTC, merged