Scroll2
coronasafe/care_fe pull request #7491
Opened 2024-03-28 19:58 UTC by dwip708

## Proposed Changes

- Fixes #issue_number
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-04-02 03:27 UTC, rithviknishad requested changes

2024-04-02 03:27 UTC, rithviknishad commented on src/Components/Shifting/ShiftingBoard.tsx
> +      style={{ overflowY: "scroll" }}
use tailwindcss classes instead

2024-04-03 09:17 UTC, dwip708 commented on src/Components/Shifting/ShiftingBoard.tsx
> +      style={{ overflowY: "scroll" }}
> use tailwindcss classes instead

Okk I'll do that.

2024-04-23 09:39 UTC, nihal467 commented
@dwip708 what is the status on this PR

2024-04-24 02:59 UTC, dwip708 commented
> @dwip708 what is the status on this PR

As I said the main scroll issue is fixed but there is a pagination issue, and as a result only 14 records at max is shown under each card in shifting. I am working on that and will solve it by this weekend.

2024-05-14 09:58 UTC, nihal467 commented
@dwip708 closing this PR and unassigning you from this issue due to inactivity, feel free to reopen the same if you are still working on it

2024-05-14 09:58 UTC, closed without merging