"Solved facility linking issue under manage facilities/view users"#7474
coronasafe/care_fe pull request #7494
Opened 2024-03-29 11:01 UTC by Sulochan-khadka

## Proposed Changes

- Fixes #i7474
- Added linked facilities slider modal 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-03-29 15:42 UTC, rithviknishad requested changes

2024-03-29 15:42 UTC, rithviknishad commented on src/Components/Facility/FacilityUsers.tsx
>    const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
These and other unrelated code can be removed now right?

2024-03-29 17:31 UTC, Sulochan-khadka commented on src/Components/Facility/FacilityUsers.tsx
>    const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
Are they unrelated? What if the user by mistake linked wrong facility and then wants to unlink it and link different facility?

2024-03-30 03:44 UTC, rithviknishad commented on src/Components/Facility/FacilityUsers.tsx
>    const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
The Facility Slideover takes care of unlinking too right? Correct me if I'm wrong

2024-03-30 04:02 UTC, Sulochan-khadka commented on src/Components/Facility/FacilityUsers.tsx
>    const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
Yes...

2024-03-30 09:10 UTC, mridulsaggi commented
please assign me this issue as i am willing to work on this.

2024-03-30 10:28 UTC, Sulochan-khadka commented
> please assign me this issue as i am willing to work on this.

Hey mate, sadly this is a PR and not an issue, therefore if you want to solve an issue, kindly explore the issue tab.

2024-03-31 19:01 UTC, Sulochan-khadka commented on src/Components/Facility/FacilityUsers.tsx
>    const [isLoadFacilityLoading, setIsLoadFacilityLoading] = useState(false);
Therefore do I need to remove them to get merged?

2024-04-11 07:35 UTC, Sulochan-khadka commented
@rithviknishad let me know the way out for this PR to get merged. Thankyou

2024-04-13 03:49 UTC, rithviknishad commented
> @rithviknishad let me know the way out for this PR to get merged. Thankyou

Could you resolve the merge conflicts?

2024-04-13 07:58 UTC, Sulochan-khadka commented
> > @rithviknishad let me know the way out for this PR to get merged. Thankyou
> 
> Could you resolve the merge conflicts?

I will do it right away...

2024-04-13 08:00 UTC, Sulochan-khadka commented
> > @rithviknishad let me know the way out for this PR to get merged. Thankyou
> 
> Could you resolve the merge conflicts?

Done...

2024-04-13 09:40 UTC, Sulochan-khadka commented
@rithviknishad , I also solved a minor error that was causing the deployment to fail. You may have a look.

2024-04-15 13:32 UTC, khavinshankar reviewed
changes look good, just resolve the linting issues and remove the comments used for todo reminders

2024-04-15 16:18 UTC, nihal467 commented
@Sulochan-khadka make the necessary changes

2024-04-15 18:14 UTC, Sulochan-khadka commented
@nihal467 @khavinshankar have fixed almost all lint errors... Well I did not find one lint error the workflow was indicating at... replacing `...` with '....' , when there is no such statement . Do let me know immediately if unknowingly I messed up something. Also have just commented out showFacilites since it might be of use in future.

2024-04-16 06:36 UTC, rithviknishad approved these changes

2024-04-16 06:57 UTC, nihal467 commented
LGTM

2024-04-16 07:01 UTC, khavinshankar approved these changes

2024-04-16 07:01 UTC, merged