[Enhancement] Ventilator Parameters Input - Validate Consultation Bed for Linked Ventilator Asset is getting resolved
coronasafe/care_fe pull request #7522
Opened 2024-04-02 03:27 UTC by manasvi-gaur

- Fixes #7397 
is in progress

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-04-16 06:59 UTC, rithviknishad requested changes

2024-04-16 06:59 UTC, rithviknishad commented on src/Components/CriticalCareRecording/CriticalCare__API.tsx
> +  }).then((result) => {
Pass a `limit` of 1 if only the latest (first) consultation bed record is only required.

2024-04-16 06:59 UTC, rithviknishad commented on src/Components/CriticalCareRecording/CriticalCare__API.tsx
> +  }).then((result) => {
```suggestion
  }).then(({ data }) => {
```

2024-04-18 15:52 UTC, manasvi-gaur commented
@rithviknishad I have made relevant changes, kindly review the PR

2024-04-19 03:27 UTC, rithviknishad approved these changes

2024-04-24 04:35 UTC, Ashesh3 approved these changes

2024-04-24 14:09 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/ae4fea4f-41c0-4dcd-8932-81a052006d85)
![image](https://github.com/coronasafe/care_fe/assets/57055998/f2ce2f77-17b3-4492-a7db-091691b8435c)

@manasvi-gaur The issue remains unresolved; the validation check isn't functioning properly. I created a ventilator-related parameter input for a patient without a ventilator asset linked to their bed, yet no notification was triggered.

2024-05-11 14:59 UTC, manasvi-gaur commented
@nihal467 @rithviknishad, but in my setup its working perfectly without an asset, we can't create a log of critical type with ventilator parameter its showing alert window with functionality to add assets

![image](https://github.com/coronasafe/care_fe/assets/120303997/a7a669b2-b14e-42dd-b482-c53f9101e4c9)

here its notifying to add assets before proceeding while adding ventilator parameter
![image](https://github.com/coronasafe/care_fe/assets/120303997/449bc4b9-7eef-44c3-b6bc-0accd304027d)

2024-05-13 04:49 UTC, rithviknishad commented
@manasvi-gaur I was able to replicate the issue.

If we submit by editing only the following fields shown in the screenshot, we are able to submit the form without linking a ventilator.

It does works only for changes in fields under the Respiratory Support subtitle. 

<img width="758" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/e60c533d-3e10-45c8-a65d-e99cd38801f4">


cc: @nihal467

2024-05-15 09:59 UTC, manasvi-gaur commented
@nihal467 @rithviknishad done, I have made all relevant changes but for that single condition that was failing, due to my examination I was unable to fix that earlier, sorry for inconvenience

2024-05-28 06:57 UTC, nihal467 commented
LGTM

2024-05-28 10:46 UTC, rithviknishad approved these changes

2024-05-28 11:12 UTC, khavinshankar approved these changes

2024-05-28 11:13 UTC, merged