Occupation dropdown frontend
coronasafe/care_fe pull request #7541
Opened 2024-04-04 18:14 UTC by hrit2773

## Proposed Changes

- Fixes #7516 
- Changed the dropdown options
- Changed the form field component to auto complete form field

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-04-05 04:52 UTC, rithviknishad requested changes

2024-04-05 04:52 UTC, rithviknishad commented on src/Components/Form/FormFields/Autocomplete.tsx
> +export const AutocompleteFormField = <T, V>(
```suggestion
const AutocompleteFormField = <T, V>(
```

Why was this exported this way?

It is already exported as default.

2024-04-05 04:52 UTC, rithviknishad commented on src/Components/Patient/PatientRegister.tsx
> +import { AutocompleteFormField } from "../Form/FormFields/Autocomplete.js";
```suggestion
import AutocompleteFormField from "../Form/FormFields/Autocomplete.js";
```

2024-04-05 05:02 UTC, hrit2773 commented
@rithviknishad yes yes I didn't notice that it was already exported...

2024-04-05 05:06 UTC, rithviknishad approved these changes

2024-04-05 05:08 UTC, hrit2773 commented
@rithviknishad I made the backend PR also check the link in the issues

2024-04-05 05:10 UTC, rithviknishad commented
https://github.com/coronasafe/care/pull/2055#pullrequestreview-1981862720

2024-04-08 12:09 UTC, nihal467 commented
@hrit2773 we are having a cypress test failure, fix it

Navigate to the "patient_spec" folder, then locate the "patient_registration.cy.ts" file. In this file, update the Occupation selection component. Currently, it uses "cy.clickAndSelectOption". Change this to reuse the "cy.searchAndSelectOption" function as you change the occupation component from a select form field to an autocomplete form field.

2024-04-16 08:29 UTC, hrit2773 commented
https://github.com/coronasafe/care/pull/2055#pullrequestreview-1981862720 @rithviknishad @sainak can you review the backend PR also

2024-04-16 22:06 UTC, nihal467 commented
backend migration is failing

2024-04-18 07:11 UTC, rithviknishad commented
@nihal467 the migration seems to be passing. Could you show the logs?

2024-04-18 07:19 UTC, hrit2773 commented
@rithviknishad maybe due to conflicting migrations after updating the branch the dependencies changed that's why maybe there was an issue anyways I deleted and re ran the migrations and pushed the code and that's why it seems to be passing. @nihal467 can you check again

2024-04-23 18:38 UTC, nihal467 approved these changes

2024-04-23 18:40 UTC, nihal467 commented
LGTM

2024-04-24 07:18 UTC, khavinshankar approved these changes

2024-04-24 07:18 UTC, merged