fix: Auto-close country codes dropdown when clicking outside the component
coronasafe/care_fe pull request #7561
Opened 2024-04-07 06:34 UTC by UdaySagar-Git

## Proposed Changes

- Fixes #7557  

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-04-08 21:34 UTC, nihal467 commented
LGTM

2024-04-09 09:12 UTC, khavinshankar commented on src/Components/Form/FormFields/PhoneNumberFormField.tsx
> +
why not separate this into its own hook, make it as a reusable hook.

2024-04-09 09:13 UTC, khavinshankar requested changes
just a small refactor required

2024-04-09 10:20 UTC, UdaySagar-Git commented on src/Components/Form/FormFields/PhoneNumberFormField.tsx
> +
sure

2024-04-10 14:40 UTC, rithviknishad requested changes
Would it be possible to use one of the headlessui component to handle the dropdown/popover? So that we won't need a custom hook to handle click outside to begin with?

2024-04-10 14:56 UTC, UdaySagar-Git commented
> Would it be possible to use one of the headlessui component to handle the dropdown/popover? So that we won't need a custom hook to handle click outside to begin with?

will give it a try

2024-04-19 03:18 UTC, rithviknishad requested changes
You can use the `close` method provided by headlessui to avoid hacks and using an additional useState.

<img width="906" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8a94b22b-3e1a-41c7-a6b8-1b61067f668c">

https://headlessui.com/react/popover#closing-popovers-manually

2024-04-19 03:18 UTC, rithviknishad commented on src/Components/Form/FormFields/PhoneNumberFormField.tsx
> +            }, [open]);
```suggestion
```

2024-04-19 03:18 UTC, rithviknishad commented on src/Components/Form/FormFields/PhoneNumberFormField.tsx
> +  const [isOpen, setIsOpen] = useState(false);
```suggestion
```

2024-04-19 03:18 UTC, rithviknishad commented on src/Components/Form/FormFields/PhoneNumberFormField.tsx
> +                  </Popover.Panel>
needs to be modified as mentioned.

2024-04-19 08:58 UTC, rithviknishad approved these changes

2024-04-23 18:37 UTC, nihal467 commented
LGTM

2024-04-24 04:34 UTC, Ashesh3 approved these changes

2024-04-24 06:46 UTC, khavinshankar approved these changes

2024-04-24 06:46 UTC, merged