Fix Incorrect error message for invalid QR code
coronasafe/care_fe pull request #7588
Opened 2024-04-11 20:14 UTC by AnkurPrabhu

## Proposed Changes

- Fixes #7571 
- not calling the backend api when the QR code is invalid 
-  stop infinite loading screen when the QR code  is invalid 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

SS:
<img width="1200" alt="Screenshot 2024-04-12 at 1 36 44 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/48c10a55-2e80-4ff3-9285-27dbff3ce8fa">

2024-04-15 09:29 UTC, bodhish requested changes

2024-04-15 09:29 UTC, bodhish commented on src/Components/Assets/AssetsList.tsx
> +    Notification.Error({ msg: "Invalid Asset Id" });
Lets make the message more friendly; 

Example 
> Oops! The asset ID you entered does not appear to be valid.

Also lets keep all strings in I18n

2024-04-17 14:17 UTC, AnkurPrabhu commented
@bodhish i have upadated the pr also. these other changes in file are not because of my changes they are related to commits which were merged

2024-04-21 16:37 UTC, rithviknishad requested changes
strings not present in i18n files.

2024-04-21 16:37 UTC, rithviknishad commented
Refer: https://github.com/coronasafe/care_fe/issues/4467

2024-05-04 11:19 UTC, rithviknishad approved these changes

2024-05-07 06:17 UTC, nihal467 commented
@AnkurPrabhu clear the merge conflict

CC: @rithviknishad

2024-05-19 14:07 UTC, AnkurPrabhu commented
@nihal467 i have resolved the conflict

2024-05-22 11:21 UTC, nihal467 commented
@AnkurPrabhu remove the additional "something went wrong...!" error message , when we scan invalid QR

![image](https://github.com/coronasafe/care_fe/assets/57055998/a85ffcdc-75bc-4231-a3ed-116ec4cb78ac)

2024-05-22 14:09 UTC, AnkurPrabhu commented
@rithviknishad can you tell me if my approach is correct ?

2024-07-31 03:22 UTC, rithviknishad approved these changes

2024-07-31 13:37 UTC, nihal467 commented
LGTM @khavinshankar can you resolve the merge conflict and merge it

2024-07-31 13:57 UTC, khavinshankar approved these changes

2024-08-01 07:48 UTC, nihal467 commented
LGTM

2024-08-01 08:58 UTC, merged