[FIXED] Able to Change the Values using Upward and Downward arrow
coronasafe/care_fe pull request #7592
Opened 2024-04-13 11:16 UTC by manasvi-gaur

- Fixes #7572 
- Now able to Change the Values using Upward and Downward arrow
<img width="849" alt="image" src="https://github.com/coronasafe/care_fe/assets/120303997/a05ea400-229f-4bee-a485-061a47dd7214">

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-04-15 09:00 UTC, bodhish requested changes
Lets also make sure that the buttons looks good in mobile;

2024-04-15 09:00 UTC, bodhish commented on src/Components/Facility/FacilityCreate.tsx
> +  return <p className="mr-1 text-xs text-gray-700">{unit}</p>;
```suggestion
  return <p className="text-xs text-gray-700">{unit}</p>;
```

2024-04-15 09:00 UTC, bodhish commented on src/Components/Form/FormFields/TextFormField.tsx
> +        <div className="absolute inset-y-0 right-7 flex items-center pr-3">
```suggestion
        <div className="absolute inset-y-0 right-0 md:right-6 flex items-center pr-3">
```

2024-04-15 09:00 UTC, bodhish commented on src/Components/Form/FormFields/TextFormField.tsx
> +          <div className="absolute inset-y-0 right-7 flex translate-y-0 items-center pr-3 opacity-100 transition-all delay-300 duration-500 ease-in-out peer-focus:translate-y-1 peer-focus:opacity-0">
```suggestion
          <div className="absolute inset-y-0 right-0 md:right-6 flex translate-y-0 items-center pr-3 opacity-100 transition-all delay-300 duration-500 ease-in-out peer-focus:translate-y-1 peer-focus:opacity-0">
```

2024-04-15 09:00 UTC, bodhish commented on src/Components/Form/FormFields/TextFormField.tsx
> +          <div className="absolute inset-y-0 right-7 flex -translate-y-1 items-center pr-3 opacity-0 transition-all delay-300 duration-500 ease-in-out peer-focus:translate-y-0 peer-focus:opacity-100"
```suggestion
          <div className="absolute inset-y-0 right-0 md:right-6 flex -translate-y-1 items-center pr-3 opacity-0 transition-all delay-300 duration-500 ease-in-out peer-focus:translate-y-0 peer-focus:opacity-100">
```

2024-04-16 06:43 UTC, manasvi-gaur commented
@bodhish done

2024-04-23 19:28 UTC, nihal467 commented
@manasvi-gaur 
![image](https://github.com/coronasafe/care_fe/assets/57055998/4273b768-8436-4477-bf95-adac7da58aab)

in the mobile view, the arrow is not visible anymore

2024-05-09 04:18 UTC, closed without merging