Add Sorting filter on Discharged Patients page
coronasafe/care_fe pull request #7594
Opened 2024-04-14 09:37 UTC by Pranshu1902

## Proposed Changes

- Fixes #issue_number
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-04-18 06:45 UTC, rithviknishad requested changes

2024-04-18 06:45 UTC, rithviknishad commented on src/Components/Facility/DischargedPatientsList.tsx
> +  }, []);
```suggestion
```

2024-04-18 06:45 UTC, rithviknishad commented on src/Components/Facility/DischargedPatientsList.tsx
> +        query={qParams}
```suggestion
        query={{ordering: "-modified_date", ...qParams}}
```

2024-04-18 11:00 UTC, rithviknishad approved these changes

2024-04-24 04:33 UTC, Ashesh3 approved these changes

2024-04-24 05:46 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/4af6425a-3b9e-4605-893a-dff36e81d510)

- [ ] keep sort by and live discharge switching button right aligned
- [ ] swap the places in between the button

2024-04-24 08:21 UTC, Pranshu1902 commented
@nihal467 Updated view:
![image](https://github.com/coronasafe/care_fe/assets/70687348/6e959986-4c5b-4c6a-b787-17faf17b5148)

2024-04-24 14:11 UTC, nihal467 commented
LGTM

2024-04-24 14:15 UTC, khavinshankar approved these changes

2024-04-24 14:16 UTC, merged