update area of specialisation of doctor
coronasafe/care_fe pull request #7664
Opened 2024-04-19 16:33 UTC by rash-27

## Proposed Changes

- Fixes #7612 
- Linked backend pr https://github.com/coronasafe/care/pull/2102
- [x] Facility dashboard (https://github.com/coronasafe/care_fe/issues/7616) change "Doctor List" to "Staff Capacity"
- [x] Change the text on the button for "Add doctor type" to "Add Staff type"
- [x] edit the pop-up window. title to be "Add staff capacity"
- [x] "area of specialisation" to be changed to "Staff type"
- [x] the dropdown for area of specialisation to be synced with the list of skills available on user module + Others+ Nurse.
- [x] the existing data to be mapped as "Critical care"= "Intensivist", "pediatric"="Pediatrician". "other speciality"="Others"

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-04-19 17:03 UTC, rash-27 commented
@nihal467 @aparnacoronasafe In this issue, we are synchronising the doctor types with available skills and using staff capacity instead of the doctor's list in the facility dashboard. I feel like we can completely go with the staff capacity in the facility dashboard and make corresponding changes to shift from displaying doctors to staff.The changes include 
- [ ] Changing the route names that we are using currently using to fetch staff details (`/api/v1/facility/{facilityId}/hospital_doctor/` and `/api/v1/facility/{facilityId}/hospital_doctor/{id}/`) for more readability 
- [ ] And also making changes in the frontend like, the notifications currently are displaying "Doctor count added successfully" and we can change them to "Staff count added successfully" and etc. 
- [ ] And also in frontend code can we change the variable names accordingly for more readability of the code as currently we are displaying the Staff details in facility dashboard instead of doctors details ?
 What do you think?

2024-05-14 18:23 UTC, nihal467 commented
@rash-27 any update on this PR

2024-05-15 04:43 UTC, nihal467 commented
@rithviknishad can you update the following bugs

2024-05-15 04:44 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/8aac4b23-3048-4828-9b56-2afb39ce55d5)

- [ ] change all doctor related text to staff related text in the facility create work flow

2024-05-15 04:46 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/b93d7765-8b3e-48d9-b029-dac5e052ab50)

- [ ] modify the delete pop-up text and relate notification

2024-05-15 04:48 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/94c6f458-bd59-43aa-a821-1a4181e27387)

- [ ] update the existing data modify

2024-05-15 04:50 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/43ff0b95-a42e-4cb8-8188-1401695b0284)

- [ ] change it to total staff count

2024-05-15 05:49 UTC, nihal467 requested changes

2024-05-15 05:49 UTC, nihal467 commented on src/Common/constants.tsx
> +  { id: 1, text: "General Medicine Doctors", desc: "bg-doctors-general" },
```suggestion
  { id: 1, text: "General Medicine", desc: "bg-doctors-general" },
```

2024-05-15 05:49 UTC, nihal467 commented on src/Common/constants.tsx
> +  { id: 2, text: "Pulmonology Doctors", desc: "bg-doctors-general" },
```suggestion
  { id: 2, text: "Pulmonology", desc: "bg-doctors-general" },
```

2024-05-15 06:18 UTC, nihal467 commented
LGTM

2024-05-15 06:30 UTC, rithviknishad approved these changes

2024-05-15 06:32 UTC, khavinshankar approved these changes

2024-05-15 06:34 UTC, nihal467 approved these changes

2024-05-15 06:35 UTC, merged