Allow only admins to delete a location or a bed
coronasafe/care_fe pull request #7671
Opened 2024-04-20 19:51 UTC by AnkurPrabhu

## Proposed Changes

- Fixes #7601
- we check if the user is "DistrictAdmin" or "StateAdmin" or is a super user if the condition does not match we disable the 
    button 
- made respective changes in `LocationManagement.tsx`
- made respective changes `BedManagement.tsx`

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

Screenshots:
`BedManagement.tsx`
<img width="299" alt="Screenshot 2024-04-21 at 1 12 21 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/7b95b7d1-025f-4b65-b0f1-754fb332bd6e">

`LocationManagement.tsx`
<img width="875" alt="Screenshot 2024-04-21 at 1 13 16 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/5819aa63-a073-4067-85d5-4d2864c8dd6a">

2024-04-23 20:14 UTC, nihal467 commented
@AnkurPrabhu 
![image](https://github.com/coronasafe/care_fe/assets/57055998/5943adf2-3be4-40d0-a03d-f7efe475280b)

the tooltip is clipping-in in the mobile view

2024-05-04 16:49 UTC, rithviknishad requested changes

2024-05-04 16:49 UTC, rithviknishad commented on src/Components/Facility/BedManagement.tsx
> +    authUser.is_superuser;
need not do super user checks explicitly as all super users are state admins.

2024-05-04 16:49 UTC, rithviknishad commented on src/Components/Facility/BedManagement.tsx
> +            disabled={!allowedUser || isOccupied}
instead of doing that, make use of the `authorizeFor` prop.

2024-05-19 14:50 UTC, AnkurPrabhu commented
@rithviknishad ptal

2024-05-19 17:20 UTC, rithviknishad approved these changes

2024-05-21 09:58 UTC, nihal467 commented
LGTM

2024-05-22 04:37 UTC, khavinshankar approved these changes

2024-05-22 04:37 UTC, merged