Frontend Adjustments for ABDM Plug Conversion
coronasafe/care_fe pull request #7817
Opened 2024-05-14 11:58 UTC by khavinshankar

This pull request introduces necessary frontend changes to accommodate the backend conversion of ABDM into a plug.

Depends on: https://github.com/coronasafe/care/pull/2161

2024-06-14 12:23 UTC, nihal467 commented
@khavinshankar testing is kept on hold for this PR, due to the ABDM sandbox mobile app crashing. Once the service is back online, ping me, we will get it tested ASAP

2024-07-02 11:41 UTC, nihal467 commented
@khavinshankar 

![image](https://github.com/coronasafe/care_fe/assets/57055998/5060de63-7230-4e0e-88d3-37c1d16d30f4)

the consent patient Abha ID is not verifying, and the push notifications are not being triggered in the applications, of chrome

2024-07-02 14:36 UTC, skks1212 requested changes

2024-07-02 14:36 UTC, skks1212 commented on netlify.toml
> -to = "https://careapi.ohc.network/api/:splat"
i think this change was unintentional

2024-07-03 12:38 UTC, nihal467 commented
@khavinshankar 
![image](https://github.com/coronasafe/care_fe/assets/57055998/53c760ea-68a3-40a0-998a-8af976d7d3ea)

the consent api is failing, can you check it

2024-07-07 16:41 UTC, nihal467 commented
@khavinshankar can you fix the cypress failure

2024-07-08 07:45 UTC, nihal467 commented
LGTM

2024-07-15 07:34 UTC, skks1212 approved these changes

2024-07-15 07:36 UTC, rithviknishad approved these changes

2024-08-23 06:22 UTC, khavinshankar commented
Closing this PR in favor of #8340

2024-09-17 01:54 UTC, merged