fixes: Renaming patient categorisation #7811
coronasafe/care_fe pull request #7820
Opened 2024-05-14 20:09 UTC by Sulochan-khadka

## Proposed Changes

- Fixes #issue_number
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-05-15 14:48 UTC, Sulochan-khadka commented
@rithviknishad could you review this?

2024-05-17 11:58 UTC, rithviknishad requested changes

2024-05-17 11:58 UTC, rithviknishad commented on src/Common/constants.tsx
> +  { id: "Moderate", text: "Moderate", twClass: "patient-moderate" },
You need not change the ID' and tailwind classess. You can just change the labels (text)

2024-05-17 11:58 UTC, rithviknishad commented on src/Common/constants.tsx
> +  { value: 2, text: "Moderate Extension(decerebrate)" },
Why was this changed? Totally unrelated to patient category.

2024-05-17 11:58 UTC, rithviknishad commented on src/Components/Patient/ManagePatients.tsx
> +  Moderate: "MODERATE",
Keys need not be changed. Just display text needs to be changed

2024-05-17 11:58 UTC, rithviknishad commented on src/Components/Patient/PatientCategorySelect.tsx
> +                Mild: "bg-patient-stable",
same here too

2024-05-22 08:37 UTC, rithviknishad commented
Closing as completed in https://github.com/coronasafe/care_fe/commit/1554ef2fc6af55333199140659468e894b220dda

2024-05-22 08:37 UTC, closed without merging