fixes: Prescriptions: Default Discontinued Prescriptions Collapsed #7767
coronasafe/care_fe pull request #7833
Opened 2024-05-16 15:47 UTC by Sulochan-khadka

## Proposed Changes

- Fixes #7767 
- Added an attribute to the component

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-05-16 15:58 UTC, rithviknishad requested changes
Nice work, however there is one problem. For active prescriptions, if we click on one of the buttons (administer/discontinue), the shrinked state of the card also changes. This is not expected behaviour.

2024-05-16 15:58 UTC, rithviknishad commented on src/Components/Medicine/PrescriptionDetailCard.tsx
> +      <div className="flex flex-1 flex-col" onClick={handleShow}>
The user should know that the element is clickable.

```suggestion
      <div className="flex flex-1 flex-col cursor-pointer" onClick={handleShow}>
```

2024-05-16 15:59 UTC, rithviknishad commented
@Sulochan-khadka you might also want to update the cypress tests are related test is failing.

2024-05-16 16:01 UTC, rithviknishad commented on src/Components/Medicine/PrescriptionDetailCard.tsx
> +      <div className="flex flex-1 flex-col" onClick={handleShow}>
Also, can we add animations on hover for the card since it's a clickable element?

2024-05-16 16:02 UTC, rithviknishad requested changes
Let's not collapse or make it collapsible where this component is used in other places.

<img width="1486" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/b744ee1a-8308-488e-a438-a544f0bc6835">

2024-05-16 16:04 UTC, rithviknishad commented
<img width="974" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/996b4a2f-4d23-4057-b909-326d1bf79713">

2024-05-17 12:15 UTC, rithviknishad approved these changes

2024-05-23 08:36 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/812e2cff-1944-42b7-bc70-07ab324c9ee1)

@Sulochan-khadka newly added active medicine is getting by-default collapsed state, which is not expected, only discontinued medicine should be in collapsed state bydefault.

Steps to replicate 

1. Create a new medicine and manually collapse it
2. then create two more medicines.
3. Then you will be seeing except the latest added medicine, all other ones are collapsed

2024-05-28 05:09 UTC, nihal467 commented
LGTM

2024-05-28 05:10 UTC, nihal467 commented
@rithviknishad create a new PR to sort the prescription table to show live medicine on the top

2024-05-28 05:59 UTC, khavinshankar approved these changes

2024-05-28 05:59 UTC, merged