Show standardized labels for patient categorization
coronasafe/care_fe pull request #7875
Opened 2024-05-21 12:39 UTC by khavinshankar

- Fixes https://github.com/coronasafe/care_fe/issues/7811
- Show standardized labels for patient categorization

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

2024-05-21 12:44 UTC, rithviknishad requested changes

2024-05-21 12:44 UTC, rithviknishad commented on src/Components/Patient/ManagePatients.tsx
> +              {category ? category.toUpperCase() : "UNKNOWN"}
`uppercase` tailwind class is already applied to the element.

```suggestion
              {category || "UNKNOWN"}
```

2024-05-21 12:49 UTC, rithviknishad approved these changes

2024-05-21 14:03 UTC, nihal467 commented
@khavinshankar events log is not working

2024-05-22 08:29 UTC, gigincg approved these changes

2024-05-22 08:32 UTC, merged