Separate page for patient consent records
coronasafe/care_fe pull request #7882
Opened 2024-05-22 13:16 UTC by skks1212

## Proposed Changes

- Fixes #7812

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-05-22 13:58 UTC, nihal467 commented on src/Components/Patient/PatientInfoCard.tsx
> +                    "Edit Consent Records",
```suggestion
                    "Consent Records",
```

as per issue

2024-05-22 15:11 UTC, aparnacoronasafe commented
Issues noted:

1- when "patient code status for a patient is updated for the first time (within an encounter), this pop-up window need not come up
![image](https://github.com/coronasafe/care_fe/assets/67050716/f911558a-36ec-4f7f-88c0-16cd97ee74f0)

2- when I type file name before selecting file, the name of the file I select replaces the file name I typed. This shouldn't happen. Only when the file name field is empty should the name of file uploaded come up there

3- when I uploaded patient code for the first time "permission denied" error came up alongside success message. The first workflow was good, but the error message is misplaced 

4- small alignment issue view button on mobile screen
![image](https://github.com/coronasafe/care_fe/assets/67050716/15efe044-e989-42e5-9f4c-1ac75963fd66)

5- I first filed a patient code status DNH. Then I filed one for active treatment. The heading - patient code status continued to show DNH. When I tried to update the patient code status the pop up window also said I am changing it from DNH (it should have been active treatment since that is the latest code status)
![image](https://github.com/coronasafe/care_fe/assets/67050716/15248c27-e2fc-4642-9561-bb1f759b6053)

2024-05-22 15:24 UTC, khavinshankar commented
@skks1212 can you make the above recommended changes

cc: @nihal467

2024-05-22 20:46 UTC, skks1212 commented
@aparnacoronasafe changes have been made.
I have replaced "delete" with archive. This will allow you to see archived consultations in the new tab.

I could not add the "nurse changed x" logs as that would require a backend PR. If the current solution does not work, then I will make that.

2024-05-23 06:44 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/ab998e9e-928a-4cb3-9e49-c16b014d209e)

- [ ] when we want to archive something, we archive the entire section, i would keep it as file level, @aparnacoronasafe can you confirm this behavior is ok for production release

2024-05-23 13:55 UTC, skks1212 commented
@nihal467 changes made

2024-05-24 05:43 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/c09a6f87-8b21-4967-9d85-55a1f306d5c9)

- [ ] keep only individual file level archive only

![image](https://github.com/coronasafe/care_fe/assets/57055998/6ffec17d-5160-4f3f-923c-7023e8e2a7e1)

- [ ] can we keep the file preview ( Left side ) and file upload component (Right side) into same level , expected behavior screenshot is attached in the bottom

![image](https://github.com/coronasafe/care_fe/assets/57055998/a3ac13cc-75e3-4f8f-b6a8-9c69895fb85f)

2024-05-24 05:55 UTC, nihal467 requested changes
make the minor changes in the comment

2024-05-24 13:48 UTC, nihal467 commented
@skks1212 
![image](https://github.com/coronasafe/care_fe/assets/57055998/dfa613c8-a4c3-4894-b1bb-c72b6304cdc4)

when i click on the consent record, the bed pop-up is triggered, it is not a necessary to have a bed for this

2024-05-24 14:12 UTC, rithviknishad approved these changes
LGTM

2024-05-24 15:12 UTC, nihal467 commented
![image](https://github.com/coronasafe/care_fe/assets/57055998/ca176787-4d16-4a0e-a3d6-0560dc4faa99)



- [ ] once the file is archived, make the button similar to file upload

![image](https://github.com/coronasafe/care_fe/assets/57055998/33511476-93de-4aee-ad58-b8143707d02b)

2024-05-24 17:58 UTC, khavinshankar commented
- [x] No records found
![image](https://github.com/coronasafe/care_fe/assets/29787772/4203518b-e00a-4361-ad67-3a7276b1b487)
- [x] Hide Archive button for non-admin users (except for the original user who uploaded it)
![image](https://github.com/coronasafe/care_fe/assets/29787772/cad8e05e-84c7-4098-8ee9-e5e177df0b3a)

2024-05-24 18:10 UTC, nihal467 commented
Approved due to priority, enhancement issue will be opened after merging

2024-05-24 18:10 UTC, nihal467 approved these changes

2024-05-24 18:10 UTC, khavinshankar approved these changes

2024-05-24 18:11 UTC, merged