New profile picture feature
coronasafe/care_fe pull request #7995
Opened 2024-06-07 07:08 UTC by UdaySagar-Git

## Proposed Changes

- Fixes #3924 

backend pr : https://github.com/coronasafe/care/pull/2253

<img width="1469" alt="Screenshot 2024-06-07 at 12 37 12 PM" src="https://github.com/coronasafe/care_fe/assets/111575806/6d89d602-3729-41cc-b26a-5c1d160a69d6">
https://github.com/coronasafe/care/pull/2253
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-06-22 18:25 UTC, UdaySagar-Git commented
@rithviknishad can you please remove stale label

2024-06-26 12:28 UTC, nihal467 commented
@khavinshankar can you review it once

2024-06-26 12:47 UTC, khavinshankar requested changes
Hi @UdaySagar-Git, mostly looks good, just some minor refactors

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Common/Sidebar/SidebarUserCard.tsx
> +          }`}
use classNames util which will be easier to read

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  const [facingMode, setFacingMode] = useState<any>(FACING_MODE_USER);
avoid using any as much as possible

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  onDelete?: (() => void) | undefined;
```suggestion
  onClose?: () => void);
  onSave?: () => void);
  onDelete?: () => void;
```

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  };
keep constants that are not dependent on component state or props outside the component

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +    await sleep(1000);
why are we adding this here?

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  const [isCaptureImgBeingUploaded, setIsCaptureImgBeingUploaded] =
what is the difference b/w isUploading and isCaptureImgBeingUploaded states, is it possible to combine these states?

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +    onSave && onSave();
```suggestion
    onSave?.();
```

2024-06-26 12:47 UTC, khavinshankar commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  user,
Can't we directly get the user from context, is there any benefit passing it as props

2024-06-27 15:57 UTC, UdaySagar-Git commented on src/Components/Users/ProfilePicUploadModal.tsx
> +    await sleep(1000);
Fixed, just a hack to prevent the modal from closing immediately while it is uploading.

2024-06-27 15:58 UTC, UdaySagar-Git commented on src/Components/Users/ProfilePicUploadModal.tsx
> +  const [isCaptureImgBeingUploaded, setIsCaptureImgBeingUploaded] =
we can merge those 2

2024-06-27 16:00 UTC, UdaySagar-Git commented
@khavinshankar made changes accordingly. Can you review it once?

2024-06-28 03:25 UTC, rithviknishad commented on src/Components/Common/Sidebar/SidebarUserCard.tsx
> +            "mb-3 h-10 w-10 rounded-full object-cover",
```suggestion
            "mb-3 size-10 rounded-full object-cover",
```

2024-06-28 03:25 UTC, rithviknishad commented on src/Components/Users/UserProfile.tsx
> +                    className="h-24 w-24 rounded-lg object-cover"
```suggestion
                    className="size-24 rounded-lg object-cover"
```

2024-07-03 17:13 UTC, UdaySagar-Git commented
ready for testing

2024-07-04 07:48 UTC, UdaySagar-Git commented
ready for testing

2024-07-05 12:07 UTC, rithviknishad approved these changes

2024-07-08 08:43 UTC, nihal467 commented
@UdaySagar-Git follow-up on the ongoing discussion on your related backend PR

2024-07-08 09:44 UTC, UdaySagar-Git commented
@nihal467 waiting for someone's reply

2024-08-07 07:10 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/bd35c384-f379-4e33-9ea1-80eec197c361)

- [ ] we need to manually reload the entire page, to view the uploaded profile, once the upload is successful. it shouldn't be the behavior, once the upload is complete, we should be able to see the profile picture without manual reload

2024-08-07 07:11 UTC, nihal467 commented
@UdaySagar-Git can you fix the merge conflict in this PR, and the test & lint failure in the related backend PR

2024-08-16 19:06 UTC, UdaySagar-Git commented
@nihal467 done !

2024-09-10 09:49 UTC, nihal467 commented
the PR testing is on hold, as the backend PR is failing test

2024-09-23 13:54 UTC, gigincg commented
@sainak Can you update the issue here? I believe you've been working on this?

2024-09-23 13:57 UTC, gigincg commented
@nihal467 Can you expedite testing this? The backend has been merged.

2024-09-24 06:49 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/08ddfb21-af9a-4818-b6d3-d9d669bdadca)
![image](https://github.com/user-attachments/assets/50ba7180-0b9e-46a3-8065-43aaeadf6dff)


- [ ] The profile picture upload functionality is not working and it's throwing 404 in the frontend

@gigincg @sainak

2024-09-24 07:17 UTC, closed without merging