Vaccination Details frontend
coronasafe/care_fe pull request #8035
Opened 2024-06-18 07:36 UTC by hrit2773

## Proposed Changes

- Fixes #7876

2024-06-18 13:19 UTC, khavinshankar requested changes
@hrit2773 nicely done, but few changes are needed, here are the gist of changes needed:
1. remove unnecessary console logs
2. avoid using any or unknown
3. use useQuery to fetch data
4. use translation whereever possible
5. follow the existing conversion used in care while creating new forms

2024-06-18 13:19 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +  }, []);
use useQuery which keeps the code clean and no need of extra states like vaccinesList and isVaccineLoading

2024-06-18 13:19 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +    console.log(data);
```suggestion
```

2024-06-18 13:19 UTC, khavinshankar commented on src/Components/Patient/PatientRegister.tsx
> +                              Complete Vaccination Details
use internationalization, we are working on adding it through out the application, so when you come across an instance where it is not used while making changes, please feel free to add

2024-06-18 13:19 UTC, khavinshankar commented on src/Components/Patient/PatientVaccinationDetails.tsx
> +          {props.vaccineData?.map((detail: any) => (
avoid using any

2024-06-18 13:19 UTC, khavinshankar commented on src/Components/VaccinationDetails/AddVaccinationDetails.tsx
> +    <div className=" flex flex-col gap-2">
use form component and structure it similar to the existing forms, checkout patient register form for reference.

2024-06-18 13:30 UTC, hrit2773 commented
@khavinshankar thanks for pointing them will make these changes and update it soon.

2024-06-19 11:13 UTC, hrit2773 commented
@khavinshankar the add vaccination details form is similar to that of consultation diagnosis. The only difference being that it has multiple form fields. we dont need the restore button offered by the form component. And when we press add vaccination details it should just display the details and not submit it by whole. Submitting will be handled by patient register. So should i still use the form component? because pressing the submit button is reloading the page. Moreover, its not a seperate form, the vaccination details are entered in the patient register form itself. Multiple vaccines can be added. So i think form component is not needed. That may make it look like a completely independent form layout

2024-07-29 04:16 UTC, closed without merging