Hcx communication
coronasafe/care_fe pull request #8178
Opened 2024-07-19 06:26 UTC by khavinshankar

Added HCX communication flow

Backend PR: https://github.com/coronasafe/care/pull/1346

_Further docs will be added later in docs repo_

2024-07-19 06:34 UTC, rithviknishad commented on src/Components/HCX/ClaimCard.tsx
> +  console.log(containerDimensions);
```suggestion
```

2024-07-19 06:34 UTC, rithviknishad commented on src/Components/HCX/ClaimCardCommunication.tsx
> +  const [responses, setResponses] = useState<IMessage[]>([]);
TODO: replace useDispatch with useQuery/request

2024-07-19 06:34 UTC, rithviknishad commented on src/Components/HCX/SendCommunicationModal.tsx
> +  const [isLoading, setIsLoading] = useState(false);
TODO: replace useDispatch with useQuery/request

2024-07-19 06:34 UTC, rithviknishad commented on src/Redux/actions.tsx
> +
TODO: not required after migrating to useQuery/request.

```suggestion
```

2024-07-19 06:34 UTC, rithviknishad commented on src/Redux/actions.tsx
> +  },
TODO: not required after migrating to useQuery/request

```suggestion
```

2024-07-19 06:34 UTC, rithviknishad commented on src/Redux/api.tsx
> +  },
TODO: `TRes` and `TBody` to be defined for it to work with useQuery/request

2024-07-19 12:03 UTC, rithviknishad requested changes

2024-07-19 12:03 UTC, rithviknishad commented on src/Redux/api.tsx
> +    TRes: Type<HCXCommunicationModel>(),
Missing TBody

2024-07-19 12:03 UTC, rithviknishad commented on src/Redux/api.tsx
> +    TRes: Type<HCXCommunicationModel>(),
Missing TBody

2024-07-19 14:13 UTC, rithviknishad approved these changes

2024-07-23 10:37 UTC, nihal467 commented
@khavinshankar can you update the description for review purpose to understand what changed in this PR

2024-07-31 10:37 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/fac2e788-19b3-45c7-8205-982cfd9a0865)

- [ ] unable to send the message because the payor-app is down, HCX is not live

![image](https://github.com/user-attachments/assets/9a0a731e-0511-4a94-8e28-9137afb380d2)
![image](https://github.com/user-attachments/assets/4f09d568-2c80-4318-a77b-b0047df1a4dc)

- [ ] After we type a message, we need to click the add button and then the submit button to send the message. This is kind of confusing because I believe this feature will be used to seek additional documents and should have an expected behavior of chat, single-click to send a message, and an icon on the text box to select documents for attachment purposes to the chat. 

![image](https://github.com/user-attachments/assets/b490dbb6-cc20-41de-8b04-7ce534cfe4b8)
![image](https://github.com/user-attachments/assets/8ad62c72-fe81-4a20-b53a-b85ee73973ab)

- [ ] Compared to the existing staging, the two fields insurer ID and name are replaced with one single field named insurer in the HCX, so we should be keeping a consistent type of data in the platform, so how to handle this?

2024-07-31 10:38 UTC, nihal467 commented
@gigincg @khavinshankar update me, for re-reviewing once the things are sorted

2024-08-05 10:09 UTC, khavinshankar commented
New UI
![image](https://github.com/user-attachments/assets/21a48bfa-c446-4137-9176-00a09a1acbab)

2024-08-06 13:26 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/a0751298-49da-47ea-80e4-34ec9e44bba7)

- [ ] rename the cancel button as close, since we can add multiple insurance in a single flow, so the pop-up wont close automatically after adding one insurance

2024-08-06 13:33 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/62e63eef-f9b4-4798-aeba-6327563290e2)
![image](https://github.com/user-attachments/assets/52724e20-912f-4db2-aa16-657461b4edcd)

@khavinshankar Even the pre-auth was successful from the care side, the swasth payor app is not showing the patients name

2024-08-23 06:50 UTC, khavinshankar commented
The above mentioned issues will be tackled in a separate PR and will be monitored in a new issue #8413

2024-09-09 08:50 UTC, nihal467 commented
@khavinshankar can you get this PR for review and testing

2024-09-20 15:59 UTC, bodhish commented
@khavinshankar is this required in the context of NHCX?

2024-09-20 18:18 UTC, khavinshankar commented
@bodhish Yes, this is one of the HCX flow but this PR can be closed as this is already part of #8420

2024-09-20 18:52 UTC, bodhish commented
Let's close it 🚀

2024-09-21 12:20 UTC, gigincg commented
Closing based on confirmation from @khavinshankar

2024-09-21 12:20 UTC, closed without merging