Changes 'CONSULTATION NOTES' to 'GENERAL INSTRUCTIONS (ADVICE)'
coronasafe/care_fe pull request #8216
Opened 2024-07-25 19:01 UTC by ahmedobaid23

## Proposed Changes

- Fixes #8213 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-07-26 08:00 UTC, rithviknishad reviewed
Nice attempt!

Although this works, there would be other `keys` that might need an altered display text eventually.

Consider adding a map or using translation files (preferred) to reverse the key to a display text.

For example, refer:

- https://github.com/coronasafe/care_fe/blob/develop/src/Components/Patient/ManagePatients.tsx#L1095
- https://github.com/coronasafe/care_fe/blob/develop/src/Locale/en/Common.json#L147-L150

2024-07-26 10:30 UTC, ahmedobaid23 commented
@rithviknishad 

Thanks for reviewing my PR.

I will create a new file named `ConsultationFormTranslation.json`. For now, I will only map `consultation_notes` to its relevant display text. In the future, if the display text of other keys needs to changed, they will be added and mapped to their corresponding display texts in this file. Sounds good?

2024-07-26 10:52 UTC, rithviknishad commented
You can keep it in consultation.json itself. We have all consultation related translation keys present there.

2024-07-26 17:50 UTC, rithviknishad requested changes

2024-07-26 17:50 UTC, rithviknishad commented on src/Components/Facility/ConsultationDetails/Events/GenericEvent.tsx
> +type ConsultationMessageKeys = keyof typeof consultationMessage;
You shouldn't be importing the translations file directly. Use `useTranslation` hook to retrieve the display text instead. Ref: https://github.com/coronasafe/care_fe/blob/f76248c997c1153a9f859511a6678ada18dd0af9/src/Components/Facility/Consultations/DailyRoundsList.tsx#L24

2024-07-29 10:12 UTC, nihal467 commented
@ahmedobaid23 can you work on the changes requested

2024-07-29 10:29 UTC, ahmedobaid23 commented
@rithviknishad Yes, I am working on it

2024-07-29 11:42 UTC, rithviknishad approved these changes

2024-07-29 11:57 UTC, skks1212 approved these changes

2024-07-30 07:52 UTC, nihal467 commented
LGTM

2024-07-31 04:22 UTC, khavinshankar approved these changes

2024-07-31 04:22 UTC, merged