Adds prompt for ICD11 search field #8232
coronasafe/care_fe pull request #8233
Opened 2024-07-30 12:02 UTC by ahmedobaid23

## Proposed Changes

- Fixes #8232  

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-07-30 12:43 UTC, rithviknishad requested changes
@ahmedobaid23 

So the 1 character minimum requirement is not applicable for all usages of the autocomplete field. This component is used in multiple other places as well, and some usages does not even need a query text in the first place in-order to be able to show the options.

Maybe consider adding a prop `minQueryLength?: number` and conditionally only achieve the requirement specified in the issue.

2024-07-30 14:30 UTC, rithviknishad approved these changes
Awesome! Nice work!

2024-07-30 19:48 UTC, nihal467 commented
LGTM

2024-07-31 04:24 UTC, khavinshankar approved these changes

2024-07-31 04:24 UTC, merged