Fixed: Misalignment of placeholder text inside date component in the …
coronasafe/care_fe pull request #8240
Opened 2024-08-01 19:35 UTC by thevishvammoliya

Misalignment of placeholder text inside date component in the add user page #8239

## Proposed Changes

- Fixes #8239 https://github.com/coronasafe/care_fe/issues/8239
- Changed the CSS to add padding on the left to align the placeholder in DateInputV2

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

![Screenshot 2024-08-02 005250](https://github.com/user-attachments/assets/b3319d47-0ab7-4e73-a4d9-91a4627de3f7)

2024-08-02 04:16 UTC, rithviknishad requested changes

2024-08-02 04:16 UTC, rithviknishad commented on src/Components/Common/DateInputV2.tsx
> +                  className={`cui-input-base cursor-pointer !px-2 pl-4 disabled:cursor-not-allowed ${className}`}
`cui-input-base` class applies consistent padding and colors already. Removing `!px-2 pl-4` seems to have also solved the issue. Let's stick to not overriding the default padding applied for all input elements.

```suggestion
                  className={`cui-input-base cursor-pointer disabled:cursor-not-allowed ${className}`}
```

2024-08-02 06:56 UTC, rithviknishad approved these changes

2024-08-02 13:33 UTC, nihal467 commented
LGTM

2024-08-07 07:27 UTC, khavinshankar approved these changes

2024-08-07 07:27 UTC, merged

2024-08-07 10:07 UTC, nihal467 commented
@thevishvammoliya nice work, feel free to join the community slack workspace : join.slack.com/t/rebuildearth/shared_invite/zt-2blycdt83-yvoJRsa10QDhE9WFiwoVkg

2024-08-07 10:20 UTC, thevishvammoliya commented
@nihal467 thanks for all the support, looking forward to contribute more to CARE ❤️