Fix: Added online status to Doctor Connect
coronasafe/care_fe pull request #8261
Opened 2024-08-06 03:45 UTC by Shelly011s

## Proposed Changes

- Fixes #7859 
- Added a green dot to show the online status of staff nurses and doctor

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-06 14:29 UTC, samholics commented
Tested Working 
@nihal467

2024-08-06 18:11 UTC, rithviknishad requested changes

2024-08-06 18:11 UTC, rithviknishad commented on src/Components/Facility/DoctorVideoSlideover.tsx
>              Number(new Date()) - Number(new Date(user.last_login)) < 60000 ? (
@Shelly011s could you make use of the reusable utility fn. `isUserOnline` here instead, as that is what's being used elsewhere in the entire platform.

2024-08-06 18:25 UTC, Shelly011s commented on src/Components/Facility/DoctorVideoSlideover.tsx
>              Number(new Date()) - Number(new Date(user.last_login)) < 60000 ? (
Updated

2024-08-07 03:20 UTC, rithviknishad approved these changes

2024-08-07 06:24 UTC, nihal467 commented
This will be working on the same logic as our user tab , LGTM

2024-08-07 06:32 UTC, khavinshankar approved these changes

2024-08-07 06:32 UTC, merged

2024-08-07 10:05 UTC, nihal467 commented
@Shelly011s nice work, feel free to join the community slack workspace : https://join.slack.com/t/rebuildearth/shared_invite/zt-2blycdt83-yvoJRsa10QDhE9WFiwoVkg