Fix#8048
coronasafe/care_fe pull request #8295
Opened 2024-08-12 14:40 UTC by khavinshankar

## Proposed Changes

- Fixes #8060

2024-08-13 12:51 UTC, bodhish requested changes

2024-08-13 12:51 UTC, bodhish commented on src/Components/Facility/Consultations/Beds.tsx
> +                Update
Shoudn't we move these strings to I18n config?

2024-08-13 12:51 UTC, bodhish commented on src/Components/Facility/TreatmentSummary.tsx
> +            { key: "differential", title: "Differential Diagnosis" },
I think we should internationalize the strings.

2024-09-02 06:17 UTC, samholics commented
tested..however the IP number in patient dashboard is mentioned as OP number in the treatment summary
<img width="222" alt="image" src="https://github.com/user-attachments/assets/5393c933-d9f5-40b4-9e15-759d4acd83ef">
<img width="406" alt="image" src="https://github.com/user-attachments/assets/2e0fd9d4-a65e-4847-bd06-226d02b675bc">

2024-09-02 10:52 UTC, khavinshankar commented
@samholics fixed the above issue, can you please check again

cc: @nihal467

2024-09-02 10:57 UTC, samholics commented
tested, working fine.  issue resolved. @nihal467 @khavinshankar

2024-09-02 13:12 UTC, nihal467 commented
@khavinshankar 

![image](https://github.com/user-attachments/assets/cd80b4fd-4022-49dd-8a91-0f541bcd313d)

- [x] mention the principal diagnosis was unconfirmed, confirmed, etc... as a badge in the report

2024-09-02 13:51 UTC, nihal467 commented
LGTM

2024-09-02 14:27 UTC, rithviknishad requested changes

2024-09-02 14:27 UTC, rithviknishad commented on src/Components/Facility/TreatmentSummary.tsx
> +  | "unconfirmed"
Import `ConditionVerificationStatuses` instead

2024-09-02 14:27 UTC, rithviknishad commented on src/Components/Facility/TreatmentSummary.tsx
> +          )
```suggestion
          ActiveConditionVerificationStatuses.includes(
            curr.verification_status,
          )
```

2024-09-03 03:00 UTC, rithviknishad approved these changes

2024-09-03 05:39 UTC, bodhish approved these changes
LGTM

2024-09-03 05:39 UTC, merged