Refactored FileUpload component
coronasafe/care_fe pull request #8329
Opened 2024-08-14 16:23 UTC by shivankacker

## Proposed Changes

- Fixes #7887 
- Migrated to use file upload hooks
- Updated the tabs component
- Other UI refactors

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-20 15:36 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/bf91cf6b-549a-4a73-9240-9ad247be2bed)

- @shivankacker  click the view button, once the discharge summary is uploaded to the section , there will be error thrown

2024-08-20 19:22 UTC, shivankacker commented
@nihal467 fixed, but it shows "cannot load pdf" which is happening in staging as well. If it needs to be fixed, I will pick it up in another issue

2024-08-21 05:14 UTC, rithviknishad commented on src/Utils/useTimer.tsx
> +export const useTimer = () => {
Can we have doc comments on this hook? What it is trying to do and for what type of use-cases we could use this for.

2024-08-21 05:14 UTC, rithviknishad commented on src/Utils/useTimer.tsx
> +    let interval: any;
Avoid `any` types.

```suggestion
    let interval: ReturnType<typeof setInterval>;
```

2024-08-21 05:14 UTC, rithviknishad commented on src/Components/Files/FileUpload.tsx
> +export const LinearProgressWithLabel = (props: any) => {
Need types for the props
```suggestion
export const LinearProgressWithLabel = (props: {...}) => {
```

2024-08-21 05:14 UTC, rithviknishad commented on src/Components/Files/FileUpload.tsx
> +  archiveTime?: any;
avoid `any`

2024-08-21 10:06 UTC, nihal467 commented
@shivankacker make the changes requested

2024-08-21 10:24 UTC, rithviknishad approved these changes

2024-08-21 11:02 UTC, nihal467 commented
LGTM

2024-08-21 12:44 UTC, khavinshankar requested changes
@shivankacker the refactor looks good, way cleaner compared to the previous version, just i18n the text and let's get it merged. Please check all the changed files, in some places i18n were missing.

2024-08-21 12:44 UTC, khavinshankar commented on src/Components/Files/AudioCaptureDialog.tsx
> +    </div>
add localization for all the text

2024-08-22 15:04 UTC, shivankacker commented
@nihal467 internationalisation done

cc. @gigincg @khavinshankar

2024-08-22 15:28 UTC, khavinshankar commented on src/Components/Patient/ManagePatients.tsx
> +                { text: "Discharged", value: 1 },
i18n

2024-08-22 15:28 UTC, khavinshankar commented on src/Components/Patient/ManagePatients.tsx
> +                    msg: "Facility needs to be selected to view discharged patients.",
i18n

2024-08-22 15:28 UTC, khavinshankar commented on src/Components/Patient/PatientConsentRecords.tsx
> +          { text: "Archived", value: 1 },
i18n

2024-08-22 15:28 UTC, khavinshankar commented on src/Components/Resource/ResourceBoardView.tsx
> +              { text: "Completed", value: 1 },
i18n

2024-08-22 15:28 UTC, khavinshankar commented on src/Utils/useFileUpload.tsx
> +      setError("Please enter file name");
i18n

2024-08-22 15:28 UTC, khavinshankar commented on src/Components/Files/AudioCaptureDialog.tsx
> +            {t("audio.allow_permission")}
Lets stick to snake casing, use double underscore (__) instead of a dot (.), please update the rest too

2024-08-23 07:30 UTC, khavinshankar approved these changes

2024-08-23 07:40 UTC, merged