Show "Save and Continue" for Progress Notes and Doctors Log
coronasafe/care_fe pull request #8352
Opened 2024-08-19 14:22 UTC by shivankacker

## Proposed Changes

- Fixes #8351

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-19 16:44 UTC, rithviknishad approved these changes

2024-08-19 17:34 UTC, bodhish requested changes

2024-08-19 17:34 UTC, bodhish commented on src/Components/Patient/DailyRounds.tsx
> +  const buttonText = !id
Move strings to I18n

2024-08-19 17:37 UTC, bodhish commented on src/Components/Patient/DailyRounds.tsx
> +  const buttonText = !id
cc @rithviknishad

2024-08-19 20:20 UTC, bodhish approved these changes
LGTM

2024-08-20 11:43 UTC, nihal467 commented
LGTM

2024-08-21 04:41 UTC, khavinshankar approved these changes

2024-08-21 04:41 UTC, merged