Fixed #8304
coronasafe/care_fe pull request #8360
Opened 2024-08-19 20:12 UTC by JOSHIK27

## Proposed Changes

- Fixes #8304 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-20 05:38 UTC, rithviknishad requested changes

2024-08-20 05:38 UTC, rithviknishad commented on src/Components/Facility/ConsultationForm.tsx
> +                          }
```suggestion
                          required={state.form.suggestion !== "DC"}
```

2024-08-20 05:38 UTC, rithviknishad commented
@JOSHIK27 Could you also update the PR's title to be something more meaningful 😄

2024-08-20 06:17 UTC, JOSHIK27 commented
> @JOSHIK27 Could you also update the PR's title to be something more meaningful 😄

done @rithviknishad

2024-08-20 12:54 UTC, rithviknishad approved these changes

2024-08-21 10:29 UTC, nihal467 commented
@JOSHIK27 
![image](https://github.com/user-attachments/assets/35a2aec0-d759-4d5f-9bc0-2045d76d8a0f)

its throwing a 500 error in the frontend 

CC: @rithviknishad

2024-08-21 10:52 UTC, rithviknishad commented
@nihal467 backend changes required: https://github.com/coronasafe/care/pull/2382

Could you test with that?

2024-08-22 06:57 UTC, closed without merging

2024-08-22 07:18 UTC, rithviknishad commented
@JOSHIK27 would you be making a new PR for this?

2024-08-22 07:30 UTC, JOSHIK27 commented
> @JOSHIK27 would you be making a new PR for this?

Yes. Definitely