Navigate to session expired page instead of showing notification
coronasafe/care_fe pull request #8363
Opened 2024-08-20 10:45 UTC by rithviknishad

## Proposed Changes

- Navigate to session expired page instead of showing notification

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-20 11:33 UTC, nihal467 commented
@rithviknishad can you fix the cypress failure

2024-08-20 14:16 UTC, shivankacker requested changes

2024-08-20 14:16 UTC, shivankacker commented on src/Utils/request/handleResponse.ts
> +      navigate(`/session-expired?redirect=${window.location.href}`);
Add an additional check to see if we are not on the /session-expired page. Otherwise we might be stuck in a redirect loop 🤔

2024-08-21 10:24 UTC, shivankacker approved these changes

2024-09-02 14:39 UTC, nihal467 commented
LGTM

2024-09-03 09:33 UTC, khavinshankar approved these changes

2024-09-03 09:33 UTC, merged