Hide N/A and null values in event log #8376
coronasafe/care_fe pull request #8381
Opened 2024-08-21 06:38 UTC by Nithin9585

## Proposed Changes

- Fixes #8376
- Hide `N/A` and `null` values in the event log on the frontend.
- Updated the `NeurologicalTables` component to conditionally render empty strings for `N/A` and `null` values.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate bug / test a new feature.
- [X] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [] Request for Peer Reviews
- [ ] Completion of QA

2024-08-21 06:40 UTC, rithviknishad requested changes

2024-08-21 06:40 UTC, rithviknishad commented on src/Components/Facility/Consultations/NeurologicalTables.tsx
This file has nothing to do with Event Logs.
You might want to have a look at this file instead: https://github.com/coronasafe/care_fe/blob/develop/src/Components/Facility/ConsultationDetails/Events/GenericEvent.tsx

2024-08-21 07:01 UTC, rithviknishad requested changes

2024-08-21 07:01 UTC, rithviknishad commented on src/Components/Facility/ConsultationDetails/Events/GenericEvent.tsx
> +        ))}
LGTM, but can we map with the formatted value before the filter? `formatValue` function for the same entry is now called twice, which could be avoided.

Something like:

```jsx
Object.entries(values)
  .map(([key, value]) => ({ key, value: formatValue(value, key)}))
  .filter(({ value }) => value != null)
  .map(({ key, value }) => <>...</>)
```

2024-08-21 07:24 UTC, rithviknishad requested changes

2024-08-21 07:24 UTC, rithviknishad commented on src/Components/Facility/Consultations/NeurologicalTables.tsx
Could you discard/undo the changes made to the neurological tables file?

2024-08-21 07:42 UTC, rithviknishad approved these changes

2024-08-21 10:26 UTC, shivankacker approved these changes

2024-08-22 05:34 UTC, rithviknishad approved these changes

2024-08-22 05:34 UTC, rithviknishad commented on src/Components/Facility/ConsultationDetails/Events/GenericEvent.tsx
> +            <li key={idx}>{formatValue(v, key)}</li>
Nice find!

2024-08-22 09:49 UTC, nihal467 commented
LGTM

2024-08-22 16:50 UTC, khavinshankar approved these changes

2024-08-22 16:53 UTC, merged