HCX Plug
coronasafe/care_fe pull request #8420
Opened 2024-08-26 05:37 UTC by khavinshankar

## Proposed Changes

- Fixes https://github.com/ohcnetwork/docs/issues/37
- Fixes https://github.com/ohcnetwork/care_fe/issues/8413
- Depends on: https://github.com/ohcnetwork/care/pull/2399

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-09-09 08:50 UTC, nihal467 commented
@khavinshankar can you get this PR for review and testing

2024-09-17 07:01 UTC, rithviknishad requested changes

2024-09-17 07:01 UTC, rithviknishad commented on src/Common/hooks/useAsyncOptions.ts
`useAsyncOptions` is no longer needed with `useQuery` and `mergeQueryOptions` utility fn as mentioned in the doc. comment of the `useAsyncOptions`.

See how medibase autocomplete form field was migrated out of useAsyncOptions to use useQuery + mergeQueryOptions.

https://github.com/ohcnetwork/care_fe/pull/7381/files#diff-27f7661cf02d3f78f7bbc53331f501ddc59ad9a33c613022593b529c128c8bb4

Let's delete this file once migrated too.

2024-09-17 07:01 UTC, rithviknishad commented on src/Components/Common/PMJAYProcedurePackageAutocomplete.tsx
> +        }
Switch to `useQuery` + `mergeQueryOptions` instead.

2024-09-17 07:01 UTC, rithviknishad commented on src/Components/Facility/ConsultationClaims.tsx
> +      },
i18n + reducing if else ladder for readability.

```suggestion
        if (!isCreateLoading) {
          return;
        }
        
        if (res.data && res.data.results) {
          Notification.Success({ msg: "Fetched Claim Approval Results" });
          return;
        }
        
        Notification.Error({ msg: "Error Fetching Claim Approval Results" });
      },
```

2024-09-17 07:01 UTC, rithviknishad commented on src/Components/Facility/DischargeModal.tsx
> +      setIsCreateClaimLoading(false);
same, i18n + reduce if-else ladder.

2024-09-17 07:01 UTC, rithviknishad commented on src/Components/HCX/ClaimCardInfo.tsx
> +              status === t("claim__status__pending") && "bg-yellow-400",
This seems hacky. How about we store `status` in known set of options in English and translate only in the place where we render it?

2024-09-17 07:01 UTC, rithviknishad commented on cypress.config.ts
> +    ENABLE_HCX: process.env.REACT_ENABLE_HCX ?? false,
Should we make plugs configurable in cypress? Shouldn't we enable all plugs for cypress tests? (Also by ensuring all plugs are enabled in FE build too for cypress?)

2024-09-17 07:01 UTC, rithviknishad commented on src/Components/HCX/InsurerAutocomplete.tsx
> +        }
Switch to `useQuery` + `mergeQueryOptions` instead.

2024-09-17 08:26 UTC, khavinshankar commented on cypress.config.ts
> +    ENABLE_HCX: process.env.REACT_ENABLE_HCX ?? false,
Yes, that's a nice idea, but it is a bit tricky for HCX as we have 2 flows based on whether HCX is enabled. Creating a new issue to track this https://github.com/ohcnetwork/care_fe/issues/8553

2024-09-17 08:28 UTC, rithviknishad approved these changes

2024-09-19 05:52 UTC, shivankacker approved these changes

2024-09-23 09:34 UTC, merged