Issue 8422
coronasafe/care_fe pull request #8443
Opened 2024-08-30 07:18 UTC by Adiflickzzz

## Proposed Changes

- Fixes #issue_number
- Change 1
- Change 2
- More?

@ohcnetwork/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-08-30 09:00 UTC, rithviknishad requested changes
As already mentioned in https://github.com/ohcnetwork/care_fe/pull/8442#issuecomment-2320259224

Please update the PR title and body

2024-08-30 09:00 UTC, rithviknishad commented on src/Components/Common/prescription-builder/ProcedureBuilder.tsx
> +                  {t("Procedure Suggestions")}
Key needs to be added to `en` locale files under `Consultation.json`

2024-08-30 09:00 UTC, rithviknishad commented on .env
> +
```suggestion
```

2024-09-06 14:56 UTC, nihal467 commented
@Adiflickzzz closing this PR as invalid

2024-09-06 14:56 UTC, closed without merging

2024-09-30 20:29 UTC, bodhish commented
@Adiflickzzz please don't spam