Remove clear all filters when no filters are applied.
coronasafe/care_fe pull request #8466
Opened 2024-09-03 07:12 UTC by Sulochan-khadka

… Discharge patients page #8449

## Proposed Changes

- Fixes #8449 
- changed condition from show to activefilters

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-09-03 08:38 UTC, rithviknishad requested changes
This is not right. Now when I apply consent record filters, the badges appear however, the clear all filters button doesn't.

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/776f18db-77ab-481e-b933-becdcaeca75b">

2024-09-04 10:09 UTC, Sulochan-khadka commented
> This is not right. Now when I apply consent record filters, the badges appear however, the clear all filters button doesn't.
> 
> <img alt="image" width="1148" src="https://private-user-images.githubusercontent.com/25143503/363905697-776f18db-77ab-481e-b933-becdcaeca75b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQ3NjEsIm5iZiI6MTcyNTQ0NDQ2MSwicGF0aCI6Ii8yNTE0MzUwMy8zNjM5MDU2OTctNzc2ZjE4ZGItNzdhYi00ODFlLWI5MzMtYmVjZGNhZWNhNzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOWQxNjg1YWU5N2I3MDA4YjUzNDc2NGU1MjAzYzAxOTNlNDhlYWYxMGEzZmRkMjUyZThkYTJiZmJiZWQ0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9po5k0sjqu6RTFC5WcrL9IoxgRZ1cpdFPNOCTKBIrgU">

Apologies for the oversight. I hope that the issue has been fixed in the update.

2024-09-04 11:58 UTC, rithviknishad approved these changes

2024-09-06 15:01 UTC, nihal467 commented
LGTM

2024-09-10 08:03 UTC, khavinshankar approved these changes

2024-09-10 08:04 UTC, merged