fix: add bed notification
coronasafe/care_fe pull request #8632
Opened 2024-09-26 06:15 UTC by AdityaJ2305

## Fixes #8627 

- Added a ternary operator to check no. of beds added and display the notification as per no. of beds selected 

 ## video demo: 

https://github.com/user-attachments/assets/c57abfe9-cb79-4e1f-9059-1392fe8a6ae9

- Reviewers 
@ohcnetwork/care-fe-code-reviewers
@nihal467 

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

2024-09-26 06:16 UTC, rithviknishad requested changes
Let's keep representable texts in `en` locale files using `useTranslations`.

Also check-out the proper expected behaviour. Show "Beds" instead of "Bed(s)" for multiple bed creation.

2024-09-26 06:55 UTC, rithviknishad approved these changes
LGTM

2024-09-27 11:10 UTC, nihal467 commented
LGTM

2024-09-30 20:18 UTC, bodhish requested changes
CC @rithviknishad

2024-09-30 20:18 UTC, bodhish commented on src/Components/Facility/AddBedForm.tsx
> +          : onSuccess(t("single_bed_created_notification")));
Look into https://www.i18next.com/translation-function/plurals

2024-10-01 09:17 UTC, khavinshankar commented
@AdityaJ2305 can you make the necessary changes

2024-10-01 10:40 UTC, AdityaJ2305 commented
Yes by EOD

2024-10-01 14:51 UTC, AdityaJ2305 commented
@bodhish @rithviknishad   Should we display `4 Beds created successfully` (with the count) or keep the previous format, `Beds created successfully` ?

2024-10-01 16:19 UTC, rithviknishad commented
Let's keep the count

2024-10-02 19:40 UTC, bodhish approved these changes
LGTM

2024-10-02 19:41 UTC, merged