Fixing Read More on notes in prescription
coronasafe/care_fe pull request #8647
Opened 2024-09-26 19:18 UTC by vishwansh01

## Proposed Changes

- Fixes #8643
- Fixed the ReadMe button

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/4c87a2cf-314e-4508-a627-34eeedfc016b

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-09-27 03:09 UTC, rithviknishad requested changes
Refer: https://github.com/ohcnetwork/care_fe/issues/8643#issuecomment-2377440395

2024-09-27 07:10 UTC, vishwansh01 commented
> Refer: [#8643 (comment)](https://github.com/ohcnetwork/care_fe/issues/8643#issuecomment-2377440395)
@rithviknishad 
 I just made changes to the PR as requested.

2024-09-27 07:26 UTC, rithviknishad approved these changes

2024-09-27 11:22 UTC, nihal467 commented
LGTM

2024-10-01 09:14 UTC, khavinshankar approved these changes

2024-10-01 09:14 UTC, merged