fix: Added Validation for Insurance input fields in patient registration  issue (#8672)
coronasafe/care_fe pull request #8681
Opened 2024-10-01 05:53 UTC by syedfardeenjeelani

## Proposed Changes

- Fixes #8672
- Added frontend validation for insurance input fields (Member ID, Policy ID, and Insurer Name) in the patient registration form.

https://github.com/user-attachments/assets/2da86816-e638-44c3-b756-7d015e7ddf20

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to the issue.
- [ ] Request Peer Reviews.
- [ ] Completion of QA.

2024-10-01 05:56 UTC, rithviknishad commented
@syedfardeenjeelani is this ready for review?

2024-10-01 05:59 UTC, syedfardeenjeelani commented
> @syedfardeenjeelani is this ready for review?

 we are getting the error from the validator.ts which is something like this
if (
!value.policy_id.trim() ||
!value.subscriber_id.trim() ||
(enable_hcx && (!value.insurer_id?.trim() || !value.insurer_name?.trim()))
)
return "All fields are mandatory";

so should i use field_required from the i18n locale here instead of "All fields are mandatory"

2024-10-01 12:32 UTC, rithviknishad commented
yes

2024-10-01 12:34 UTC, syedfardeenjeelani commented
> yes

Thanks I'll do the changes and push

2024-10-01 14:15 UTC, syedfardeenjeelani commented
@rithviknishad  if we do it like this 
 if (
    !value.policy_id.trim() ||
    !value.subscriber_id.trim() ||
    (enable_hcx && (!value.insurer_id?.trim() || !value.insurer_name?.trim()))
  )
    return t("field_required");
};


then it will also show it right here
![issue](https://github.com/user-attachments/assets/18f3bd0a-5072-4dbc-9614-386f68011b9b)
  so instead should a make a key which  says  "all_fields_mandatory": "All fields are mandatory"

or should we handle both cases seprately

2024-10-01 16:22 UTC, rithviknishad commented
Let's keep the error texts same as before itself, just that ensure ALL fields are required validation happens as mentioned in the issue.

2024-10-01 18:51 UTC, syedfardeenjeelani commented
@rithviknishad  I've made some changes based on your feedback, but I'm not sure if I got it right. Could you take a look at my PR when you get a chance and let me know if i am headed in the right direction or not ?

2024-10-03 04:20 UTC, rithviknishad requested changes
Only this file needs to be modified: https://github.com/ohcnetwork/care_fe/blob/develop/src/Components/HCX/validators.ts

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +              error={error}
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +          error={error}
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +          error={error}
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +  error: FieldError;
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +  error,
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +              error={props.error}
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Components/HCX/InsuranceDetailsBuilder.tsx
> +import { FieldError } from "../Form/FieldValidators";
```suggestion
```

2024-10-03 04:20 UTC, rithviknishad commented on src/Redux/fireRequest.tsx
> +            // return error.response;
Why was this changed?

2024-10-03 06:04 UTC, syedfardeenjeelani commented
> Only validation logic in this file needs to be modified: https://github.com/ohcnetwork/care_fe/blob/develop/src/Components/HCX/validators.ts

hey @rithviknishad  should it be something like this 
if (!value.policy_id.trim()) {
    return "some err message";
  } else if (!value.subscriber_id.trim()) {
    return "some err message";
  }
  if (enable_hcx) {
    if (!value.insurer_id?.trim()) {
      return "some err message";
    } else if (!value.insurer_name?.trim()) {
      return "some err message";
    }
  }  

also do we only have to change this particular file and nothing else

2024-10-03 09:16 UTC, rithviknishad commented
> also do we only have to change this particular file and nothing else

yes

2024-10-04 19:38 UTC, nihal467 commented
@rithviknishad can you verify is it ready for testing

2024-10-05 09:38 UTC, rithviknishad requested changes
texts to be in i18n locale files

https://github.com/ohcnetwork/care_fe#translations

2024-10-05 11:51 UTC, syedfardeenjeelani commented
> texts to be in i18n locale files
> 
> https://github.com/ohcnetwork/care_fe#translations

@rithviknishad  hello should i put them in common.json

2024-10-08 07:46 UTC, rithviknishad commented
Put in `en.json`

2024-10-08 17:05 UTC, syedfardeenjeelani commented
> Put in `en.json`

okay

2024-10-11 22:36 UTC, nihal467 commented
@syedfardeenjeelani any update on the PR

2024-10-12 07:18 UTC, syedfardeenjeelani commented
@rithviknishad  i need some guidance i cant find en.json

2024-10-12 09:16 UTC, AdityaJ2305 commented
> @rithviknishad i need some guidance i cant find en.json

need to update the new changes in forked repo then pull

2024-10-12 10:02 UTC, rithviknishad commented
yup

2024-10-15 13:06 UTC, rithviknishad approved these changes

2024-10-16 11:47 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/fa7ebb7d-8e28-47f7-89bb-4e8aaa14ec87)
![image](https://github.com/user-attachments/assets/f83d7c26-b107-4b6b-8fe6-e5f9f9d63df3)

- [ ] Even though the validation is added, it's not blocking the user from submitting a patient registration form when the insurance fields are kept blank

2024-10-16 12:09 UTC, AdityaJ2305 commented
Hey @syedfardeenjeelani , Please check by adding this line `errors["insurance_details"] = insuranceDetailsError;` in `validateForm` func in `PatientRegister.tsx`

2024-10-17 04:21 UTC, rithviknishad commented
@syedfardeenjeelani could you resolve the merge conflicts?

2024-10-17 04:21 UTC, rithviknishad commented
ensure the en.json file has keys sorted. pre-commit should do it for you if setup properly.

2024-10-19 06:14 UTC, syedfardeenjeelani commented
@nihal467  please test this

2024-10-19 06:17 UTC, rithviknishad requested changes

2024-10-19 06:17 UTC, rithviknishad commented on src/Locale/en.json
why is the entire file having a change?

2024-10-19 06:23 UTC, syedfardeenjeelani commented on src/Locale/en.json
pre-commit  was not sorting keys for me so i used https://codeshack.io/json-sorter/

2024-10-19 06:24 UTC, rithviknishad commented on src/Locale/en.json
use `npm run sort-locales` instead; also why is pre-commit not sorting?

2024-10-19 06:34 UTC, syedfardeenjeelani commented on src/Locale/en.json
i will look into it @rithviknishad  also can you please tell  me if i should   hard reset to commit [f5a265172e499e4f4016be1453751680b7eb416b](https://github.com/ohcnetwork/care_fe/pull/8681/commits/f5a265172e499e4f4016be1453751680b7eb416b) (fixed validation) or do something different from here

2024-10-20 16:44 UTC, rithviknishad requested changes

2024-10-20 16:44 UTC, rithviknishad commented on src/Locale/en.json
Why is so many i18n keys deleted?

2024-10-20 16:44 UTC, rithviknishad commented on package-lock.json
Could you discard changes to the lock file?

2024-10-20 16:52 UTC, closed without merging

2024-10-20 16:58 UTC, syedfardeenjeelani commented
@rithviknishad  i will setup the repo again and raise a new pr