Noufalrahim/feat/added units to pressure sore
coronasafe/care_fe pull request #8715
Opened 2024-10-05 01:57 UTC by noufalrahim

## Proposed Changes

- Fixes #8209 
- Added Units
- Added Units to i18n locale files (Consultation.json)
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-10-05 09:35 UTC, rithviknishad requested changes

2024-10-05 09:35 UTC, rithviknishad commented on src/Locale/en/Consultation.json
> +  "length_label__cm": "Length (cm)"
```suggestion
  "width": "Width ({{ unit }})",
  "length": "Length ({{ unit }})"
```

2024-10-05 09:35 UTC, rithviknishad commented on src/Components/LogUpdate/Sections/PressureSore/PressureSore.tsx
> +            label={t("width_label__cm")}
```suggestion
            label={t("width", { unit: "cm" })}
```

2024-10-05 09:35 UTC, rithviknishad commented on src/Components/LogUpdate/Sections/PressureSore/PressureSore.tsx
> +            label={t("length_label__cm")}
```suggestion
            label={t("length", { unit: "cm" })}
```

2024-10-05 09:55 UTC, rithviknishad approved these changes

2024-10-07 23:17 UTC, bodhish commented
@noufalrahim please add human firendly title and description for the PR. We also expect you to complete the #Merge Checklist

cc @rithviknishad

2024-10-08 15:16 UTC, nihal467 commented
@noufalrahim can you push the changes requested by @bodhish

2024-10-10 05:42 UTC, closed without merging