Fix#8815/fix clear button aligned arrow
coronasafe/care_fe pull request #8817
Opened 2024-10-17 11:03 UTC by NitinPSingh

## Proposed Changes

- Fixes #8815 
- [x] The clear button should clear the already selected data in the input field
- [x] Align the dropdown arrow to be in the center rather than the top of the input field

@ohcnetwork/care-fe-code-reviewers

https://github.com/user-attachments/assets/f10cf8de-cef7-4ac9-95ea-ef1e7c649eef

2024-10-17 12:22 UTC, NitinPSingh commented
@rithviknishad @nihal467 the cross button is implemented such that it opens the dropdown on click , do you want to remove this?

current:

https://github.com/user-attachments/assets/879bbbb4-1026-4bb1-9701-6da932d378ca


i have implemented the changes which will not open the dropdown on click of cross button, should i push?

https://github.com/user-attachments/assets/5fc69f78-dc60-4dfb-ad79-3a423c6c740c

2024-10-18 10:28 UTC, nihal467 commented
@NitinPSingh the cross button is implemented such that it opens the dropdown on click , keep this behavior itself

2024-10-18 10:40 UTC, NitinPSingh commented
@nihal467 ok , i havent push that part yet , so the current code will clear the selected and also open the drop-down

2024-10-18 11:14 UTC, nihal467 commented
@NitinPSingh https://github.com/ohcnetwork/care_fe/actions/runs/11402328266/job/31727083859?pr=8817 , there is cypress failure, can you fix it

2024-10-18 14:09 UTC, NitinPSingh commented
all green now

2024-10-18 15:40 UTC, nihal467 commented
LGTM

2024-10-21 04:09 UTC, bodhish commented
@NitinPSingh Please do add a human firendly title for the PR

2024-10-21 09:35 UTC, Jacobjeevan commented on src/Components/Facility/SpokeFacilityEditor.tsx
> +              (v === null || (!Array.isArray(v) && v)) && setSelectedFacility(v)
This isn't a big deal, but since you are specifying the type for state object to be FacilityModel or null, probably don't need the (&& v) check anymore.

2024-10-21 09:36 UTC, Jacobjeevan approved these changes
LGTM

2024-10-22 01:49 UTC, khavinshankar requested changes

2024-10-22 01:49 UTC, khavinshankar commented on src/Components/Facility/SpokeFacilityEditor.tsx
> +              (v === null || (!Array.isArray(v) && v)) && setSelectedFacility(v)
@NitinPSingh Like @Jacobjeevan mentioned, the logic wouldnt be effected but its hard to read, please simplify it to something like

```suggestion
              (v === null || !Array.isArray(v)) && setSelectedFacility(v)
```

2024-10-23 10:41 UTC, rithviknishad commented
this wasn't intended right?

<img width="998" alt="image" src="https://github.com/user-attachments/assets/c47baff4-16aa-45cc-b8ab-477c777acb25">

2024-10-23 10:42 UTC, NitinPSingh commented
something went wrong here i guess let me fix , i create new pr

2024-10-23 10:52 UTC, closed without merging