Fix: Permission Handling Issues in Microphone and Camera Capture Dialogs
coronasafe/care_fe pull request #8830
Opened 2024-10-19 16:46 UTC by shauryag2002

## Proposed Changes

- Fixes #8829 
- In the `Record audio` modal, the recording timer now starts only after the user grants microphone access. If permission is denied, an appropriate error message is displayed to the user.
- In the `Open Camera` modal, when camera access is blocked, a proper error message is shown instead of an empty container. The camera no longer freezes after clicking the `Switch` button, and a clear message is displayed if the camera cannot be switched.

## **Video**:

https://github.com/user-attachments/assets/39556953-d678-4e18-8296-c6155a39bf86

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-10-21 16:40 UTC, nihal467 commented
LGTM

2024-10-22 01:34 UTC, khavinshankar requested changes
LGTM, Nicely done, just a minor i18n change

2024-10-22 01:34 UTC, khavinshankar commented on src/Components/Files/AudioCaptureDialog.tsx
> +        });
i18n

2024-10-27 08:39 UTC, shauryag2002 commented on src/Components/Files/AudioCaptureDialog.tsx
> +        });
Done

2024-10-27 22:12 UTC, bodhish approved these changes
LGTM

2024-10-27 22:23 UTC, merged