Bed management UI enhancement
coronasafe/care_fe pull request #8839
Opened 2024-10-21 04:38 UTC by Jacobjeevan

## Proposed Changes

- Fixes #6974 

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/61973f6b-532a-4bb9-ba9d-543780672796">

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

2024-10-21 04:45 UTC, bodhish requested changes

2024-10-21 04:45 UTC, bodhish commented on src/Components/Facility/BedManagement.tsx
> +  };
Can't we use tailwind https://tailwindcss.com/docs/text-overflow#truncate

2024-10-21 04:45 UTC, bodhish commented on src/Components/Facility/BedManagement.tsx
> +  };
Also lets not show anything if we don't have a description.

2024-10-21 05:00 UTC, bodhish approved these changes
LGTM

2024-10-21 05:18 UTC, Jacobjeevan commented
I'll take a look at the failing test 👍

2024-10-21 17:18 UTC, samholics commented
tested, working fine @nihal467

2024-10-21 17:19 UTC, nihal467 commented
![image](https://github.com/user-attachments/assets/c17b64a0-f3f7-4b6f-84ee-9537ba8c5d6e)

- [ ] use the full width of the page, on the left side, so it is aligned with the bed management heading

![image](https://github.com/user-attachments/assets/b02df95d-f96c-45ea-832d-e6e7f1be9a73)

- [ ] add a space between the white padding and the button when there is no bed in the location

2024-10-21 19:16 UTC, Jacobjeevan commented
> ![image](https://private-user-images.githubusercontent.com/57055998/378533375-c17b64a0-f3f7-4b6f-84ee-9537ba8c5d6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Mzg0NTksIm5iZiI6MTcyOTUzODE1OSwicGF0aCI6Ii81NzA1NTk5OC8zNzg1MzMzNzUtYzE3YjY0YTAtZjNmNy00YjZmLTg0ZWUtOTUzN2JhOGM1ZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE5MTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YmJhM2Y2MGQ3Y2Y3OTQ0MWFkMDhmOTA4YjAwY2UxYTZhNTQ1OGU0OTEzYmE3MjViMDk3YWZmM2NiZmYzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.neSRvtx5e3HS94NIqtY-Qnf9xudp9i27eIj-m4HtW5w)
> 
>     * [ ]  use the full width of the page, on the left side, so it is aligned with the bed management heading
> 
> 
> ![image](https://private-user-images.githubusercontent.com/57055998/378534116-b02df95d-f96c-45ea-832d-e6e7f1be9a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Mzg0NTksIm5iZiI6MTcyOTUzODE1OSwicGF0aCI6Ii81NzA1NTk5OC8zNzg1MzQxMTYtYjAyZGY5NWQtZjk2Yy00NWVhLTgzMmQtZTZlN2YxYmU5YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE5MTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNDFiOWY3YzIzYjY0NzI0MGQ0MjVmZDIwNDE1MjgwMjZjNjYzZjM2ZjQ1NTQxMmY1NDFhOGVmMmFjODIyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZDcI_SSwrUgcxqfH-ip4tlYetBKprrkLksJ5LpbkIIk)
> 
>     * [ ]  add a space between the white padding and the button when there is no bed in the location

Done 👍

2024-10-22 08:42 UTC, nihal467 commented
LGTM

2024-10-22 08:48 UTC, rithviknishad approved these changes

2024-10-22 08:48 UTC, rithviknishad commented on src/Locale/en.json
> +  "add_new_beds": "Add New Bed(s)",
could've been improved with https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

2024-10-22 16:08 UTC, khavinshankar approved these changes

2024-10-22 16:09 UTC, merged