responsive: shiftingDetails page and Breadcrumbs added phone and desktop
coronasafe/care_fe pull request #8933
Opened 2024-10-26 17:27 UTC by modamaan

## Proposed Changes
change the button alignment when phone size

- Fixes #8831 

Before
![Screenshot 2024-10-20 000900](https://github.com/user-attachments/assets/3df09704-bdc8-4693-907e-037fd16bca29)

After
![Screenshot 2024-10-20 011739](https://github.com/user-attachments/assets/092c7ada-ce53-4354-a70a-04a789321d11)

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-10-26 17:46 UTC, modamaan commented
@bodhish @rithviknishad 

https://github.com/user-attachments/assets/230362f1-51a7-43dc-8260-f074e01069a3

2024-10-26 20:33 UTC, shivankacker commented
@modamaan unable to understand the breadcrumbs relation here, could you elaborate more in the PR description?

2024-10-27 00:13 UTC, modamaan commented
@shivankacker https://github.com/ohcnetwork/care_fe/pull/8833#issuecomment-2425499268

2024-10-27 00:30 UTC, modamaan commented
## Proposed Changes
 add responsive shadcn breadcrumbs

- Fixes #8831 

Current version
![Screenshot 2024-10-27 055208](https://github.com/user-attachments/assets/04d123f1-5b20-4037-a36a-2d97f47b040c)

Last item broken

![Screenshot 2024-10-27 055401](https://github.com/user-attachments/assets/24d42762-966d-4995-89ff-241ff850f464)

No dropdown here

Updated version

![Screenshot 2024-10-27 055745](https://github.com/user-attachments/assets/bd7fd764-3b87-4d0e-8b09-86007d10c358)
Last item broken issue solved

![Screenshot 2024-10-27 055906](https://github.com/user-attachments/assets/a68e54a6-ee9b-465d-91f0-686a3c9daaa1)
Shadcn Dropdown added

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-10-27 21:42 UTC, bodhish commented
Duplicate of https://github.com/ohcnetwork/care_fe/pull/8833

2024-10-27 21:46 UTC, bodhish requested changes
<img width="411" alt="image" src="https://github.com/user-attachments/assets/f0b7bfce-098c-4ccf-b3c6-7164ed820097">
 I will actually add icons for non paths in the dropdown. 
 
 Example 
- 🏢 Critical Care
- 🗳 Assets 
> unicodes are just for illustration. 

I expect these changes to be made on the previous PR

2024-10-27 21:46 UTC, bodhish commented on src/components/Common/Breadcrumbs.tsx
> +import useAppHistory from "../../common/hooks/useAppHistory";
Why revert the change :( 
Lets use `@`

2024-10-28 14:06 UTC, modamaan commented
@bodhish  ![Screenshot 2024-10-28 193508](https://github.com/user-attachments/assets/b3aa1a0e-26f4-4789-9662-217a7448f568)

2024-10-28 14:12 UTC, modamaan commented on src/components/Common/Breadcrumbs.tsx
> +import useAppHistory from "../../common/hooks/useAppHistory";
resolved

2024-10-30 14:35 UTC, closed without merging

2024-10-30 14:35 UTC, modamaan commented
i made a mistake, created branch from local branch instead of develop branch. this caused it to include all commits from my other branch, i would like to create new branch and resolve this issue