update condition to render component
coronasafe/care_fe pull request #8960
Opened 2024-10-29 08:33 UTC by JavidSumra

## Proposed Changes

- Fixes #8958 
- Updated the condition to render the `TextAreaFormField` for "OTHER TYPE" and "9" selections in the sample type dropdown.
- Ensured that the component renders correctly based on the selected sample type.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-10-29 09:08 UTC, rithviknishad requested changes
solves the mentioned issue; but in the sample details page, the sample test type details (value entered in the text area) is not being shown. let's fix that too

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/37225927-77fc-4429-acc5-814533653956">


<img width="1708" alt="image" src="https://github.com/user-attachments/assets/0bfad7c9-6101-4150-bffc-4d0d206ba73a">

2024-10-29 09:11 UTC, JavidSumra commented
Can I add extra space for that or just display it inline?

2024-10-29 09:13 UTC, rithviknishad commented
you can add it to the right (2nd col. of the grid) like others

2024-10-29 11:41 UTC, JavidSumra commented
@rithviknishad requested changes done

2024-10-29 14:00 UTC, Jacobjeevan requested changes

2024-10-29 14:00 UTC, Jacobjeevan commented on src/components/Patient/SampleDetails.tsx
> +        console.log(data);
Let's remove this console.log 👍

2024-10-29 14:00 UTC, Jacobjeevan commented on src/components/Patient/SampleDetails.tsx
> +                Sample Type Description:
Add a space after the colon, similar to what's there for other titles.

On a side note, now's probably the time to add in translations for these titles.

2024-10-29 14:03 UTC, JavidSumra commented on src/components/Patient/SampleDetails.tsx
> +                Sample Type Description:
So shall I need to add translation for each field title?

2024-10-30 08:26 UTC, khavinshankar approved these changes

2024-10-30 08:27 UTC, khavinshankar commented
@Jacobjeevan @rithviknishad can u please re-review this

2024-10-30 08:29 UTC, rithviknishad approved these changes

2024-10-30 08:33 UTC, Jacobjeevan approved these changes

2024-11-04 21:02 UTC, nihal467 commented
@gigincg There is no product requirement for adding a text box for selecting other sample test types in the sample test request form. Can you provide insight into whether it's a required change or not?

2024-11-05 02:45 UTC, JavidSumra commented
Hey @nihal467 I'm not adding textbox it's already present but with the wrong condition for rendering.

2024-11-05 08:30 UTC, nihal467 commented
@JavidSumra 
![image](https://github.com/user-attachments/assets/8aff2715-4fba-4e4d-9c6f-69a008ecc324)

In the Sample Test History section on the Patient Details page, the "Other Type" sample request is currently displaying the Sample Test Type Details description under the Sample Test heading. Please update it to display "Other Type" instead.

2024-11-08 21:33 UTC, nihal467 commented
LGTM

2024-11-10 03:55 UTC, rithviknishad approved these changes

2024-11-10 03:56 UTC, merged