Fixed Cypress Parallel
coronasafe/care_fe pull request #8989
Opened 2024-11-04 06:00 UTC by nihal467

## Proposed Changes

- Fixes #issue_number
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-11-05 10:14 UTC, bodhish commented
Did we merge the other PR from @rithviknishad 🤔

2024-11-06 07:51 UTC, rithviknishad reviewed
we could further reduce the time for the action by caching the backend's volume too after running the migrations and load dummy data.

2024-11-06 14:07 UTC, rithviknishad requested changes

2024-11-06 14:07 UTC, rithviknishad commented on package-lock.json
lock file changes needs to be discarded;

2024-11-22 07:51 UTC, closed without merging