Upgrading Sample Tests & Investigations to Lab Orders
coronasafe/care_fe pull request #9260
Opened 2024-11-30 21:32 UTC by yash-learner

## Proposed Changes

- Fixes #8683 
- Change 1
- Change 2
- More?

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

--

[InProgress Figma link](https://www.figma.com/design/Z93EYKSa1MdBmXndsMBJSQ/Care?node-id=2346-1282&node-type=canvas&t=i1HFQvkk4JV42N4C-0)

2025-01-14 04:33 UTC, khavinshankar requested changes
@yash-learner, can you make these changes ASAP!

Most of the suggestions need to be implemented across the board, but I have just mentioned it once (just a heads up).

Apart from the comments, merge conflicts and i18n also needs to be done.

2025-01-14 04:33 UTC, khavinshankar commented on src/types/emr/specimen.ts
> +  ];
Is this relevant?

2025-01-14 04:33 UTC, khavinshankar commented on src/components/ui/button.tsx
> +          "bg-primary-700 text-white shadow hover:bg-primary-700/90 dark:bg-primary-100 dark:text-primary-900 dark:hover:bg-primary-100/90",
revert changes to this file

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Questionnaire/QuestionnaireSearch.tsx
> +          limit: 100,
revert this

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/utils.ts
> +  console.log(subSteps, previousStepStatus, "subSteps");
remove console logs, here and in other places if any

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/utils.ts
> +};
Specimen always returns request which is a service request and it always comes with phase field, consider using that, it will be more accurate

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/utils.ts
> +): SpecimenStatus => {
Consider rewriting this util with phase, just a thought

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/SendSpecimen.tsx
> +          {/* Expanded Content */}
remove these unwanted comments (only have comments when you want to explicitly mention something), also remove comments in other places too if any

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +            />
Always use barcode input for barcode, change this in other places if any

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +  });
make this dynamic, fetch this data from the `system-specimen-condition` valueset

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +  const [note, setNote] = React.useState<string>();
move note into form schema, and there should be a note for each condition, the idea is,

here is an example structure
```ts
[
  {
    codings: [
      {
        system: "...",
        code: "condition 1",
        display: "condition 1",
      },
    ],
    text: "note for condition 1",
  },
  {
    codings: [
      {
        system: "...",
        code: "condition 2",
        display: "condition 2",
      },
    ],
    text: "note for condition 2",
  },
];
```

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +                  {scannedSpecimen.subject.id || "T105690908240017"}
remove hardcoded default values, and use util functions to display id, name, code and such, that way its standard in all places

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +                </div>
Consider separating it out into a component something like `ScannedSpecimen`

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +          </div>
Separate component, `ReceiveSpecimenForm`

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/CollectSpecimen.tsx
> +                  Active
make it dynamic

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/CollectSpecimen.tsx
> +          } `}
do not use string template for classNames, its hard to read, use cn util from lib, 

change this in other places if any

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/SendSpecimenForm.tsx
> +];
use getAllFacilities api to get the data from backend with filter 9, 10 (Govt Lab and Private Lab) for facility type

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/LabObservationQuestion.tsx
> +export const LabObservationQuestion: React.FC<LabObservationQuestionProps> = ({
Just rename this component to `DiagnosticReportForm` or something in that terms as this not a question (part of questionnaire)


Also move the LabObservationItem component into the same (this) file

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/LabObservationQuestion.tsx
> +  setObservations,
use shadcn form component and react hook form to maintain the states and enforce validation

2025-01-14 04:33 UTC, khavinshankar commented on public/images/half_circle.svg
Remove these svgs, let's use library icons as much as possible, 

Also, this half circle should be implemented as logic, should be dynamic

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Common/ServiceRequestTimeline.tsx
> +    | "notStarted";
this seems very specific to lab orders, lets make it generic, may be like `completed` | `in-progress` | `yet-to-start` or consider using number like percentage for progress,

here is a thought
```ts
type Step = {
  index: number;
  title: string;
  progress: number;
  subSteps: Step[];
};
```

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ProcessSpecimen.tsx
> +            id: uuid(),
id will be auto created, is there any reason for this, setting it in the frontend?

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ProcessSpecimen.tsx
> +  const [observations, setObservations] = useState<LabObservation[]>([]);
use shadcn form and react hook form for state and validation

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ProcessSpecimen.tsx
> +            {diagnosticReport.status !== "preliminary" && (
use pharse field from based_on

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReviewResult.tsx
> +        : "notStarted";
use phase field from request.phase

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReviewResult.tsx
> +            {path.includes("/result") ? t("results") : t("review_result")}
create separate page for review result and showing result

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReviewResult.tsx
> +          </div>
Seperate component, here and also in collect specimen

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReviewResult.tsx
> +                      </div>
Separate component

2025-01-14 04:33 UTC, khavinshankar commented on src/components/Lab/pages/ReviewResult.tsx
> +                        </div>
form

2025-01-14 10:16 UTC, yash-learner commented on src/components/Lab/pages/ReceiveSpecimen.tsx
> +  });
Once we have this data on our HL7 server, will make it dynamic

2025-01-14 20:52 UTC, yash-learner commented on src/components/Lab/pages/CollectSpecimen.tsx
> +                  Active
Currently, we are always getting status as `draft` from backend

2025-01-15 16:05 UTC, yash-learner commented on src/components/Lab/SendSpecimenForm.tsx
> +];
Done https://github.com/ohcnetwork/care_fe/pull/9260/commits/e90ecbcb0f21e996f0ebb66aa8c8747d6bb0fbd5

2025-01-16 19:36 UTC, yash-learner commented on src/components/Lab/pages/ProcessSpecimen.tsx
> +            id: uuid(),
@khavinshankar 

> id will be auto created, is there any reason for this, setting it in the frontend?

Yeah, actually we have `id` field in https://github.com/yash-learner/care_fe/blame/1f02c25a30474a7dc919fc7948569ca7f38ab860/src/Utils/request/api.tsx#L758

and also backend is expecting an `id`, without that it is raising an error 



```
Execution time: 0.001358s [Database: default]
172.18.0.1 - - [17/Jan/2025 00:44:06] "POST /api/v1/diagnostic_report/18b8c5f8-3fad-400d-aef0-d85a931e92b0/observations/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 2761, in to_python
    return uuid.UUID(**{input_form: value})
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/uuid.py", line 181, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
    
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/care/emr/api/viewsets/diagnostic_report.py", line 86, in observations
    observation_instances = Observation.objects.bulk_create(observations)
  File "/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 835, in bulk_create
    returned_columns = self._batched_insert(
    
  File "/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1875, in _batched_insert
    self._insert(
    ^
  File "/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1835, in execute_sql
    for sql, params in self.as_sql():
                       ~~~~~~~~~~~^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1760, in as_sql
    self.prepare_value(field, self.pre_save_val(field, obj))
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1699, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 2751, in get_db_prep_value
    value = self.to_python(value)
  File "/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 2763, in to_python
    raise exceptions.ValidationError(
    ^
django.core.exceptions.ValidationError: ['“” is not a valid UUID.']


//payload from fe without id


{
  "observations": [
    {
      "main_code": {
        "code": "100-8",
        "display": "Cefoperazone [Susceptibility] by Minimum inhibitory concentration (MIC)",
        "system": "http://loinc.org"
      },
      "value": {
        "value": "7"
      },
      "status": "final",
      "effective_datetime": "2025-01-16T19:14:06.277Z",
      "data_entered_by_id": 7,
      "subject_type": "patient",
      "note": "yuytutyut",
      "value_type": "quantity",
      "created_by_id": 7,
      "updated_by_id": 7
    }
  ]
} 

🤔

2025-01-17 07:32 UTC, khavinshankar commented on src/components/Lab/pages/ProcessSpecimen.tsx
> +            id: uuid(),
lets keep the uuid then

2025-03-05 06:39 UTC, rithviknishad commented
we can re-open this once things are resumed

cc: @khavinshankar

2025-03-05 06:39 UTC, closed without merging