Replace custom useQuery util with TanStack useQuery
coronasafe/care_fe pull request #9360
Opened 2024-12-10 20:15 UTC by amjithtitus09

## Proposed Changes

- Fixes #issue_number
- Replaced custom useQuery util with tanStack useQuery, along with a wrapper for backward compatibility
- Added documentation for tanStack usage as well as wrapper usage

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-12-11 04:22 UTC, rithviknishad approved these changes
This approach LGTM. 

Just something to note, our `request` function does perform query retries by itself. And in this implementation Tanstack's Query Client has retry configured to 1. 

We could modify our `request` to not perform retries.

https://github.com/ohcnetwork/care_fe/blob/b25ecd001b117624cb4b279f7078232ea2f4fdb4/src/Utils/request/request.ts#L53

2024-12-11 04:42 UTC, rithviknishad requested changes

2024-12-11 04:42 UTC, rithviknishad commented on src/Utils/request/useTanStackQueryInstead.ts
> +  };
When calling `refetch` in this implementation, we are bypassing tanstack's useQuery invocation made above altogether. This means the returned `data`, `res`, etc. by `useTanStackQueryInstead` is only of the first request and not of subsequent requests.

Hence the `refetch` called for the current auth user when signIn is invoked, the original states aren't updated. Same for signOut and other similar usages in CARE.

2024-12-11 04:44 UTC, rithviknishad commented on src/Utils/request/useTanStackQueryInstead.ts
> +  };
Let's instead use tanstack's useQuery's `refetch` itself instead?

2024-12-11 04:47 UTC, rithviknishad commented on src/Utils/request/useTanStackQueryInstead.ts
> +  });
In this new approach, we are no longer having the ability to abort requests right? We could modify the `request` to take in a `signal` and use the signal provided by tanstack's useQuery's `queryFn`.

```suggestion
export default function useTanStackQueryInstead<TData>(
  route: QueryRoute<TData>,
  options?: QueryOptions<TData>,
) {
  const { data: response, isLoading } = useQuery({
    queryKey: [route.path, options?.pathParams, options?.query],
    queryFn: async ({ signal }) => {
      return await request(route, options, signal);
    },
    enabled: options?.prefetch ?? true,
    refetchOnWindowFocus: options?.refetchOnWindowFocus,
  });
```

2024-12-11 05:35 UTC, rithviknishad commented
<img width="1673" alt="image" src="https://github.com/user-attachments/assets/579342f9-5019-49aa-a365-3a60cb3ac089">

Since we have plugins, this approach isn't backwards compatible. We might have to stick with same file and function name `useQuery` instead of `useTanstackQuery` instead.

We just have to be careful when importing in new usages. However, `@deprecated` tag does help there.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/ea57efe2-580d-4028-9cbf-172834cf7caa">

2024-12-11 06:54 UTC, rithviknishad commented
Looks like there's an issue with refetching when component remounts.

Example: when we go to asset list page, and open an asset and go back to asset list page using the back button, it shows no assets found.

2024-12-11 12:10 UTC, rithviknishad commented
Opted out of caching between usages of the useQuery that has the same query key. This was causing so many weird state management issues with our existing implementation.

Cache for the same useQuery invocations is still present as per defaults.

2024-12-11 12:10 UTC, rithviknishad approved these changes

2024-12-12 00:14 UTC, bodhish commented
@coderabbitai full review

2024-12-12 06:13 UTC, Jacobjeevan approved these changes
Since we merged Users redesign FE yesterday, there's a few more instances of useQuery that ought to be replaced.

Other than that, LGTM.

2024-12-12 06:25 UTC, shivankacker approved these changes

2024-12-12 06:32 UTC, rithviknishad commented
> Since we merged Users redesign FE yesterday, there's a few more instances of useQuery that ought to be replaced.

Done, thanks for finding that miss!

2024-12-12 07:15 UTC, merged