Added medication statement question
coronasafe/care_fe pull request #9528
Opened 2024-12-22 07:14 UTC by khavinshankar

## Proposed Changes

- Added medication statement question

Screenshot:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/f5b31042-9664-404d-bbf5-ecff6477f227" />

@ohcnetwork/care-fe-code-reviewers

2024-12-22 08:29 UTC, bodhish commented
Lets keep it simple? 
<img width="744" alt="image" src="https://github.com/user-attachments/assets/de5b21e5-0346-4e11-ab15-80736b0817f2" />


- Keep doasage as text
- Make soruce a dropdown. Default to patient
- Should we rename effective period to Started and Ended? Something simpler for users?

2024-12-22 08:37 UTC, bodhish requested changes
Lets also add a list of ongoing medications to the health profile page. `/facility/ID/patient/ID/health-profile`

2024-12-22 08:37 UTC, bodhish commented on src/types/questionnaire/base.ts
> +  id?: string;
Does it have an ID 🤔 

Coudn't find one in FHIR spec https://build.fhir.org/datatypes.html#period

2024-12-22 08:37 UTC, bodhish commented on src/types/emr/medicationStatement.ts
> +  information_source?: MedicationStatementInformationSourceType;
This should an enum!

2024-12-22 08:37 UTC, bodhish commented on src/types/emr/medicationStatement.ts
> +  dosage?: string;
Call it `dosage_text` so that we are clear that we storing the information as text

2024-12-23 17:25 UTC, bodhish commented
@khavinshankar ping me once you push the changes

2024-12-27 06:11 UTC, khavinshankar commented
Updated UI:
<img width="542" alt="image" src="https://github.com/user-attachments/assets/4610b449-61e4-4559-8e5a-e13cce5963d6" />

2024-12-27 06:28 UTC, merged