Patient encounter notes
coronasafe/care_fe pull request #9617
Opened 2024-12-30 22:07 UTC by bodhisha

## Proposed Changes

- Patient encounter notes

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2024-12-30 22:09 UTC, bodhish commented
@coderabbitai review

2024-12-31 09:40 UTC, rithviknishad requested changes

2024-12-31 09:40 UTC, rithviknishad commented on src/types/notes/threads.ts
> +}
unused type and duplicate of `PaginatedResponse<Thread>`

```suggestion
```

2024-12-31 09:40 UTC, rithviknishad commented on src/types/notes/messages.ts
> +}
unused type and duplicate of `PaginatedResponse<Message>`

```suggestion
```

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +                  {t("Create")}
```suggestion
                  {t("create")}
```

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +            {t("Create New Thread")}
translation keys missing in en.json, needs to be added as mentioned in Merge Checklist

```suggestion
            {t("create_new_thread")}
```

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +      })({ signal: new AbortController().signal });
won't we get `signal` from the `queryFn`'s callbacks args itself? 🤔 

```suggestion
    queryFn: async ({ pageParam = 0, signal }) => {
      const response = await query(routes.notes.patient.getMessages, {
        pathParams: {
          patientId: encounter.patient.id,
          threadId: selectedThread!,
        },
        queryParams: {
          limit: String(LIMIT),
          offset: String(pageParam),
        },
      })({ signal });
```

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +      isSelected ? "bg-primary/10" : "hover:bg-muted"
we don't have `muted` color configured/defined.

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +};
We can reuse the existing `Avatar` component right?

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +}
This is already defined in `src/Utils/request/types.ts`, let's not redefine it

2024-12-31 09:40 UTC, rithviknishad commented on src/Utils/request/api.tsx
> +  },
since these APIs are part of encounter, wouldn't it be appropriate to nest this inside `encounter` instead?

2024-12-31 09:40 UTC, rithviknishad commented on src/pages/Encounters/EncounterShow.tsx
> +import { EncounterNotesTab } from "./tabs/EncounterNotesTab";
switch to absolute imports

2025-01-01 16:48 UTC, bodhish commented on src/Utils/request/api.tsx
> +  },
It will be the same for both patient and encounter

2025-01-01 16:49 UTC, bodhish commented on src/pages/Encounters/tabs/EncounterNotesTab.tsx
> +      isSelected ? "bg-primary/10" : "hover:bg-muted"
Nice find

2025-01-06 12:24 UTC, merged