issue #964, List active shifting records inside patient page
coronasafe/care_fe pull request #973
Opened 2021-04-25 05:27 UTC by khavinshankar

added active shifting record inside patient page

2021-04-25 05:42 UTC, khavinshankar commented
The UI looks like this,
![image](https://user-images.githubusercontent.com/29787772/115982216-08ca3580-a5b7-11eb-9114-c02d37673e14.png)

2021-04-25 15:04 UTC, tomahawk-pilot commented
looks good to merge

2021-04-25 15:04 UTC, tomahawk-pilot approved these changes

2021-04-26 03:51 UTC, riginoommen requested changes

2021-04-26 03:51 UTC, riginoommen commented on src/Components/Patient/PatientHome.tsx
> +                      (shift.patient_object.disease_status == "POSITIVE"
```suggestion
                      (shift.patient_object.disease_status === "POSITIVE"
```

2021-04-26 03:51 UTC, riginoommen commented on src/Components/Patient/PatientHome.tsx
> +                              {(shift.orgin_facility_object || {}).name}
```suggestion
                              {(shift.orgin_facility_object || {})?.name}
```

2021-04-26 03:51 UTC, riginoommen commented on src/Components/Patient/PatientHome.tsx
> +                              {(shift.shifting_approving_facility_object || {}).name}
```suggestion
                              {(shift.shifting_approving_facility_object || {})?.name}
```

2021-04-26 03:51 UTC, riginoommen commented on src/Components/Patient/PatientHome.tsx
> +                              {(shift.assigned_facility_object || {}).name ||
```suggestion
                              {(shift.assigned_facility_object || {})?.name ||
```

2021-04-26 14:14 UTC, amit-kr-debug commented
Looks like 
![image](https://user-images.githubusercontent.com/68914475/116097421-c04e6d00-a6c7-11eb-9c86-0ace80c93af3.png)

2021-04-26 14:28 UTC, khavinshankar commented
@vigneshhari can you give it check

2021-04-26 17:07 UTC, merged